### ISSUE TITLE
[Question] How to handle styling for card being dragged

### ISSUE THREAD

**Issue by buddythumbs** [rcdexta/react-trello#100]
Hi, 

Currently when I drag a card I get this yellow background color:

![image](https://user-images.githubusercontent.com/24975408/41791114-10106a60-7655-11e8-8d5f-9758e5609625.png)

How can I change this styling?

I've looked at the props being passed to custom card component but I don't see a "isDragging" prop (or something similar).

Help is greatly appreciated

**Comment by rcdexta** [comment]
![drag_style](https://user-images.githubusercontent.com/900028/42129331-d8ad2284-7c76-11e8-8fe9-8e8e36d420a1.gif)

Added new props `cardDragClass` and `laneDragClass`  to customize appearance of lane and card being dragged.

Refer to storybook for example: https://github.com/rcdexta/react-trello/blob/master/stories/DragDrop.story.js#L56-L64

**Comment by buddythumbs** [comment]
Hi @rcdexta,

Thanks for adding this - however, I am using `styled-components` in my code (very little .css files) so would like to be able to access a `isDragging` prop inside the card so that I can use string interpolation to style the card.

Something like:

```
const TaskCard = styled.div`
  margin: 5px;
  position:relative;
  background-color: ${ (props) => props.isDragging ? 'black' : 'white' } ;
`
   ...

<TaskCard 
    key={props.id}
    id={props.id}
    isDragging={props.isDragging}
>
        <div>
          <TaskTool>{props.title}</TaskTool>
        </div>
        <div>
          { props.label }
        </div>
</TaskCard>
```

I would be willing to help on this but I have not contributed to anyone else's code on github except my own!

Thanks,
M

**Comment by rcdexta** [comment]
The drag-n-drop library that react-trello uses as a concept called ghost element styling that is used to apply styling to an element when it is being dragged. It only accepts a css class and no style objects and hence this library is exposing the same.

@buddythumbs react-trello uses `styled-components` library as well. You can add css style classes as seen here:
https://github.com/rcdexta/react-trello/blob/master/src/styles/Base.js#L15-L21

**Comment by buddythumbs** [comment]
Hey,

I'm using `"react-trello": "^1.32.2",` and using the following to style a dragging card:
```
 injectGlobal`
  .draggingCard {
      background-color: #7fffd4;
      border: 1px dashed #a5916c;
      transform: rotate(10deg);
  }
`


<Board 
  data={data} 
  style={{
    ...this.props.style,
    backgroundColor: 'transparent',
    paddingTop: 50,
    height: '65vh',
  }}
  draggable
  cardDragClass='draggingCard'
  customCardLayout
  addCardLink={<FlatButton label="Add" />}
  customLaneHeader={<LaneHeader />}
  handleDragEnd={::this.handleChange}
  onCardClick={(cardId, metadata) => ::this.openItem(metadata)}
>
    <Task/>
  </Board>

```

where `<Task/>` is my custom component for the card.

However, I am still getting the yellow background like previous - am I on the correct version?

Thanks

**Comment by avillarubia-stationfive** [comment]
someone can answer this?

**Comment by avillarubia-stationfive** [comment]
hi, cardDragClass is not working @rcdexta 

```
 <Board
      style={{
          backgroundColor: 'transparent',
      }}
      components={components}
      data={dealsData}
      draggable
      editable
      laneDraggable={false}
      editable={false}
      canAddLanes={false}
      cardDragClass={{
          backgroundColor: 'red',
      }}
      onCardMoveAcrossLanes={(fromLaneId, toLaneId, cardId, index) =>
          handleCardDrag(fromLaneId, toLaneId, cardId, index)
      }
  />
```

**Comment by garimahans15** [comment]
I am also facing a similar issue. Can someone answer how to handle this scenario

**Comment by wallace-sf** [comment]
How can i style lane when i drag a card?

**Comment by Gabriel637** [comment]
Hello @wallace-sf I did this, because when I tried to set state to handle the class the board broke
```
  const dragStart = () => {
    const board = document.getElementsByClassName('boardContainer')[0];
    board.classList.add(classes.dragging);
  };

  const dragEnd = () => {
    const board = document.getElementsByClassName('boardContainer')[0];
    board.classList.remove(classes.dragging);
  };
  
      <Board
      className={`${classes.board} boardContainer`}
      handleDragStart={() => {
        dragStart();
      }}
      handleDragEnd={() => {
        dragEnd();
      }}
    />
```

**Comment by elvishuges** [comment]
d
