### ISSUE TITLE
Is it possible to have the lanes wrap to prevent horizontal scroll?

### ISSUE THREAD

**Issue by leebailey88** [rcdexta/react-trello#101]
**Is your feature request related to a problem? Please describe.**
I have a lot of lanes (about 15), and I would like them to wrap to multiple rows so the user can see all of them at the same time without having to scroll horizontally.

**Describe the solution you'd like**
A config enabling lane wrapping.

**Describe alternatives you've considered**
I've already overrided the style to remove the `white-space: nowrap` which works somewhat but with a big problem--the lane dragging breaks which is another feature that I want to use.

**Comment by rcdexta** [comment]
@leebailey88 A Kanban board in its essence has lanes that are horizontally stacked and cards stacked vertically against them. Breaking that layout style can make things confusing for users when re-arranging lanes and other UX use-cases.

If you are still inclined to vertically stack lanes, `react-trello` supports rendering multiple boards at the same time as seen here: http://rcdexta.me/react-trello/?selectedKind=Multiple%20Boards&selectedStory=Two%20Boards&full=0&down=0&left=1&panelRight=0

May be that might serve your use-case....
