### ISSUE TITLE
The style under IE11 is wrong

### ISSUE THREAD

**Issue by changyu72** [rcdexta/react-trello#102]
The style under IE11 is wrong，

**Comment by changyu72** [comment]
![Uploading 2018-07-31_11-02-42.gif…]()

**Comment by changyu72** [comment]
![2018-07-31_11-02-42](https://user-images.githubusercontent.com/18181509/43435651-83ae9cb8-94b3-11e8-8d49-c0e2e3ec98e5.gif)

**Comment by KosherHotDog** [comment]
![screen shot 2018-08-14 at 2 52 51 pm](https://user-images.githubusercontent.com/18075726/44120625-cb8b4706-9fd1-11e8-9e37-742b3eb6d1a1.png)
This is a similar issue occurring with chrome and safari.  I found that the issue seems to be with height:auto, any thoughts?

**Comment by changyu72** [comment]
fiexd

**Comment by jlbmagic** [comment]
Hi. Is this fixed in the latest NPM build? I didn't see a version change, and my project isnt picking up the fix.

**Comment by changyu72** [comment]
Sorry ，only in my local

**Comment by jlbmagic** [comment]
Okay. How do I fix it locally? Is there a height style to pass to the lanes?

**Comment by KosherHotDog** [comment]
The solution i found was to go to Base.js and change ScrollableLane flex:1 to display:flex.

**Comment by jlbmagic** [comment]
Is this fixed in the npm build yet?
