### ISSUE TITLE
Limit cardDraggable to their own lanes?

### ISSUE THREAD

**Issue by nayayan** [rcdexta/react-trello#104]
I need to have my cards only draggable in their own lanes to be reordered but never switched categories.

If I could have a simple config or prop like 'cardSortableOnly={true}'.

Maybe there is a way to return false on 'handleDragEnd' and prevent the switch?

Thanks in advance for your help!

FOUND A TEMPORARY SOLUTION : 
`handleDragEnd(cardId, sourceLaneId, targetLaneId, position, cardDetails) {
    if (sourceLaneId !== targetLaneId) {
      const boardData = this.state.boardData
      this.setState({
        boardData: {
          lanes: []
        }
      })
      this.setState({ boardData })
    }
  }`

It forces (kinda dirty) to re-render from original state if the lane is different... works for me now! ;)

Still waiting for a clean solution... plz?...

**Comment by andrewb273** [comment]
To add to this - I want to be able to have a card draggable within its own lane, or to another lane but preserve the ordering. I believe this is the typical experience that JIRA offers, with the rational being that if you're changing status, you're not trying to change priority.

**Comment by rcdexta** [comment]
Hi @nayayan, planning to add a assertion function called 

`canAcceptDrop(cardId, sourceLaneId, targetLaneId)` that if defined as prop must return `true` for the drag-n-drop to be completed successfully. Let me know if that works for you. That way it gives the developer complete flexibility to put restrictions on drag-n-drop as needed.

Will add it in coming week. Sorry for getting back late on this one!

**Comment by rcdexta** [comment]
@andrewb273 If I understand you right, you would like to know the exact position at which the card is inserted in another lane or the same lane. This is already available in the callback function:

`handleDragEnd(cardId, sourceLaneId, targetLaneId, position, card)`

as 4th argument. The order is preserved in the entire lifecycle of the state. Let me know what I am missing!?

**Comment by rcdexta** [comment]
Yeah I get what you are saying. The global order use-case sounds to be specific outside of the general realm of this library. Thanks anyway!

**Comment by marcshilling** [comment]
> Hi @nayayan, planning to add a assertion function called
> 
> `canAcceptDrop(cardId, sourceLaneId, targetLaneId)` that if defined as prop must return `true` for the drag-n-drop to be completed successfully. Let me know if that works for you. That way it gives the developer complete flexibility to put restrictions on drag-n-drop as needed.
> 
> Will add it in coming week. Sorry for getting back late on this one!

Hi @rcdexta, did this `canAcceptDrop` prop ever get added? I'm not seeing it in the repo but I could use this functionality myself!

**Comment by johhansantana** [comment]
I'm also looking for something like this. I want the cards to only be able to drag and drop in the same lane and not the others or specific ones.
