### ISSUE TITLE
Can add [Add Lane] Button ? like this

### ISSUE THREAD

**Issue by changyu72** [rcdexta/react-trello#106]
This is what I added. Can you add it, or can I submit the code?
![2018-08-15_09-43-03](https://user-images.githubusercontent.com/18181509/44127511-320da318-a070-11e8-92ac-55c7222c7fb7.gif)

**Comment by changyu72** [comment]
added

**Comment by rcdexta** [comment]
This looks awesome! Please submit PR

**Comment by CodyFitzpatrick** [comment]
@changyu72 I'd love to see the source of your app, not only the "+ Add A Lane" button, but the add new card functionality as well (the "Cancel" button in addition to the standard repo's "Add Card" button).

Would love for you to submit a PR per @rcdexta's request!

**Comment by CodyFitzpatrick** [comment]
@changyu72 Would love for you to submit a PR for this functionality per @rcdexta's request! Am going to implement this functionality on my own if we are unable to share the fruits of your labor. :)

**Comment by changyu72** [comment]
@rcdexta , @CodyFitzpatrick : I would like to share this function，but I need time to clear up the local code，if this work finished，will submit PR.

**Comment by changyu72** [comment]
@rcdexta  The code is attached. Please integrate it，thanks！
[react-trello-fixed-src.zip](https://github.com/rcdexta/react-trello/files/2409476/react-trello-fixed-src.zip)

**Comment by changyu72** [comment]
Can you issue the problem? 

I don't know how to update npm。

**Comment by rcdexta** [comment]
@changyu72 I will take care of reviewing the changes and releasing it to npm today. But, however looks like the archive is invalid and cannot be extracted. Can you send me  patch of just ur changes. If . you have the commit hash.. just run this command 

`git format-patch -1 HEAD` and share the file generated..

Thanks.

**Comment by mehuljariwala** [comment]
@rcdexta  Just install 7-zip in your pc and extract it

**Comment by mehuljariwala** [comment]
@rcdexta Once done newLane Changes just messgage me i will update in my code..

**Comment by changyu72** [comment]
Ok，I only have to do this tomorrow， no time today.

**Comment by rcdexta** [comment]
@changyu72 No worries. Thanks for code changes.

I took that as baseline and worked on more fixes on top of it. `Add new lane` functionality now works end-to-end with the event bus too! 

Please pull 2.0.1 for the latest changes

**Comment by rcdexta** [comment]
You can see the feature in action here:

https://rcdexta.me/react-trello/?selectedKind=Editable%20Board&selectedStory=Add%20New%20Lane&full=0&addons=0&stories=1&panelRight=0

**Comment by mehuljariwala** [comment]
@rcdexta Thank you sir for integrating code in it.
 but once i add newLane then how to delete newLane,
Suppose i want to delete newLane is its possible ?
@changyu72 any Solutions for that ?

**Comment by mehuljariwala** [comment]
> Thanks @rcdexta

Sir any help for delete lane
