### ISSUE TITLE
Not clear how to add, remove or modify the card using .publish

### ISSUE THREAD

**Issue by adamklepacz** [rcdexta/react-trello#109]
Hey, 
I'm trying to build my own trello app using react-trello. 
Currently my app is able to create new lane, but I'm stuck on how to add new card within a lane. 
I was trying to use these publish methods, but I'm getting error like "TypeError: Cannot read property 'publish' of undefined".

Can someone help me on how to add new card to existing lanes??
I'm using only a Board component without customCard component.

**Comment by rcdexta** [comment]
Looks like an issue with setting the `eventBus` handle. See example code about using the event bus here:
https://github.com/rcdexta/react-trello/blob/master/stories/Realtime.story.js#L19-L22

See example behaviour here:
http://rcdexta.me/react-trello/?selectedKind=Advanced%20Features&selectedStory=Realtime%20Events&full=0&down=0&left=1&panelRight=0
