### ISSUE TITLE
Add new card link is missing when using newCardTemplate

### ISSUE THREAD

**Issue by adamklepacz** [rcdexta/react-trello#110]
**Describe the bug**
After use of newCardTemplate on a Board component, Add card button is hidden after I press it for the first time on every single lane and it never appears again.

**Expected behavior**
Expected behavior should be: Using newCardTemplate we should be able to see Add Card button every time we add new card to the current lane.

**Desktop (please complete the following information):**
 - OS: Mac OSX Sierra
 - Browser Chrome@latest

**Comment by rcdexta** [comment]
@adamklepacz closing this issue as it needs more details...
