### ISSUE TITLE
[CSS] Cards render slightly outside the lane when scrollbar active

### ISSUE THREAD

**Issue by leebailey88** [rcdexta/react-trello#111]
**Describe the bug**
When a lane has a lot of cards, a vertical scrollbar appears which pushes the cards to render slightly outside their container lane (see screenshot)

**To Reproduce**
1. Add enough cards to a lane to trigger vertical scrollbar

**Expected behavior**
The scrollbar would either render outside the lane or the card width would shrink when a scrollbar was present to remain inside the lane

**Screenshots**
![screen shot 2018-09-04 at 5 21 38 pm](https://user-images.githubusercontent.com/5678278/45064177-285b6b00-b067-11e8-9988-37dfb9bbd01b.png)

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Chrome
 - Version 68

**Comment by rcdexta** [comment]
@leebailey88 Can you give me more details or share the code where you face the error. From the screenshot, looks like the default lane width has been modified. I have test cases where a lane has numerous cards and I don't see this styling issue:

http://localhost:9002/?selectedKind=Basic%20Functions&selectedStory=Infinite%20Scrolling&full=0&down=0&left=1&panelRight=0

**Comment by rcdexta** [comment]
@leebailey88 closing this issue for now. happy to help you if you can provide more details
