### ISSUE TITLE
Card drag and drop problem while using sorting

### ISSUE THREAD

**Issue by prachi0708** [rcdexta/react-trello#113]
Hi,
I am facing issue during drag and drop of card. While dropping card at different location, card other then dragged card is dropped. It is because "this.state.Result" has data in different sequence and after applying sort "laneSortFunction" result is sorted on view only and on "this.state.Result" it remains in unsorted form. So, dropped card is the card which is at that position in "this.state.Result". 

What changes I should made to make my code work as expected.

```
laneSortFunction(card1, card2){
        if (card1.Amount > card2.Amount)
          return -1;
        if (card1.Amount < card2.Amount)
          return 1;
        return 0;
    }
```

```
                <Board 
                        data={this.state.Result}
                        customCardLayout
                        draggable={this.state.draggable}
                        laneSortFunction={this.laneSortFunction}
                        handleDragEnd={this.handleDragEnd}
                        handleDragStart={this.handleDragStart}
                        laneDraggable={false}>
                         <CustomCard />
                     </Board>; 
```

**Desktop**
 - Linux
 - Chrome

**Comment by CodyFitzpatrick** [comment]
Data represented on the front-end is saved on the backend (well, technically still front-end, since React is JS), so you simply want to grab the output of `laneSortFunction` and save it to `this.state.Result`. This should lead to congruency between what you are seeing and the actual state of the app.

**Comment by rcdexta** [comment]
@prachi0708 If you pass laneSortFunction as props, you are telling the Lane component that the cards must be sorted in a specific way. So, this applies to newly dragged cards to the lane as well and they will be sorted using this logic after they are dropped. 

Either you can reuse the laneSortFunction to calculate state again and subscribe to `onDataChange` which will publish the lane data in the new order as rendered on the UI.

**Comment by otomatik** [comment]
Hi @rcdexta 
I just faced the same issue as @prachi0708 
I tested but can't verify this statement:
> Either you can reuse the laneSortFunction to calculate state again and subscribe to `onDataChange` which will publish the lane data in the new order as rendered on the UI.

While cards are correctly sorted on the UI after the `laneSortFunction` has been applied, I get notified by `onDataChange` but they remain in the in the initial order in the resulting `data`.
Is there something I'm missing?
Thanks in advance,
