### ISSUE TITLE
[Very Minor] Function defined twice in Realtime.story.js

### ISSUE THREAD

**Issue by CodyFitzpatrick** [rcdexta/react-trello#114]
`modifyLaneTitle()` is defined twice in https://github.com/rcdexta/react-trello/blob/master/stories/Realtime.story.js.

This does not affect demo or app functionality whatsoever, but wanted to leave this here in case you wanted to clean that story file up. There may be other duplicate functions in other story files, but I have not yet had a chance look through them all.

Thanks for creating this.

**Comment by rcdexta** [comment]
@CodyFitzpatrick Thanks for reporting this. Fixed
