### ISSUE TITLE
How to check that which card is move to which lane

### ISSUE THREAD

**Issue by mehuljariwala** [rcdexta/react-trello#118]
I want to check that which card is moving to one lane to other lane is there any option to checking the card current positions.
@rcdexta 
Thanks you.!
Mehul Jariwala

**Comment by changyu72** [comment]
Board's event：
move card:
handleDragEnd = (cardId, sourceLaneId, targetLaneId, newPosition, _card){
 ...
}
move lane:
 handleLaneDragEnd = (removedIndex, addedIndex){
...
}

**Comment by CodyFitzpatrick** [comment]
@mehuljariwala, like @changyu72 , there is a method provided by the board called `handleDragEnd`, which automatically receives certain parameters like `targetLaneId`, which is what you are looking for. Whatever you need to do with this value, process it and/or save it to the state within that function.

**Comment by G-Rath** [comment]
@mehuljariwala It sounds like you've got a solution to your problem, so I'm going to close this issue for now.

Feel free to re-open it if there's still something wrong, thanks!
