### ISSUE TITLE
Allow for easy lane styling

### ISSUE THREAD

**Issue by xforesttree** [rcdexta/react-trello#123]
--Updated with new screenshot--

Currently we generate our data with function and are perfectly happy with the cards we've created, but despite increasing the lane size it does not show the entire card. Why isn't there a prop for css outside of drag events (not that we want it different during drag events, but others might)
![blacked out](https://user-images.githubusercontent.com/43811884/47653752-94e77780-db89-11e8-8f71-cf8f63f2ad9e.png)

**Comment by ogsalman** [comment]
I need a way to style the lanes, how can I do this?

**Comment by xforesttree** [comment]
> I need a way to style the lanes, how can I do this?

The only way I currently know is to give it a style prop, but it does not solve my problem

**Comment by rcdexta** [comment]
Refer to this section for notes on styling any of the components:

https://github.com/rcdexta/react-trello#styling

Also sample storybook illustrating the same:

http://rcdexta.com/react-trello/?selectedKind=Styling&selectedStory=Lane%20Styling&full=0&addons=0&stories=1&panelRight=0
