### ISSUE TITLE
How can i Remove Scrollbar Loading Events ?

### ISSUE THREAD

**Issue by mehuljariwala** [rcdexta/react-trello#124]
Hello,
I am facing some problem when i used scrollbar when i add OnLaneScroll its working fine but at the end 
one loading spinner is coming i need to remove that spinner is there any way to remove Spinner..
Thank you,
Mehu Jariwala.

**Comment by rcdexta** [comment]
@mehuljariwala That spinner is a UI feedback to the user saying a promise is called on `OnLaneScroll` and for the user to wait for more data. Later on we might offer the ability to customize the spinner, but for not cannot be disabled.
