### ISSUE TITLE
Multiple card selection (a bulk move for example)

### ISSUE THREAD

**Issue by mastermad** [rcdexta/react-trello#125]
Hi,

Great work, great component, pleased with it but i wonder if there is any chance to add multiple card selection behavior? (ex : i want to move multiple cards)

Thanks a lot for the help.

**Comment by rcdexta** [comment]
This library tries to stay true the features offered by the original trello/kanban board. It should be possible to add multi-select behavior if you pass your own custom card template so that you can decide to add checkboxes or some UI element to let the user select multiple cards at the same time.
