### ISSUE TITLE
Lanes with "Ongoing" and "Done" sides

### ISSUE THREAD

**Issue by sylvain-hamel** [rcdexta/react-trello#127]
**Is your feature request related to a problem? Please describe.**
In Kanban literature, it is common for "Lanes" to be divided in two : "Ongoing" and "Done". This helps visually but also helps enforcing the max WIP of a column, because the Max WIP restricts the number of item in the Lane (both sides added up). See this screenshot: http://blog.crisp.se/henrikkniberg/images/qconsf-2009-kanban.jpg

**Describe the solution you'd like**
I'd like a Lane to have a prop to enable a "split mode" and props to set the subtitle of each side of the lane.

**Describe alternatives you've considered**
If lane styling allows it (I did not explore this yet) I might be able to simulate this by using zero margin/padding between two lanes, and only use margin between my "real" lanes. But I don't know how I'd handle the subtitle aspect of this.

**Comment by rcdexta** [comment]
You can use the custom lane templating to build this on your own. Examples available here:
http://rcdexta.com/react-trello/?selectedKind=Custom%20Templates&selectedStory=Custom%20Lane%20Template&full=0&addons=0&stories=1&panelRight=0

Since this is a very special request for customization, it is unlikely that it should be added to the library itself. Thanks @sylvain-hamel

**Comment by sylvain-hamel** [comment]
Hi @rcdexta , it's totally fine to reject this feature request. I was able to make it work using CSS. Here is what it looks like. I'm not done yet but you get the idea.

![image](https://user-images.githubusercontent.com/1754010/50108150-88cf7c00-0202-11e9-9385-e62f7d07c2ad.png)

**Comment by rcdexta** [comment]
Yup this looks good and I understood what you meant initially to have a done section. If you were able to do this using custom lane templating, pls do share the code and I include it in the storybook for the benefit of others. Thanks
