### ISSUE TITLE
cannot get drag to work

### ISSUE THREAD

**Issue by nodefiend** [rcdexta/react-trello#13]
Greetings!

I see that you made fixes to bugs, but I cannot seem to get the drag to work.

Also your example is not working either.

PLease advise when you get the chance!

**Comment by rcdexta** [comment]
I have added drag-n-drop to the sample repo just to check if latest version works fine:

Please pull latest from https://github.com/rcdexta/react-trello-example

Seems to work as expected. Let me know the browser u use and specific error, if any, that you see in the console

**Comment by nodefiend** [comment]
thanks so much for this ! appreciated!
