### ISSUE TITLE
Need Customize Lane component

### ISSUE THREAD

**Issue by abdulkhaliquem9** [rcdexta/react-trello#130]
I want to customize the Lane component in a way that it can have multiple sections.
For Example
If I have LightVehicles card I want to have sections for 2 wheeler, 3 wheeler, 4 wheeler.

Currently what I am doing is, I am adding a 'type' property for each card, and while displaying it with a different color based on the type. In my case 2, 3, and 4 wheeler.

The problem here is, when I am dragging 2 wheeler over to the other lane, say for example HeavyVehicles, then, I have to again sort the whole lane to differentiate between the 2,3, & 4 wheelers.
I want to have a Title for each section.

Or also we can have nested lanes, but having an option to customize the Lane Component will be much easier.

**Comment by rcdexta** [comment]
@abdulkhaliquem9 The library supports straight forward use-cases trying to keep the design closer in spirit to a trello board. 

But, you are free to customize the lane look-and-feel by defining your own custom template:

Refer example here:
https://rcdexta.me/react-trello/?selectedKind=Custom%20Templates&selectedStory=Custom%20Lane%20Template&full=0&addons=0&stories=1&panelRight=0

Corresponding code here:
https://github.com/rcdexta/react-trello/blob/master/stories/CustomLaneStyling.story.js
