### ISSUE TITLE
Status of package ("is this repo abandoned?")

### ISSUE THREAD

**Issue by G-Rath** [rcdexta/react-trello#132]
There are a number of new issues having been created in the last month, along with two outstanding PRs, and a couple of requests for comment from me personally.

@rcdexta are you still actively maintaining this project/repo?

I'm happy & willing to contribute to this repo, to shore the package up. I've already got a list of a number of places in the api where I feel there are holes, that I'd be happy to fix myself, but without being a member of the repo, it falls to you to have to review the PRs, merge them, & release new versions.

**Comment by rcdexta** [comment]
Hi @G-Rath. Thanks for taking interest in this project. I had a work emergency for the past couple of weeks, so could not contribute to the repo. Will look at your PRs and merge them at the earliest.

I find that many find this library useful, so want to keep this project well maintained. I am happy to take all the help I can. Will add you as a collaborator to this project. 

Welcome to the team! :)
