### ISSUE TITLE
Text doesn't wrap when using customCardLayout

### ISSUE THREAD

**Issue by hkjasf687261gh** [rcdexta/react-trello#138]
Heya,

I've got a standard board set up using a customCardLayout. I've used the custom card layout example in the readme, and also tried a basic `<div>lots of text</div>` as the entire card layout, but the text never wrap. it always stays on 1 line.

The text wraps when you don't use a custom card layout, but when you do the text wont wrap.

thanks

![3a376d1c-d267-4efb-95e8-1cf287df1bfa](https://user-images.githubusercontent.com/29833930/48827362-2b8e0980-edc1-11e8-978f-281d6f9fb2c7.png)
![0a45b7e1-0ca8-4e24-9cc7-ea874a8ddd60](https://user-images.githubusercontent.com/29833930/48827363-2b8e0980-edc1-11e8-853d-1d481348c843.png)

**Comment by rcdexta** [comment]
When you opt for the custom card template, you take control of the styling for the card. But default, the card component has `white-space: normal;` set in the parent. Make sure you are not changing it or I would suggest applying that again to the card content.
