### ISSUE TITLE
canAddLanes doesn't default to false as readme claims

### ISSUE THREAD

**Issue by mandudeboy** [rcdexta/react-trello#139]
**Describe the bug**
According to the readme file the "canAddLanes" should default to "false" if not provided. It doesn't.

**To Reproduce**
1. Add a board using this syntax (NOT adding "canAddLanes")
`<Board
          data={toTrelloData(board)}
          style={{
            backgroundColor: '#276877',
            height: '700px',
            borderRadius: '0.5rem',
            boxShadow: '0px 0px 10px 0px #888888'
          }}
          draggable
          editable
          collapsibleLanes
          laneDraggable={false}
          cardDraggable
          hideCardDeleteIcon
        />`
2. view result
3. "Add another lane" button appears to the right of existing lanes and is usable.

**Expected behavior**
No "Add another lane" button should appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/1374672/48829879-a2041a80-ed73-11e8-9218-acd6506f51c0.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version: Version 70.0.3538.77 (Official Build) (64-bit)

**Comment by G-Rath** [comment]
@mandudeboy - that's interesting, as the default most definitely is `false` (line 229): 

https://github.com/rcdexta/react-trello/blob/6e752f49f8ac21c0fbd4b27a99ce4334393b6979/src/components/BoardContainer.js#L222-L239

I'll have a look tomorrow, and see if I can figure out why it's not working.

In the meantime, can you confirm the package version you've got installed?

**Comment by mandudeboy** [comment]
I have tried passing canAddLanes={false} and also canAddLanes="false" but it always shows the "add another lane" button

**Comment by mandudeboy** [comment]
"react-trello@2.0.1"

**Comment by mandudeboy** [comment]
Updated now, so now it says "version": "2.0.4" in package.json

**Comment by mandudeboy** [comment]
Seems like it's working now... I have no idea why... sorry if this caused any problems, I don't know if the upgrade fixed it or if something else did.
