### ISSUE TITLE
Any way to change the style of the columns and the board itsself?

### ISSUE THREAD

**Issue by jamesbaker1** [rcdexta/react-trello#14]
Is there anyway to change the background color/ the columns color and style? 

Great package by the way!

**Comment by rcdexta** [comment]
You can completely customize the look and feel of each card: 

http://localhost:9002/?selectedKind=react-trello&selectedStory=Custom%20Card%20styling&full=0&down=0&left=1&panelRight=0

https://github.com/rcdexta/react-trello/blob/master/stories/CustomCard.story.js

Let me know if that works for you...

**Comment by jamesbaker1** [comment]
I just ended up writing it all by myself!

**Comment by rcdexta** [comment]
cool..
