### ISSUE TITLE
Decouple Storybook, easily

### ISSUE THREAD

**Issue by Kalaschnik** [rcdexta/react-trello#140]
I’ve got already an existing react component which requires authentication and does a lot of other things, and I had a hard time trying to get `react-trello` into this project.
Ultimately I failed, for one, it was to to hard to put the entire `react-trello` structure in our big existing React (v15) project, the other reason was that I was not able to decouple Storybook from `react-trello`. In the end, I copied the structure from `react-trello-example` and into my existing project and added react-trello as a dependency in package.json. Is this actually the correct way?

However, it would be nice to work directly with the "official" `react-trello` project, and testing with Storybook. But at some point, when your’re done, to get rid of Storybook.

Thanks for all,
Kalaschnik

**Comment by rcdexta** [comment]
@Kalaschnik The release version of this library does not include the storybook. I am not sure I understand your question. To make it more clear for you to understand the usage, I have added a code sandbox example here: https://codesandbox.io/s/1o3zj95m9j

**Comment by Kalaschnik** [comment]
@rcdexta What do you mean by the release version of this library? `react-trello-example`? I actually have the same setup as you provided in the sandbox. So it is actually the intended way to use this project with `react-trello-example` and put `react-trello` as a dependency in `package.json`?
