### ISSUE TITLE
After implementing this plugin , existing UI design is breaking ? how to fix ? 

### ISSUE THREAD

**Issue by thisisrajkumar** [rcdexta/react-trello#148]
Before screen :

![before screen](https://user-images.githubusercontent.com/35949605/49133667-e1e47800-f306-11e8-989c-140896daf381.PNG)

After Screen : 

![after screen](https://user-images.githubusercontent.com/35949605/49133692-f0cb2a80-f306-11e8-968f-40317ed3fd91.PNG)

**Comment by rcdexta** [comment]
@thisisrajkumar react-trello does not inject any global styles. I have created a codesandbox example here:

https://codesandbox.io/s/1o3zj95m9j

Compare with your code and make sure you are normalizing your styles and not depending on the browser defaults for margin and padding. More [here](https://superyesmore.com/embed/article/9094165cd5a3f8ddb8ebad6df33b9b2f?u=1520433514)

**Comment by thisisrajkumar** [comment]
Thanks, I fixed that issue . This is routing level issue .  

`
function asyncComponent(getComponent) {
  class AsyncComponent extends Component {
    static Component = null;
    state = { Component: AsyncComponent.Component };

    componentWillMount() {
      if (!this.state.Component) {
        getComponent().then(Component => {
          AsyncComponent.Component = Component
          this.setState({ Component })
        })
      }
    }
    render() {
      const { Component } = this.state
      if (Component) {
        return <Component {...this.props} />
      }
      return null
    }
  }
  return AsyncComponent;
}
const LearningJourney = asyncComponent(() =>
  import('../LearningJourney').then(module => module.default)
)

        <Route exact path="/learning-journey" component={LearningJourney} />


`
