### ISSUE TITLE
I build custom add card using newCardTemplate method. How I can get card property and  laneId ? 

### ISSUE THREAD

**Issue by thisisrajkumar** [rcdexta/react-trello#149]
`   this.NewCard = (<div>
      <p>enter</p> <input type="text" /> <button onClick={this.InsertData} onCardAdd={this.handleCardAdd}>Submit</button>
    </div>)
`

 <Board editable={true}
                  onCardAdd={this.handleCardAdd}
                  onCardClick={this.clickCard}
                  data={this.props.learningjourney.data}
                  draggable
                  onDataChange={this.shouldReceiveNewData}
                  eventBusHandle={this.setEventBus}
                  handleDragStart={handleDragStart}
                  handleDragEnd={handleDragEnd}
                  addCardLink={<button disabled={this.state.btndisable}>Button</button>}
                  newCardTemplate={this.NewCard}
                />

**Comment by G-Rath** [comment]
`newCardTemplate` takes a React Node - this is a React component, meaning it gets passed props containing this information.

The quickest way to inspect the props is to pass `console.log` as the prop value, and then inspect the object in the Chrome console (note that this will result in the application crashing).

You can access the props with a function, or class component, per normal:

```
<Board
    newCardTemplate={props => (<button onClick={props.addCard}>Add Card</button>)}
/>
```

**Comment by G-Rath** [comment]
I have already told you how: You pass a *component*, instead of jsx.

In the simplest form:
```
this.NewCard = props => {
    /* now you have the laneId, and more in 'props' */
    return (
        <div>
                <p>enter your card name</p> 
                <input type="text" />
                <button onClick={() => this.InsertData(props.laneId)} >Submit</button>
        </div>
    )
}
```

Please re-read my previous answer. I recommend you read the [react page](https://reactjs.org/docs/components-and-props.html) on components & props.
