### ISSUE TITLE
Clicking an anchor in a custom card does not work

### ISSUE THREAD

**Issue by sylvain-hamel** [rcdexta/react-trello#150]
**Describe the bug**
My board uses `customCardLayout` and my card includes a `<a href="...">` tag. Clicking the hyperlink does not work.

**To Reproduce**

- Use this code

```
     const Card = ()=> <a href="www.github.com">test</a>;

     <Board 
         customCardLayout
         eventBusHandle={eventBusHandle} 
         handleDragEnd={handleDragEnd} 
         hideCardDeleteIcon 
         draggable 
         editable 
         laneDraggable={false} 
         data={myData} 
         addCardLink={<span/>}>

       <Card/>

     </Board>
```

- click on the link inside a card

**Expected behavior**

The click works and navigates away form the current page. Drag & drop should still work if I click and drag elsewhere in the card.

**Desktop :**
 - OS: Windown
 - Browser: Chrome
 - Version:  70

**Comment by sylvain-hamel** [comment]
The root cause is the call to `e.preventDefault()` here in `Lane.js`

```
  handleCardClick = (e, card) => {
    const {onCardClick} = this.props
    onCardClick && onCardClick(card.id, card.metadata, card.laneId)
    e.stopPropagation()
    e.preventDefault()
  }
```
What made you add that line? In other words, what wouldn't work if this line was not there?

**Comment by rcdexta** [comment]
Fixed in the latest release. Thanks for reporting. The bug was introduced as a side-effect of using another library for DnD. Should work now.
