### ISSUE TITLE
isDraggingOver is not set to False on cardDrop

### ISSUE THREAD

**Issue by mandudeboy** [rcdexta/react-trello#155]
**Describe the bug**
When draggable is set to true and you drag a card from lane A to lane B the lane B is extended 100px down during the drag event, but it doesn't get reduced 100px when you drop the card there.

In the code the lanes "isDraggingOver" prop is set to true on "onDragEnter" and to false on "onDragLeave" but since we drop the card in the lane, the "onDragLeave" event is never triggered and the extra 100px lane height sticks around.

I guess a fix would be to set "isDraggingOver" to false also on "onDrop" event?

**Screenshots**
![image](https://user-images.githubusercontent.com/1374672/49804811-ddcb4800-fd53-11e8-8c28-218c795a95e9.png)

**Comment by rcdexta** [comment]
This should be fixed 2.1.0

![screen-recording-2019-02-23-at-6 23 06-pm](https://user-images.githubusercontent.com/900028/53294266-57da6d00-3798-11e9-98d1-ce832ff04702.gif)
