### ISSUE TITLE
customLaneHeader does not work if also using customCardLayout

### ISSUE THREAD

**Issue by sylvain-hamel** [rcdexta/react-trello#156]
**Describe the bug**
Adding a `customLaneHeader` to a board that already uses `customCardLayout` does not work: the header is broken.

**To Reproduce**
Use both features at the same time

**Expected behavior**
The cards use the card layout and the lane header uses the lane header template.

**Actual behavior**
The cards do use the card layout and that's fine. But the lane header is rendered using the card layout too!!

**Comment by rorycor** [comment]
It is working fine for myself 
![image](https://user-images.githubusercontent.com/42002101/50511308-0ad26700-0a85-11e9-884d-decee71da62b.png)
![image](https://user-images.githubusercontent.com/42002101/50511317-1f166400-0a85-11e9-9380-d9ac63dd1bbf.png)

**Comment by sylvain-hamel** [comment]
I'm no longer able to reproduce.

**Comment by akshayDatacode** [comment]
I tried as @rorycor you mention above, but I am facing the same issue, 
There is nothing updation on borad design as custom header of a lane
