### ISSUE TITLE
Can't reorder lists in "Editable Board" example

### ISSUE THREAD

**Issue by harrysolovay** [rcdexta/react-trello#158]
**Describe the bug**
I'm unable to reorder the lists

**To Reproduce**
1. clone
2. 'yarn && yarn storybook'
3. try Editable Board demo

**Comment by rcdexta** [comment]
Unless you pass the `draggable` prop as true to the `Board` component, the lanes and card cannot be dragged. This example has both editable and draggable implemented:

http://rcdexta.com/react-trello/?selectedKind=Editable%20Board&selectedStory=Add%2FDelete%20Cards&full=0&addons=0&stories=1&panelRight=0

**Comment by harrysolovay** [comment]
@rcdexta it's broken––it's letting me drag, just not persisting the position upon release. Pretty sure that's not the intended behavior. Please let me know if you need more details (or maybe a screen recording?) :)

**Comment by rcdexta** [comment]
Oh yes you are right @harrysolovay :o  The lanes do wiggle back to their original position. I will fix it and let you know. Thanks

**Comment by rcdexta** [comment]
v2.0.7 should address this one.

**Comment by harrysolovay** [comment]
@rcdexta thank you!
