### ISSUE TITLE
how to restrict the drag and drop from one list to another ?

### ISSUE THREAD

**Issue by thisisrajkumar** [rcdexta/react-trello#159]
Hi, Drag and Drop issue, Currently, we have an option to Drag a card from one list and drop it into another list, but I want to know the how to restrict the drag and drop from one list to another.

**Comment by rcdexta** [comment]
In the data passed to the `Board` component, the lane objects have an attribute called `draggable`. It is true by default and set it to false to restrict drag-and-drops to specific lanes. 

Example here: https://rcdexta.com/react-trello/?selectedKind=Drag-n-Drop&selectedStory=Restrict%20lanes&full=0&addons=0&stories=1&panelRight=0
