### ISSUE TITLE
Unable to resolve path to module 

### ISSUE THREAD

**Issue by iwoork** [rcdexta/react-trello#16]
When running ESLint, the module throws an error:

 Unable to resolve path to module 'react-trello'  import/no-unresolved

**Comment by rcdexta** [comment]
Can you post your eslint config. Also this could be an issue: https://github.com/benmosher/eslint-plugin-import/issues/720

**Comment by rcdexta** [comment]
Closing issue for now. Please revert back with more details if problem persists
