### ISSUE TITLE
cancel the card drag

### ISSUE THREAD

**Issue by abdulkhaliquem9** [rcdexta/react-trello#160]
**I want to revert the card drag  if some condition fails**
As per my project requirement, I need to update the card data in the server whenever it is dragged. I want to cancelCardDrag() method if response is false or in case of any network failure.

**Describe the solution you'd like**
As the react-trello is maintaining its own redux internally, I am unable to revert the changes, Even if restore the state of my redux.
`
  handleDragEnd = async (cardId, sourceLaneId, targetLaneId, position, cardDetails) => {
        console.log('CARD DRAG END: > laneId: ',cardId, sourceLaneId, targetLaneId, position, cardDetails)
        // handleDragEnd(cardId, sourceLaneId, targetLaneId, position, cardDetails, this, this.props.savePatientData, this.props.trelloReducer.boardData)
        await this.props.setLoadingBoard(true)
        ajaxcall.then(res =>{
            if(res.data){
                await handleDragEnd(cardId, sourceLaneId, targetLaneId, position, cardDetails, )
                await this.props.setLoadingBoard(false)
            }
        }).catch(e=>{
            await handleDragEnd(cardId, sourceLaneId, sourceLaneId, position, cardDetails, )
            await this.props.setLoadingBoard(false)
        })
    }`
 I am making the source & target lane Ids to be same if the res.data is false, But it react-trello internally moves the card to the target in the internal redux.

**Comment by abdulkhaliquem9** [comment]
I fixed it, I am not calling the handleDragEnd() if server response is false

**Comment by abdulkhaliquem9** [comment]
I still have some problem with the approach which I am following. 
If I don't call the handleDragEnd() if the server response fails, the card is not getting back to the previous lane, But to correct my screen I have to fetch the data from the server to re-render the screen.
I feel, it will be good to have a cancelLastMove() function, or else give me some suggestion to correct my flow in the current scenario.

**Comment by dapi** [comment]
if network is failure it’s enough to show alert to user and recommend him to reload the page. It’s a critical situation we does not know is the card really moved or not on the server. Trello work the same way
