### ISSUE TITLE
Add EnableVertical={bool} and verticalScroll style={object} props

### ISSUE THREAD

**Issue by abdulkhaliquem9** [rcdexta/react-trello#161]
**I want to enable vertical scroll bar with fixed Header, with cutomized styles for the vertical scroll**
Please add props to enable/disable verticalScrollBar & VerticalScrollStyles to change the color of scrollbar.

**Comment by dapi** [comment]
@abdulkhaliquem9 hi! You could use component dependency mechanism (`components` props) to override Lane component to have requested behaviour
