### ISSUE TITLE
Adding new cards (editable) when using custom card component

### ISSUE THREAD

**Issue by harrysolovay** [rcdexta/react-trello#162]
**Describe the bug**
With an editable board, there's conflict when attempting to use a custom card. Adding a new card, it shows the fixed (default) card. There's no way to override this and make use of your own "editable" card.

**Comment by rorycor** [comment]
The 'editable board' story has the code you are looking for, you need to declare a new card template and pass it to the board 
![image](https://user-images.githubusercontent.com/42002101/50518879-04a5b000-0ab0-11e9-8c55-204908268d53.png)

**Comment by harrysolovay** [comment]
Oooooo——I missed that in the docs. Thank you @rorycor!!!!!
