### ISSUE TITLE
Deleting newly-created lanes

### ISSUE THREAD

**Issue by harrysolovay** [rcdexta/react-trello#163]
**Is your feature request related to a problem? Please describe.**
I'm unable to delete lanes created in 'editable' mode

**Describe the solution you'd like**
A remove function passed via props to customLaneHeader

**Describe alternatives you've considered**
Interacting directly with the underlaying Redux... I end up breaking things though :(

**Additional context**
Nope

**Comment by harrysolovay** [comment]
Hi, just wanted to reach out again and see if anyone knew how to achieve this? I'm really in need of this feature. Thank you!

Kind regards,

Harry

**Comment by harrysolovay** [comment]
@rcdexta I'm sorry to bother you, but I really, really need the ability to delete. It would mean a crazy amount to me.

**Comment by harrysolovay** [comment]
@rcdexta please implement this––it seems like a must-have for this type of component

**Comment by G-Rath** [comment]
@harrysolovay Hi, sorry I've only just seen this issue.

I've had this functionality in my application since I started using it - you can "delete" lanes by removing them from the `data` object you're passing to the prop.

You can use a custom lane header to add a button directly on the lane itself.

Let me know if you need more help with this, and I can dig up some examples.

**Comment by rcdexta** [comment]
@harrysolovay Sorry I got really busy and could not work on this till now. what @G-Rath is suggesting could be work but the I think what you are asking for is to perform this action from the UI.

So after creating a lane, it should be possible to delete the lane again. Will push this tomorrow my time (PST)

**Comment by harrysolovay** [comment]
Thank you @rcdexta –– I really appreciate your work on this!

**Comment by rcdexta** [comment]
Feature implemented in latest release. Lanes can be deleted only when `canAddLanes` and `editable` props set to true

![feb-10-2019 23-31-14](https://user-images.githubusercontent.com/900028/52550246-1efbca80-2d8c-11e9-94b4-666bd11bef82.gif)

**Comment by harrysolovay** [comment]
B E A U T I F U L –– thank you @rcdexta !!!!!!!!!!!!!!!!!!!!!
