### ISSUE TITLE
Build fails after upgrading to v2

### ISSUE THREAD

**Issue by fabioDMFerreira** [rcdexta/react-trello#167]
**Describe the bug**

After upgrading react trello from version 1 to version 2 I started to get the next error on building my application (bootstrapped by create-react-app).
```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/react-trello/dist/styles/Base.js:12

Read more here: http://bit.ly/2tRViJ9
```

Comment uglify plugin in webpack configuration script fixes the problem, but I want to keep the bundle as small as possible. It may be related with modern javascript features that were introduced in this new react-trello version as create-react-app documentation suggests.
https://facebook.github.io/create-react-app/docs/troubleshooting#npm-run-build-fails-to-minify

Also tried other solutions:
https://github.com/ccxt/ccxt/issues/299
https://github.com/mishoo/UglifyJS2/issues/2011

The problem seems solved in the new create-react-app version. It uses webpack 4 and uglify was deprecated.

**To Reproduce**
1. Download repository from next origin:
https://github.com/fabioDMFerreira/react-trello-webpack-3
2. Run `npm run build`

**Expected behavior**
Build bundle without problems.

**Comment by rcdexta** [comment]
should be fixed in v2.0.9
