### ISSUE TITLE
Dead link in readme

### ISSUE THREAD

**Issue by ajRiverav** [rcdexta/react-trello#172]
**Describe the bug**
Dead link in README.md 
Line is : "Learn how to write stories here", where here is href pointing to dead link.
Error is : getstorybook.io’s server IP address could not be found.

**To Reproduce**
1. Click on here. 

**Expected behavior**
Non-dead link.

**Comment by Kalaschnik** [comment]
New Domain:
https://storybook.js.org/basics/writing-stories/

**Comment by rcdexta** [comment]
Fixed. Thanks
