### ISSUE TITLE
Customize newLane button description

### ISSUE THREAD

**Issue by tatosjb** [rcdexta/react-trello#175]
**Is your feature request related to a problem? Please describe.**
I'm from Brazil and my users expect to se all software in portuguese, so the buttons description *Add* and *Cancel* force me to write another component just for change buttons description.

**Describe the solution you'd like**
I like to pass the description by props and it be rendered on the default new lane layout .

**Describe alternatives you've considered**
Add props to the Board component. I think its no so complicated.

**Additional context**
If its approved, i could do it @rcdexta

**Comment by Kalaschnik** [comment]
You can customize the label with `addLaneTitle` and `addCardTitle`. As of #173 (version 2.0.9) the feature of giving a custom Lane button title is broken.

```
<Board
  data={data}
  editable
  canAddLanes
  addLaneTitle="Add Column"
  addCardTitle="Add Item"
      />
```

**Comment by tatosjb** [comment]
@Kalaschnik, mey i see a missunderstending here. I'm talking about this component.

https://github.com/rcdexta/react-trello/blob/master/src/components/NewCard.js

It has two button one calle "Add" other called "Calcel" and those are not customizable.

**Comment by Kalaschnik** [comment]
I’m sorry. Now I get it. You’re right, they are hard-coded...

**Comment by rcdexta** [comment]
@tatosjb pls submit a PR for localizing both the button descriptions. thanks

**Comment by sylvain-hamel** [comment]
You can replace the new lane form altogether using `newLaneTemplate`, which is pretty easy. All you have to do is call `props.onAdd(laneInfo)` in your "OK" button click handler.

**Comment by schevall** [comment]
@sylvain-hamel have the right solution, it is just needed to add it to the docs

**Comment by dapi** [comment]
better way to use i18n - https://github.com/rcdexta/react-trello/issues/237

**Comment by dapi** [comment]
Use i18n support - https://github.com/rcdexta/react-trello#i18n
