### ISSUE TITLE
Set cards to be not draggable on specify lane

### ISSUE THREAD

**Issue by ioterateam** [rcdexta/react-trello#176]
**Is your feature request related to a problem? Please describe.**
The problem is related to fix bug task. The lanes is Bug, Website, Server, and Solved.

**Describe the solution you'd like**
I want solution for making cards inside lane **_solved_** shouldn't be able to drag

Current solution I use is set **bug**, **website** and **server** lanes 

> droppable=false

So all cards is draggable but only droppable on solved lane. But it's really bad behavior, since cards inside solved lane still draggable.

Can you help me with this problem? Because I already read all your options on board, lanes and card, but none provide to solve my problem.

![image](https://user-images.githubusercontent.com/29442149/51156816-e0b7dc00-18af-11e9-81af-b607cba6d63d.png)

**Comment by rcdexta** [comment]
@ioterateam Each card has a prop called `cardDraggable` passed as part of the incoming data prop. Setting it to false for all the cards in a lane and setting `droppable` to false for the lane will effectively freeze the lane which is your requirement I believe.

**Comment by oisti** [comment]
It's not working in the latest version.

[codesandbox.io](https://codesandbox.io/s/jyxqr40y9)

**Comment by code-bot-dev** [comment]
Hi rcdexta, I was trying to implement the same thing but its working using the latest version. I want to apply cardDraggable/droppable prop at card level and not on lane level so that in the same lane some cards are dragabble and some not. How can we achieve that?

**Comment by luizasilval** [comment]
i need to be able to put cards on a lane but not move them anymore, so i need to drag cards on a lane and not drag them. 
I'm trying to use the **draggable false** (documentarion says that it is the default) but it still let me move the card on the lane.
