### ISSUE TITLE
Get the title from a lane, not the id

### ISSUE THREAD

**Issue by Kalaschnik** [rcdexta/react-trello#178]
I’m using handleDragEnd to call a function which update some things. Is there a convenient way to get the `targetLaneTitle` from the `targetLaneId`, or the lane title in generel from a given lane id?

for example in `handleDragEnd`
```
const handleDragEnd = (cardId, targetLaneTitle) => {
    updateItem(cardId, targetLaneTitle);
};
```

Since there is no `targetLaneTitle` it would be really neat if the Board would provide such a method, or to get something similar such as`getLaneTitle(laneId)`

**Comment by dapi** [comment]
Try to get title with `this.state.title`

**Comment by Kalaschnik** [comment]
Well the title is not in the state. handleDragEnd is defined like this:

handleDragEnd | function | Callback function triggered when card drag ends, return false if you want to cancel drop: handleDragEnd(cardId, sourceLaneId, targetLaneId, position, cardDetails)
-- | -- | --

Yet, my cards have a unique id, but I want to get to know the title. It is not supported in this function. I already solved it actually myself; I created a lookup in the state, kinda like {id: title}. However, it would be neat if there would be native implementation. But I’m also fine with my solution. So keep this closed :)

**Comment by dapi** [comment]
`this.props.title` ? )

**Comment by dapi** [comment]
@Kalaschnik ping

**Comment by Kalaschnik** [comment]
Feel free to close it; in short I created my own lookup table which I’ll use to lookup titles based on the given id.

**Comment by dapi** [comment]
ok
