### ISSUE TITLE
dependency not installable with yarn without git

### ISSUE THREAD

**Issue by leoschweizer** [rcdexta/react-trello#179]
Currently, react-trello can't be installed through yarn if git is not available (which could easily happen in a CI environment or when running your dev environment in a docker container). The reason is probably the https dependency on the fork of smooth-dnd here: https://github.com/rcdexta/react-trello/blob/master/package.json#L49

Which leads to
```
# yarn add -D -E react-trello@2.0.9
yarn add v1.10.1
[1/4] Resolving packages...
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

I'm not sure if this was intentional?

**Comment by vale2628** [comment]
Any update on this?

**Comment by jesterstar** [comment]
I have the same problem. @dapi will you do smth with that?
I want to use your library, but this bug. A lot of people used yarn with docker. I guess it should be changed.

**Comment by jesterstar** [comment]
Add this line in your Docker file 
`RUN apk add --no-cache git`
before your `yarn` commands

**Comment by dapi** [comment]
Mentioned package is replaced

**Comment by kojuka** [comment]
as of 2.2.3 I'm still having this issue.   @jesterstar 's suggestion worked, but seems like overkill to require git in CI environments.
