### ISSUE TITLE
Missing canAddLanes feature since v2.0.9

### ISSUE THREAD

**Issue by Termit1975** [rcdexta/react-trello#180]
**Describe the bug**
canAddLanes no longer works because of https://github.com/rcdexta/react-trello/commit/dabd983a2db85479f7246fe7a878250621fbd4a0#diff-ec6ba09dae0e5a38d6c4be664c98b7bd. I guess it was accidentally dropped.

**Comment by Kalaschnik** [comment]
See #173 .

**Comment by Termit1975** [comment]
Thanks
