### ISSUE TITLE
Hide add card button

### ISSUE THREAD

**Issue by oflarcade** [rcdexta/react-trello#183]
It will be awesome if we can hide the add card button on specific lanes... And cancel the drop event if not the wanted lane id

Ie saye you have 4 lanes and the first lane is the start of all lanes. You can only add cards on the first lane, and move it to the one next to it and so on.

**Comment by sylvain-hamel** [comment]
workaround: 

```
<Board addCardLink={<span/>}/>
```

**Comment by dapi** [comment]
Could we close the issue?

**Comment by dapi** [comment]
Use `lane.disallowAddingCard` - https://github.com/rcdexta/react-trello/pull/287/files#diff-e2b1352494cba6252bc14efc8ccc5ac0R178

**Comment by dapi** [comment]
@oflarcade !

**Comment by dapi** [comment]
@oflarcade feel free to reopen if something wrong
