### ISSUE TITLE
Lane cannot be styled via className anymore

### ISSUE THREAD

**Issue by Termit1975** [rcdexta/react-trello#186]
**Describe the bug**
Before https://github.com/rcdexta/react-trello/commit/e07e4a6c9441150d71c821a331c61da9d76a7b08, I was able to give a className and the <section> node had the specified className. Since there is the new attribute ``className="react-trello-lane"`` this overrides what comes from current className property it was done via ...otherProps

**To Reproduce**
1. Add a className to the data of the lanes
2. Class name is not added to <section> dom node

**Expected behavior**
The section object should include the className from otherProps as well as "react-trello-lane"

**Comment by rcdexta** [comment]
Should be addressed in rather release
