### ISSUE TITLE
Open the wiki

### ISSUE THREAD

**Issue by Kalaschnik** [rcdexta/react-trello#187]
# Open the wiki
Since there are a bunch of active people here around, I think it would be great if we all could share some how-to, ideas, best practices of doing things in a wiki...  What do you think?

**Comment by rcdexta** [comment]
You are most welcome to add such guides to the wiki here: https://github.com/rcdexta/react-trello/wiki

**Comment by Kalaschnik** [comment]
Thanks. However, I cannot edit it. Can you check these settings:

https://help.github.com/articles/changing-access-permissions-for-wikis/

**Comment by rcdexta** [comment]
The wiki should be editable now @Kalaschnik
