### ISSUE TITLE
How to open a Dialog/Modal view for onCardClick

### ISSUE THREAD

**Issue by Kalaschnik** [rcdexta/react-trello#188]
I know that `onCardClick` is expecting a function, so I, naïvely, did the following:

```
// React class render method:
render() {
  const cardClicked = (cardId, metadata, laneId) => {
    // this works:
    console.log(cardId, metadata, laneId);
    // this not:
    return (
      <SomeModalViewComponent>
        <h1>Content</h1>
      </SomeModalViewComponent>
    );
  };

  return (
  <Board onCardClick={cardClicked} />
}
```
It’s probably because of my still limited React understanding, but maybe someone already tried something similar (btw. good to have a wiki #187 for some usage examples)

Thanks for any help on that!

**Comment by oflarcade** [comment]
check the docs you will find onCardClick function in the props table you can use to trigger a setState of modal open/close state;  

onCardClick | function | Called when a card is clicked: onCardClick(cardId, metadata, laneId)
-- | -- | --

**Comment by oflarcade** [comment]
you can do it like so: 

```
class foo extends React.Component{
state={isOpen: false}

onCardClick = (cardId, metadata, laneId) => {
this.setState((prevState) => {
     return {isOpen: !prevState.isOpen}
});
}
  render() {
     const {isOpen} = this.state;
      return(
        <Board>
          <Modal open={isOpen} />
       </Board>
        );
     }
}

```

**Comment by rcdexta** [comment]
@oflarcade's suggestion should work...
