### ISSUE TITLE
Build fails on 2.0.9

### ISSUE THREAD

**Issue by Mangid** [rcdexta/react-trello#189]
**Describe the bug**
I have installed react-trelle in the current version. During the build process I get the following message:

> react-scripts build

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/react-trello/dist/styles/Base.js:257 

Read more here: http://bit.ly/2tRViJ9

**To Reproduce**
1. Installed react-trello
2. run "npm run build"

**Expected behavior**
Build bundle without problems.

**Comment by Mangid** [comment]
I missed the package "terser": "3.14.1"! Sorry

**Comment by srivastavaharsh9888** [comment]
Having the same problem can you elaborate that how you resolved this issue..

**Comment by dintrans** [comment]
I'm still having problems with webpack3, uglify3 and react-trello2, so at the moment i went back to 1.33.0

**Comment by rcdexta** [comment]
>Failed to minify the code from this file: 

This error should be fixed in the latest build!
