### ISSUE TITLE
Build getting failed in v2.0.10

### ISSUE THREAD

**Issue by srivastavaharsh9888** [rcdexta/react-trello#193]
**Describe the bug**
I have installed react-trelle in the current version. During the build process I get the following message:
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 
 	./node_modules/react-trello/dist/styles/Base.js:12 

**To Reproduce**
1. Install react-trello 
2. npm run build

**Expected behavior**
Build file is produced.

**Screenshots**
![image](https://user-images.githubusercontent.com/22855779/52293072-01012500-299c-11e9-85ba-22844bc9f2db.png)

**Additional context**

**Comment by MrShubhamSingh** [comment]
I think your issue can be resolved with this 

https://github.com/rogeriochaves/npm-force-resolutions

**Comment by rcdexta** [comment]
I think the version of javascript runtime does not support template literals. I have anyway used a babel transform to make the build agnostic of this runtime support.

Please pull latest build
