### ISSUE TITLE
Increase card droppable area for lane?

### ISSUE THREAD

**Issue by JavaJamie** [rcdexta/react-trello#194]
Is there a way to expand the area where the card can be dropped inside a lane?

We have some pretty long (height) cards and when a lane has no cards inside it we can't drop the card inside it as the droppable area is far too small. We'd like to ideally make the droppable area the full height of the board.

Thanks.

**Comment by JavaJamie** [comment]
Have resolved this by giving the lane a min-height.

**Comment by chrisfoster22** [comment]
This solution didn't work for me - I actually had to give `.smooth-dnd-container` a min-height.
