### ISSUE TITLE
HTML React Title Attribute Prop

### ISSUE THREAD

**Issue by aliogaili** [rcdexta/react-trello#195]
**Describe the bug**
If  an HTML element is passed to the card title prop, then [object object] will be rendered in the title attribute.

<img width="269" alt="screen shot 2019-02-16 at 12 07 47 am" src="https://user-images.githubusercontent.com/1675307/52881826-30bfe200-317f-11e9-9cf5-fe5502a042b6.png">

**To Reproduce**
1. Pass something like  

>  title: (
>         <div
>           {noteDoc.title}
>         </div>
>       ),
> 

To the title prop then hover on the card body to see the [object object] tooltip displayed

**Expected behavior**
Either render the actual title html string or provide away to override/disable it.

This is on version:  2.0.9

**Comment by dapi** [comment]
I think it will be fixed in this milestone https://github.com/rcdexta/react-trello/milestone/5

**Comment by dapi** [comment]
@aliogaili is it OK now?

**Comment by aliogaili** [comment]
I'll give it a try today and let you know @dapi

**Comment by aliogaili** [comment]
I've updated to 2.2.0 and the [object object] title is still there. 

Here is the generated html
<img width="785" alt="Screen Shot 2019-07-24 at 2 01 05 PM" src="https://user-images.githubusercontent.com/1675307/61772257-03f1b400-ae1c-11e9-9cc4-05b4858805a3.png">

I've also noticed that the card now has [x] on the title that only shows on hover. Is it possible to remove that, I don't think we had that in  2.1.4 (the version I was on), I've adding my own X on the title.

**Comment by dapi** [comment]
1. To hide `delete card icon` use property `hideCardDeleteIcon`
2. I think in such cases better to use dependency injection and create you own card component. Here is example - https://github.com/rcdexta/react-trello/blob/master/stories/CustomCard.story.js#L8

**Comment by aliogaili** [comment]
Yeah I agree with that, but wanted to point out this issue. 

Should we close this then?

**Comment by dapi** [comment]
Yeah, closing..
