### ISSUE TITLE
styled-components should not be bundled with react-trello

### ISSUE THREAD

**Issue by leoschweizer** [rcdexta/react-trello#199]
Currently, react-trello declares styled-components as dependency: https://github.com/rcdexta/react-trello/blob/master/package.json#L52

According to the official docs, this is not recommended: https://www.styled-components.com/docs/faqs#i-am-a-library-author-should-i-bundle-styledcomponents-with-my-library

When using react-trello in an application which itself uses styled-components, this inevitably leads to the problem:
```
It looks like there are several instances of 'styled-components' initialized in this application. 
This may cause dynamic styles not rendering properly, errors happening during rehydration 
process and makes your application bigger without a good reason.

See https://s-c.sh/2BAXzed for more info.
```

Please consider implementing this as recommended by styled-components.

**Comment by Kalaschnik** [comment]
Another thing is that styled-components have react peerDependency "react": ">= 16.3.0". My company runs on react 15.x, unfortunately. Therefore, I cannot update react-trello anymore*

*Details
`react-trello 2.0.7` requires `styled-components 3.4.10` which have react `peerDependency: "react": ">= 0.14.0 < 17.0.0-0"`, However, `react-trello >= 2.0.8` requires `styled-components >= 4.0.3` which have react peerDependency `"react": ">= 16.3.0"`, which is bad for people running React on older projects prior <16.3.

**Comment by rcdexta** [comment]
Yes it's not right to have styled-components as a direct dependency. Moved it a peer dependency in v2.1.3
