### ISSUE TITLE
Can't resolve components/Board

### ISSUE THREAD

**Issue by chrislewispac** [rcdexta/react-trello#20]
./node_modules/react-trello/dist/index.js
Module not found: Can't resolve './components/Board' in '/Users/chrislewis/Projects/statrecruit-react/node_modules/react-trello/dist'

**Comment by rcdexta** [comment]
There was a glitch in the build script that packaged the most recent version of the library. Thanks for letting know. Please pull version `1.20.2` and you should be good!
