### ISSUE TITLE
Wrong classnames with latest update

### ISSUE THREAD

**Issue by PaulCombal** [rcdexta/react-trello#200]
Looks like you copy-pasted too fast in your latest update:

[This line](https://github.com/rcdexta/react-trello/commit/f56a73c45ffb35db4898ad70756388ba9f25e2dc#diff-d99b8305e62aa26a276f475d589ace28R44) should be 
` const allClassNames = classNames('react-trello-**card**', this.props.className || '')`

And [this line](https://github.com/rcdexta/react-trello/commit/f56a73c45ffb35db4898ad70756388ba9f25e2dc#diff-75e9fc3130d0169490ea0466c5976ff9R267) should be:
`const allClassNames = classNames('react-trello-**lane**', this.props.className || '')`

Am I right?

**Comment by dapi** [comment]
@PaulCombal hi!

There was a big rewriting. Is the problem still exists?

**Comment by dapi** [comment]
It’s fixed long time ago.
