### ISSUE TITLE
Warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use PropTypes.checkPropTypes() to call them.

### ISSUE THREAD

**Issue by geocine** [rcdexta/react-trello#201]
**Describe the bug**
This is not a bug but shows this warning.

**To Reproduce**
1. Go to https://codesandbox.io/s/k93yo8mj77
2. Open Dev Console
4. See warning

**Expected behavior**
Should not show warning

**Screenshots**
```
Warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use PropTypes.checkPropTypes() to call them. Read more at http://fb.me/use-check-prop-types
    in PopoverWrapper (created by BoardContainer)
    in BoardContainer (created by Connect(BoardContainer))
    in Connect(BoardContainer) (created by Board)
    in Provider (created by Board)
    in Board (created by App)
    in App
```

**Desktop (please complete the following information):**
 - OS: mac
 - Browser: Chrome
 - Version: 72

**Comment by geocine** [comment]
I believe it is coming from this dependency https://github.com/terebentina/react-popover/issues/16

**Comment by dapi** [comment]
I think we will remove react-popover in the near feature

**Comment by rmaroun** [comment]
> I think we will remove react-popover in the near feature

hi @dapi will this be solved in next release? When is 2.2.0 planned to be released? thanks.

**Comment by dapi** [comment]
hi @rmaroun! Yes it will be fixed in next release. I plan to realise it this summer.

Now we need more feedback from users of current version (`2.2.0-alpha.1`) to continue development

**Comment by dapi** [comment]
@rmaroun hi!

Right now have replaced `react-popover` with `react-popopo`.

Could you try master branch of `react-trello`?
