### ISSUE TITLE
handleLaneDragEnd bugged parameter

### ISSUE THREAD

**Issue by AlexSicoe** [rcdexta/react-trello#205]
**Describe the bug**
In handleLaneDragEnd, parameter _laneId_ is not actually the lane's id but the old position

**To Reproduce**
This is obvious if you name your lanes with strings 'lane1', 'lane2' and in the handler console.log each parameter. The log of _laneId_ currently displays numbers, which I think are corresponding to the old position.

**Possible fix**
Rename the current _laneId_ to _oldPosition_
(turns out i can get the correct laneId from the payload)

**Comment by dapi** [comment]
@AlexSicoe I have updated docs. Could we close the issue?
