### ISSUE TITLE
Add support for custom footer.

### ISSUE THREAD

**Issue by hiren-ghodasara** [rcdexta/react-trello#209]
Want to add custome footer beacuse of need one button into the footer section.

I need to add Load more cards group by lane, when we click on that button it will make one ajax call and appeds other cards into the list.

**Comment by dapi** [comment]
@hiren-ghodasara  hi!

I have just  done Dependency Injection mechanism. Could you please test it and give me a feedback?

https://github.com/rcdexta/react-trello/pull/274

```
yarn add BrandyMint/react-trello#components_dependency_injections
```

If it is Ok, I will merge it to master.

**Comment by dapi** [comment]
Merged in master.

Now you can override LaneFooter with dependency injection mechanism:

https://github.com/rcdexta/react-trello#3-completely-customize-the-look-and-feel-by-using-components-dependency-injection
https://github.com/rcdexta/react-trello/blob/master/src/components/index.js

Fell free to open the issues if there are needs
