### ISSUE TITLE
Customize Lanes?

### ISSUE THREAD

**Issue by sluongng** [rcdexta/react-trello#21]
Is there a way I can customize the lanes similar to customizing Cards?
For instance the width, max height of the lanes, heading etc...
May be having 2 lanes on top of each other?

**Comment by rcdexta** [comment]
It's possible to customize the style for lane and as well as lane title.

Have added sample code to illustrate my point in this storybook:
https://rcdexta.github.io/react-trello/?selectedKind=React%20Trello&selectedStory=Card%20and%20Lane%20Styling&full=0&down=0&left=1&panelRight=0

Code here: https://github.com/rcdexta/react-trello/blob/master/stories/CustomCardAndLaneStyling.story.js

Pls pull the latest version as the change to customize lane title was added recently!

**Comment by code-bot-dev** [comment]
Hi I want to customize lane header but the solution link is not working, also in the documentation I can see 'customLaneHeader' prop which takes a element but what if I want to use an array to create header element for each lane and also add buttons/icons beside the text just like card. How can we achieve that?
