### ISSUE TITLE
Returning false in handleDragEnd doesn't cancel the drop

### ISSUE THREAD

**Issue by dantonel** [rcdexta/react-trello#212]
**Describe the bug**
Returning false in handleDragEnd does not cancel the drop.

**To Reproduce**
1. Set handleDragEnd={ () => false }
2. Try dragging any card to a different position/lane

**Expected behavior**
All drags should be cancelled, as per the documentation: Callback function triggered when card drag ends, return false if you want to cancel drop: handleDragEnd(cardId, sourceLaneId, targetLaneId, position, cardDetails)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 74.0.3729.131 (Official Build) (64-bit)

**Comment by andrei10k** [comment]
it should be fixed but the latest version is not published to npm. in the lane.js on the repository i can see the following code: 

`onDragEnd = (laneId, result) => {
    const {handleDragEnd} = this.props
    const {addedIndex, payload} = result
    this.setState({isDraggingOver: false})
    if (addedIndex != null) {
      const newCard = {...cloneDeep(payload), laneId}
      const response = handleDragEnd ? handleDragEnd(payload.id, payload.laneId, laneId, addedIndex, newCard) : true
      if (response === undefined || !!response) {
        this.props.actions.moveCardAcrossLanes({
          fromLaneId: payload.laneId,
          toLaneId: laneId,
          cardId: payload.id,
          index: addedIndex
        })
      }
      return response
    }
  }`

while on my node_modules i have:

`onDragEnd = (laneId, result) => {
    const {handleDragEnd} = this.props
    const {addedIndex, payload} = result
    this.setState({isDraggingOver: false})
    if (addedIndex != null) {
      this.props.actions.moveCardAcrossLanes({
        fromLaneId: payload.laneId,
        toLaneId: laneId,
        cardId: payload.id,
        index: addedIndex
      })
      handleDragEnd && handleDragEnd(payload.id, payload.laneId, laneId, addedIndex, payload)
    }
  }`

@rcdexta can you please publish the latest version, we kind of really need this fix

**Comment by rcdexta** [comment]
Changes should be available in v2.1.4 released 15 mins ago

**Comment by dantonel** [comment]
Seems to be working now. Thanks!
