### ISSUE TITLE
Cannot overwrite minWidth from ScrollableLane

### ISSUE THREAD

**Issue by chargome** [rcdexta/react-trello#216]
Hi, 

I tried to update the width of the lane and the card by modifying the data.json. However I could not come up with a way to overwrite the min-width: 250px from ScrollableLane.

<img width="1200" alt="Screenshot 2019-05-18 at 14 59 52" src="https://user-images.githubusercontent.com/20254395/57970106-a48ba980-797d-11e9-8f71-751689ff9194.png">

**Comment by dapi** [comment]
@chargome try to use dependency injection mechanism (property `components`) to override Lane component and to have you custom styles (with modified `min-width`)

**Comment by johhansantana** [comment]
> @chargome try to use dependency injection mechanism (property `components`) to override Lane component and to have you custom styles (with modified `min-width`)

how do you do this? why isn't there an easier way like passing props?

**Comment by johhansantana** [comment]
was able to "fix" by doing this in a css file:

```css
.react-trello-lane div:nth-child(2) {
  min-width: auto;
}
```
