### ISSUE TITLE
Got error when using custom card

### ISSUE THREAD

**Issue by sluongng** [rcdexta/react-trello#22]
![image](https://user-images.githubusercontent.com/26684313/30239708-976f4436-958c-11e7-968a-9525dfe52e6e.png)

Here is my custom card with components taken from `react-bootstrap` https://react-bootstrap.github.io/components.html#panels

```
const CustomCard = props => {
    const CardSubject = (
        <h4>{props.subject}</h4>
    );

    return (
        <Panel header={CardSubject} bsStyle="success">
            <Grid>
                <Row className="show-grid">
                    <Col xs={12} md={8}>Status: {props.status}</Col>
                    <Col xs={6} md={4}>Assigned to: {props.assignee}</Col>
                </Row>
                <Row className="show-grid">
                    <Col xs={12} md={8}>Link1</Col>
                    <Col xs={6} md={4}>Link2</Col>
                </Row>
            </Grid>
        </Panel>
    )
}
```

**Comment by sluongng** [comment]
The cards rendered normally but only for the first row. Missing many cards, no card was rendered second row

**Comment by sluongng** [comment]
https://react-bootstrap.github.io/components.html#panels-contextual

Style which shown in this example of `react-bootstrap` also failed to render

**Comment by rcdexta** [comment]
Inspect the board data passed to `Board` component and ensure the `id` attribute of each card is unique. `card.id` is passed along as the react key prop to card elements inside a lane

**Comment by sluongng** [comment]
Thank you, I didnt know the Card.ID must be unique. Fixed that and its Ok now.
