### ISSUE TITLE
Board with className styling

### ISSUE THREAD

**Issue by ZachDillon** [rcdexta/react-trello#23]
Hi rcdexta,

Is it possible to add a className to the Board component with this styling on it, or is only inline styling supported?

JSX:
`<Board
          className={styles.board}
          data={processes}
        />`

CSS:
`.board {
  background-color: #191F26;
  padding-top: 10;
  padding-left: 10;
}`

Thanks

**Comment by rcdexta** [comment]
Yes should be possible now. I have added sample code to illustrate the point:
https://github.com/rcdexta/react-trello/blob/master/stories/BoardStyling.story.js

Please pull v1.20.4
