### ISSUE TITLE
Add localization/i18n

### ISSUE THREAD

**Issue by dapi** [rcdexta/react-trello#237]
We want to use this component for Russian users. I think it will be nice to have possibilities to use any other translations.

Probably the best way to do it is extrude all texts from the code and to use `react-i18next`.

If there are no other proposals or recommendations I would implement by myself in a week and send PR.

**Comment by Kalaschnik** [comment]
There are only two elements presented in English language by default (the add card button text and the ass lane button text). Both of them you can change, everything else (your data) is in your hand. Or am I missing some hard-coded hidden interface?

**Comment by dapi** [comment]
Buttons:

https://github.com/rcdexta/react-trello/blob/fa2690d9bc50e0ebb762c05e669da7dc2bf8aa61/src/components/NewCard.js#L33-L34

Add Card:

https://github.com/rcdexta/react-trello/blob/fa2690d9bc50e0ebb762c05e669da7dc2bf8aa61/src/components/Lane.js#L105

**Comment by dapi** [comment]
* `Lane actions`
* `Delete lane`

**Comment by dapi** [comment]
Total 9 texts to translate - https://github.com/rcdexta/react-trello/pull/248/files#diff-b9def2b395fcf7945c9622f2afb43520
