### ISSUE TITLE
Warning: Failed prop type: Invalid prop `label` of type `object` supplied to `Lane`, expected `string`.

### ISSUE THREAD

**Issue by chrislewispac** [rcdexta/react-trello#24]
If you pass a <Component/> into the label field the following error appears in the console but otherwise everything else works correctly.

Expected behavior would be that you can pass a component (button) into the title line of a lane.

Thanks!

**Comment by rcdexta** [comment]
Yes `lane.title` should not be restricted to just a string type and should accept any node. Please pull  the latest release version and the warning should go away. Thanks

**Comment by cfaure004** [comment]
Is is possible to also change label type to PropTypes.node ?
