### ISSUE TITLE
Use existing Button Style for Add Lane Button

### ISSUE THREAD

**Issue by Kalaschnik** [rcdexta/react-trello#243]
I’m not sure if this is already possible; but we use MDL style for different components, such as a button that is already design based on the company’s CI. Is there anyway to inject our <Button> to be used for the Add Lane Button?

**Comment by dapi** [comment]
@Kalaschnik   hi!

I have just  done Dependency Injection mechanism. Could you please test it and give me a feedback?

https://github.com/rcdexta/react-trello/pull/274

```
yarn add BrandyMint/react-trello#components_dependency_injections
```

I think it is a good way to get full control over components customisation.

If it is Ok, I will merge it to master.

**Comment by dapi** [comment]
Now dependency injection in master. You can override any used components.

https://github.com/rcdexta/react-trello#3-completely-customize-the-look-and-feel-by-using-components-dependency-injection

Pls open the issue if something is wrong
