### ISSUE TITLE
newCardTemplate when i try to add extra field inside  customAddCard Template its not working.. can anyone help me in this.

### ISSUE THREAD

**Issue by mehuljariwala** [rcdexta/react-trello#246]
Here is the code and scrrenshot.

`import React from "react";
import ReactDOM from "react-dom";

import data from "./data.json";
import "./styles.css";
import Board from "react-trello";

const NewCard = props => {
  return (
    <div>
      <input type="text" value={props.cp} onChange={props.onCardChange} />
      <input
        type="button"
        value="Add"
        onClick={() => props.onNewCardAdd(props.laneId, props.cp)}
      />
    </div>
  );
};
class App extends React.Component {
  state = {
    cp: ""
  };
  onNewCardAdd = (laneId, cp) => {
    let newData = data.lanes;
    newData.map(data => {
      if (data.id === laneId) {
        data.cards.push({ id: "sdasdsdas23123asdaskdlas", title: cp });
      }
      return data;
    });
    this.hideEditableCard();
  };
  onCardChange = event => {
    this.setState({
      cp: event.target.value
    });
  };

  render() {
    return (
      <div className="App">
        <h1>react-trello demo</h1>
        <Board
          data={data}
          draggable
          editable
          newCardTemplate={
            <NewCard
              onNewCardAdd={(laneId, cp) => this.onNewCardAdd(laneId, cp)}
            />
          }
          onCardChange={this.onCardChange}
        />
      </div>
    );
  }
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
`

how can i add cp in card data and when i click on add that time textbox is not hide in lane.

![image](https://user-images.githubusercontent.com/30499320/59148572-4efc6700-8a28-11e9-9df4-9f7b9de3ae36.png)

how can i use is generate function uuid ?

please can anyone help in this ? 

@rcdexta @Cody Fitzpatrick

**Comment by dapi** [comment]
I’m working on it here - https://github.com/BrandyMint/react-trello/pull/2

**Comment by dapi** [comment]
Wait until implement new way to inject components

**Comment by dapi** [comment]
@mehuljariwala try to use this branch - https://github.com/rcdexta/react-trello/pull/274

**Comment by dapi** [comment]
Now dependency injection in master. You can override any used components.

https://github.com/rcdexta/react-trello#3-completely-customize-the-look-and-feel-by-using-components-dependency-injection

Pls open the issue if something is wrong
