### ISSUE TITLE
Build fails in 2.1.4

### ISSUE THREAD

**Issue by MarioZ2002** [rcdexta/react-trello#247]
**Build fails**
Build fails with the following message:
Failed to minify the code from this file: 
./node_modules/react-trello/dist/dnd/Container.js:22

**Steps To Reproduce**
1. yarn add react-trello
2. yarn build

**Expected behavior**
Build without errors.

**Comment by MarioZ2002** [comment]
This was coming from "react-scripts-platformsh". 
It seems like it using react-scripts version < 2.0.0., which caused the build to fail.

Read more here: http://bit.ly/2tRViJ9

**Comment by Sasi50KLs** [comment]
I have the same issue. but I am using react-app-rewired. pls tell any idea to solve this issue.

>  react-app-rewired build

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

        ./node_modules/react-trello/dist/dnd/Container.js:22 

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
