### ISSUE TITLE
sourceLaneId equal targetLaneId?

### ISSUE THREAD

**Issue by Macragge** [rcdexta/react-trello#25]
Hi,
when implementing drag & drop behaviour it seems like the parameters sourceLaneId and targetLaneId which are given within the handleDragEnd-method are the same. In your Demo it is working correctly but when i use the code which is in your story.js it shows the beviour i just described above.

**Comment by rcdexta** [comment]
Ok let me check that. Does this happen when you move the card from one lane to another or juggling within the same lane?

**Comment by Macragge** [comment]
When i move it between lanes so in your example when i move from planned to wip source and target are always planned

**Comment by rcdexta** [comment]
This issue should be fixed now. Refer again to this example for implementing drag-n-drop: https://github.com/rcdexta/react-trello/blob/master/stories/DragDrop.story.js

Make sure the lane id is unique for each lane since it is passed along to the `handleDragEnd` method. Use v1.21.4
