### ISSUE TITLE
How can i get lane id when user delete lane.

### ISSUE THREAD

**Issue by mehuljariwala** [rcdexta/react-trello#250]
i need removeLane Function 

@rcdexta @javajamine @G-Rath @lowsky

**Comment by dapi** [comment]
PR with `onLaneDelete`  is merged https://github.com/rcdexta/react-trello/pull/255

**Comment by dapi** [comment]
@mehuljariwala is `onLaneDelete` do what you requested? Can we close the issue?

**Comment by yashutanna** [comment]
Hey guys - thanks for the cool library. having an issue with the onLaneDelete property. it is ignored and does not register the event handler. see sandbox below

[![Edit react-trello-example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-trello-example-y4ymw?fontsize=14)

**Comment by mehuljariwala** [comment]
Yes problem is there .
@dapi  can you check please this issue.

Thanks
