### ISSUE TITLE
I would like to help to maintain this project

### ISSUE THREAD

**Issue by dapi** [rcdexta/react-trello#257]
@rcdexta thank you for this component!

It looks like we will use it in our new projects (it some a-la trello task manager) and I would like to help you to maintain the project.

What is you goals with it? Have any roadmap?

We think `react-trello` need to be more extensible:

* possibility to use custom styles without `classes`
* possibility to good looking realtime async update state of board, lanes, tasks
* some minor improvements in card creation and editing
* easy way to customise lane`s panel menu

**Comment by rcdexta** [comment]
@dapi Thanks for showing interest in contributing to this repository. As you can see from the pending PRs and open issues, I am looking for maintainers for this repo. As first steps, can you pls start looking at issues and assign yourself against the ones that you can help fix.

I am with you on offering more ways to customize the library and let the user gain fine-grained control over the look-and-feel. Let's work on moving away from classes to styles as first step.

**Comment by dapi** [comment]
hi!

I have no rights to assign issues, but I could take these:

## Features

* https://github.com/rcdexta/react-trello/issues/204
* https://github.com/rcdexta/react-trello/issues/246

## Bugs

* https://github.com/rcdexta/react-trello/issues/154
* https://github.com/rcdexta/react-trello/issues/168
* https://github.com/rcdexta/react-trello/issues/195
* https://github.com/rcdexta/react-trello/issues/205

## Other

These issues will be fixed automatically when we merge PR with I18n - https://github.com/rcdexta/react-trello/pull/248

* https://github.com/rcdexta/react-trello/issues/236
* https://github.com/rcdexta/react-trello/issues/175

These issues could be closed if owners agree:

* https://github.com/rcdexta/react-trello/issues/178
* https://github.com/rcdexta/react-trello/issues/182
* https://github.com/rcdexta/react-trello/issues/183
* https://github.com/rcdexta/react-trello/issues/198
* https://github.com/rcdexta/react-trello/issues/250

About styling. What to you think about to replace `styled-components` with `emotion`? It has smaller size and more powerful.

Also here I refactored the way to pass custom templates of elements. It uses component class/functions instead of templates - https://github.com/BrandyMint/react-trello/pull/2/files

**Comment by dapi** [comment]
now in progress

**Comment by dapi** [comment]
@rcdexta yesterday you give me write access, today it is denied. I can’t assign issues and change it’s label.

I have merged some small PR into master is that OK?

**Comment by rcdexta** [comment]
@dapi you should have complete access to this repo as I have made you one of the collaborators. Had to delete the existing config and send a new invitation. Can you accept that again?

**Comment by rcdexta** [comment]
@dapi email me directly if you are still facing issues. thanks

**Comment by dapi** [comment]
I got it, thanks!
