### ISSUE TITLE
There is no edit lane option is there.

### ISSUE THREAD

**Issue by mehuljariwala** [rcdexta/react-trello#263]
when i add lane but i am not able to edit lane after adding new Lane.

if you have this feature then good me to extend my project.

@dapi @rcdexta 

Thanks @dapi  for support

**Comment by dapi** [comment]
Hi @mehuljariwala !

Do you mean edit the title or adding cards to the lane?

**Comment by mehuljariwala** [comment]
@dapi 
I need to edit the lane title

**Comment by dapi** [comment]
@mehuljariwala I got. Doing this feature, will show in a week

**Comment by mehuljariwala** [comment]
did you fix this issue ? @dapi

**Comment by dapi** [comment]
working on it https://github.com/rcdexta/react-trello/pull/274

**Comment by dapi** [comment]
@mehuljariwala could you try this branch? https://github.com/rcdexta/react-trello/pull/283

**Comment by dapi** [comment]
Now in master availability to edit lane title.

Use `onLaneUpdate` and `editLaneTitle`props.

Look into story - https://github.com/rcdexta/react-trello/blob/master/stories/EditableBoard.story.js#L81
