### ISSUE TITLE
Style the Lane Label

### ISSUE THREAD

**Issue by emorling** [rcdexta/react-trello#27]
Great component 👍 

What is the proper way tot style the Lane Label? I recognize the Lane, and Title can be styled, but what of the Label?

**Comment by rcdexta** [comment]
Fixed. Pass `labelStyle` along with lane attributes to override label appearance. Pls pull the latest version

Example here: http://rcdexta.me/react-trello/?selectedKind=React%20Trello&selectedStory=Card%20and%20Lane%20Styling&full=0&down=0&left=1&panelRight=0

Code here: https://github.com/rcdexta/react-trello/blob/master/stories/CustomCardAndLaneStyling.story.js
