### ISSUE TITLE
how can i add extra properties in json when i add card in lane

### ISSUE THREAD

**Issue by mehuljariwala** [rcdexta/react-trello#280]
Hello,
I need to add other properties in card json like.
if i add card then its give (label,description,title) but i need to add date also when user add new card..
but i don't want to user customAddCard templates.

is there any changes ? 

@dapi 

Thanks @dapi  you are great

**Comment by dapi** [comment]
Hi! I'm thinking about it..

**Comment by dapi** [comment]
Use `metadata`:
```
src/controllers/Lane.js:    onCardClick && onCardClick(card.id, card.metadata, card.laneId)
```

**Comment by dapi** [comment]
@mehuljariwala hi! What do you think about `metadata` usage?

**Comment by dapi** [comment]
@mehuljariwala how it is going?
