### ISSUE TITLE
When adding a new lane, the title field overflows

### ISSUE THREAD

**Issue by BenHenderson09** [rcdexta/react-trello#281]
Go to the [Storybook](https://rcdexta.com/react-trello/?selectedKind=Editable%20Board&selectedStory=Add%20New%20Lane&full=0&addons=0&stories=1&panelRight=0) and if you type a long string into the title field when adding a new lane, the text overflows. Also, the long text will obscure the "lane actions" (three dots) icon when saved.

![trello](https://user-images.githubusercontent.com/37810700/60665860-87436980-9e5d-11e9-9bff-7a125b171d0f.png)

![trello2](https://user-images.githubusercontent.com/37810700/60665952-c1147000-9e5d-11e9-87d4-84d716191866.png)

**Comment by dapi** [comment]
thank you for reporting!

**Comment by BenHenderson09** [comment]
No problem :+1:

**Comment by dapi** [comment]
http://g.recordit.co/1zSUs3T7up.gif

**Comment by dapi** [comment]
@BenHenderson09 fixes in master branch

**Comment by BenHenderson09** [comment]
Thanks.
