### ISSUE TITLE
Version 2.2

### ISSUE THREAD

**Issue by PeterKottas** [rcdexta/react-trello#284]
It seems there was a breaking change in the api supported even by https://github.com/rcdexta/react-trello/blob/master/UPGRADE.md . It's also well documented. The only problem is the 2.2 version is nowhere to be found :) Maybe the build didn't kick in properly. Would you be releasing these changes any time soon? Cheers

**Comment by dapi** [comment]
@PeterKottas I wait for more reviews from users to release it. Do you try 2.2?

**Comment by PeterKottas** [comment]
I see. Yep been using it extensively for the past few days. I found a bunch of small stuff. Nothing major. I am afk now. I'll get detailed overview to you once I am at the pc. Also please look at my other "issue". Hope you are still interested in typescript rewrite as I would be happy to make that happen.

**Comment by PeterKottas** [comment]
1. 
```
Warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use PropTypes.checkPropTypes() to call them. Read more at http://fb.me/use-check-prop-types in PopoverWrapper
```
This apparently happens inside https://github.com/terebentina/react-popover which was last updated 2 years ago. Maybe the package could be replaced with something that is maintained.
2.
```
Warning: Unknown event handler property `onCardMoveAcrossLanes`. It will be ignored.
```
This is the stack:
```
in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div
    in BoardContainer
    in Connect(BoardContainer)
    in Provider
    in Board
```
This is a simple fix, it just needs adding here https://github.com/rcdexta/react-trello/blob/master/src/controllers/BoardContainer.js#L126
3. Cursor change to grab even if lane/card is not draggable. 
4. This is more of a feature request. It would be great if the result of onDragEnd could change the cursor to no-drop if it returns false. I am pretty sure this is doable with react-dnd.

Other than that it's working great!

**Comment by PeterKottas** [comment]
https://github.com/rcdexta/react-trello/pull/286 actually takes care of 3.

**Comment by dapi** [comment]
Thank you for the response!

1. We have the issue - https://github.com/rcdexta/react-trello/issues/201
2. Just created the issue - https://github.com/rcdexta/react-trello/issues/288
4. Please extract it to separate issue

**Comment by PeterKottas** [comment]
Cheers, I think you meant to say create a new issue for number 4. I'll do that right away. Please while you here consider #285 . I have some time today and I could get most of the work done.

**Comment by dapi** [comment]
> create a new issue for number 4.

yeah )

**Comment by sstalder** [comment]
How do we use 2.2 in a project? Do you plan to publish a preview on npm?

**Comment by dapi** [comment]
Use:

`yarn add rcdexta/react-trello`

I plan to release it this month. Now it's version 2.3 )

**Comment by sstalder** [comment]
After doing that I get Module not found: Can't resolve 'react-trello'. I've tried a few different ways of importing it (im using import Board from 'react-trello';). Sorry if this is obvious but how do I reference it now?

**Comment by dapi** [comment]
What it you `import` string?

Try `import ... 'react-trello/src’`

**Comment by sstalder** [comment]
That gives me Unexpected token < on the return <Board> line. I'll just wait for you to release it to NPM as nothing else appears to work for me.

With `import Board from 'react-trello'`

![error1](https://user-images.githubusercontent.com/504421/61557881-7127d280-aa33-11e9-8b25-f12c1ef95cb7.PNG)

With `import Board from 'react-trello/src'`

![error2](https://user-images.githubusercontent.com/504421/61557882-7127d280-aa33-11e9-899d-47c4635ffa5d.PNG)

**Comment by dapi** [comment]
@sstalder do you use `babel`? and `@babel/preset-env`?

**Comment by dapi** [comment]
@rcdexta hi! I think we can publish current version (2.3.1) to npm.

**Comment by sstalder** [comment]
That would be awesome! I don't believe I had babel-env as I am just trying to use it in a create-react-app application.

**Comment by rcdexta** [comment]
@dapi  I will be glad to publish latest changes to npm. Just a note on version management. We use https://github.com/semantic-release/semantic-release to upgrade our version numbers. To make a release use `npm run commit` instead of `git commit` when committing latest changes to master. Every commit is built in travis and semantic release workflow will take care of publishing it to npm. I have removed the hard coded version from `package.json` for now.

Again, I appreciate all the hard work @dapi 

v2.2 released to npm
