### ISSUE TITLE
onCardDelete Event doesn't get fired anymore

### ISSUE THREAD

**Issue by MarioZ2002** [rcdexta/react-trello#298]
**Describe the bug**
After upgrading to 2.2 the onCardDelete Event doesn't seem to work anymore

**To Reproduce**
1. See Storybook

**Expected behavior**
Print CardId and LaneId to the console when card gets deleted (see storybook: [here](https://rcdexta.com/react-trello/?selectedKind=Editable%20Board&selectedStory=Add%2FDelete%20Cards&full=0&addons=0&stories=1&panelRight=0))

**Comment by yashutanna** [comment]
+1 Was just about to open this issue myself

**Comment by yashutanna** [comment]
I have made a fix for this issue @dapi. how I need access to open a PR it seems?
