### ISSUE TITLE
Unable to drag cards

### ISSUE THREAD

**Issue by edudavid** [rcdexta/react-trello#3]
Hello @rcdexta ,

First of all congratulations for the component.

I am playing with react-trello but I am having issues with drag and drop cards between lanes.

Here is my code:
`  render() {
    return (
      <Board
        data={data}
        draggable={true}
        onDragStart={() => console.log('start')}
        onDragEnd={() => console.log('end')}
      />
    );
  }`

What I am missing?

Regards,

Eduardo

**Comment by rcdexta** [comment]
Hi @edudavid,

Thanks for trying react-trello. The drag-n-drop functionality was broken with the recent refactoring that I did. Fixed that and the latest release 1.11.0 should work

Please refer to this storybook example for reference: https://github.com/rcdexta/react-trello/blob/master/stories/DragDrop.story.js

Thanks

**Comment by edudavid** [comment]
Hello @rcdexta ,

Great, now it is working perfectly.

One issue I found with build script is that the file Dragula.scss is not being copied to the dist/styles directory.

Updating the package.json with the following line, fixed the problem:

`"build": "babel src --out-dir dist --copy-files"`

Do you want me to open a PR with this fix or there is other way to fix it?

Thank you.

Regards,

Eduardo

**Comment by rcdexta** [comment]
Yes pls send me a PR @edudavid. For now let's add to the build script. Eventually I will move it to styled_components like the rest of the styles in the library. Thanks

**Comment by rcdexta** [comment]
Fixed the build script. We are good now. Thanks

**Comment by edudavid** [comment]
Awesome! 👍
