### ISSUE TITLE
Is anyone working on Draggable Lanes?

### ISSUE THREAD

**Issue by emorling** [rcdexta/react-trello#30]
I see that there seems to be some preparation for draggable lanes, but not yet implemented?

**Comment by changyu72** [comment]
Oh, looking forward to it, thank you！

**Comment by rcdexta** [comment]
Check out this storybook for intended behaviour: http://rcdexta.me/react-trello/?selectedKind=Drag-n-Drop&selectedStory=Basic&full=0&down=0&left=1&panelRight=0

Usage code here: https://github.com/rcdexta/react-trello/blob/master/stories/DragDrop.story.js

Added two handlers specific to lane drop. Pull the latest release to see changes in effect.

**Comment by changyu72** [comment]
Thanks very much! But sometimes drag failure?

**Comment by rcdexta** [comment]
@changyu72 Could you give more details? Are we talking lane or card dnd?

**Comment by changyu72** [comment]
When dragging lane, over other lane through a state similar to the drag of card down, the dragged lane  go to the first, and then  can not drag anything.

**Comment by changyu72** [comment]
![2018-05-06_12-43-51](https://user-images.githubusercontent.com/18181509/39669917-742a8cd2-512b-11e8-940b-d1286b062484.gif)

**Comment by rcdexta** [comment]
@changyu72 Thanks for pointing that out. The latest release patch should fix that

**Comment by changyu72** [comment]
thanks!
