### ISSUE TITLE
Implementing a custom translation table doesnt work 

### ISSUE THREAD

**Issue by danielmoenius** [rcdexta/react-trello#300]
**Describe the bug**
I tried to implement a custom translation table for the whole board.
With the property t.

**To Reproduce**
I implemented it like that 

import React from "react";
import { Board } from "react-trello";

const KanbanBoard = () => {

	const TRANSLATION_TABLE = {
		"Add another lane": "+ Weitere Liste erstellen",
		"Click to add card": "Klicken zum Erstellen einer Karte",
		"Delete lane": "Liste löschen",
		"Lane actions": "Listenaktionen",
		"button": {
			"Add lane": "Liste hinzufügen",
			"Add card": "Karte hinzufügen",
			"Cancel": "Abbrechen"
		},
		"placeholder": {
			"title": "Titel",
			"description": "Beschreibung",
			"label": "Label"
		}
	};

	const customTranslation = (key) => TRANSLATION_TABLE[key];

	const data = {
		...
	};

	return (
		<div>
			<Board
				t={customTranslation}
				data={data}
				draggable
				editable
				canAddLanes
			/>
		</div>
	);
};

export default KanbanBoard;

**Expected behavior**
The board should use the given new translations from my table TRANSLATION_TABLE

**Desktop:**
 - OS: [Mac OS]
 - Browser [Chrome]
 - Version [newest]

**Additional context**
I think its more likely that I understood it wrong how to use the property t.
It wld be great to have a example how to use it with a specific use case.
Thanks for the help and thanks for the great project.

**Comment by dapi** [comment]
@danielmoenius thank you for response!

You should either have flat translation table or use provided `createTranslation` function.

Here is more examples - https://github.com/rcdexta/react-trello/pull/303/files

README is updated

**Comment by danielmoenius** [comment]
Thanks man! Awesome!
