### ISSUE TITLE
Placeholders are missing when adding a new card to a lane

### ISSUE THREAD

**Issue by yashutanna** [rcdexta/react-trello#301]
**Describe the bug**
Placeholders are missing when adding a new card to a lane

**To Reproduce**
1. Go to 'Add/Delete Cards' in story book
2. add a new card

**Expected behavior**
When adding a new card to a lanem the Title, Description and Label fields should have placeholders.

**Screenshots**
![image](https://user-images.githubusercontent.com/6696871/61705640-7b551400-ad46-11e9-87a5-a2843e4d8a65.png)

**Comment by dapi** [comment]
@yashutanna thank you! Fixes in master
