### ISSUE TITLE
Delete Icon not there in Custom Card Component

### ISSUE THREAD

**Issue by mehuljariwala** [rcdexta/react-trello#306]
I implemented custom card then i figure out that remove card icon was remove when we use custom card component.
you can check this link its not there close(remove) Icon.

https://rcdexta.com/react-trello/?selectedKind=Custom%20Components&selectedStory=Card&full=0&addons=0&stories=1&panelRight=0

@dapi @rcdexta

**Comment by dapi** [comment]
@mehuljariwala hi!

Special for you just added an example of Delete Icon usage into CustomCard story.

**Comment by mehuljariwala** [comment]
can you provide me link where did you added delete Icon example ? @dapi

**Comment by dapi** [comment]
Commit is attached to this issue - https://github.com/rcdexta/react-trello/commit/e309543e750d7397763e07eeb887a80b7ca586ef
