### ISSUE TITLE
Dynamic updating Card Title

### ISSUE THREAD

**Issue by emorling** [rcdexta/react-trello#31]
I am programatically updating the Card Title, but this does not seem to impact the rendering of the Card Title? Any ideas?

**Comment by rcdexta** [comment]
I have added an example story to illustrate programmatic changes to lane and card titles. Would recommend using a library like `immutability-helper` to modify the data passed to the board.

Code here: https://github.com/rcdexta/react-trello/blob/master/stories/Realtime.story.js
Example here: http://rcdexta.me/react-trello/?selectedKind=React%20Trello&selectedStory=Realtime%20Events&full=0&down=0&left=1&panelRight=0

Pls pull version 1.22.1
