### ISSUE TITLE
Upgrade smooth-dnd to the latest version

### ISSUE THREAD

**Issue by hugo4711** [rcdexta/react-trello#317]
smooth-dnd which react-trello uses (0.6.x) is outdated and does not work with other packages (e.g. react-smooth-dnd) requiring a newer version (0.12.0 or later).

Oddly enough the package.json of react-trello@2.2.3 specifies the git repo for downloading smooth-dnd which does not load the latest stable version of smooth-dnd (0.12.0)...

**Comment by hugo4711** [comment]
I think react-trello should utilize react-smooth-dnd instead, but I also saw that you modified smooth-dnd for your purposes somehow....

**Comment by rcdexta** [comment]
Done and pulled it out as a package dependency

**Comment by hugo4711** [comment]
Great! Thanks a lot!
