### ISSUE TITLE
Customcard example is not working  

### ISSUE THREAD

**Issue by Arrow66** [rcdexta/react-trello#319]
how can i import MovableCardWrapper  shown in customcard example in my app to make a customcard ?.can you give another example on customising card when using with npm package

**Comment by guifeliper** [comment]
Did you manage how to custom a card?

**Comment by Arrow66** [comment]
@guifeliper  yes 
customCard  is just a functional component .all we have to do is plug that in to Board like this  
` <Board
                  data={props.janusReducer.trelloData || {}}
                  components={{
                    Card: customCard
                  }}
                  onCardClick={(cardId, metadata, laneId) => {
                    cardClick(cardId, metadata, laneId);
                  }}
                  style={{
                    display: "flex",
                    height: "100%",
                    width: "100%",
                    overflowY: "hidden",
                    overflowX: "scroll"
                  }}
                />`

**Comment by guifeliper** [comment]
Thank you @Arrow66 
What do you have inside your customCard variable?

**Comment by Arrow66** [comment]
```
let customCard = (data) =>{
return (
<div  style={{
        display: "flex",
        marginTop: "5px",
        marginBottom: "5px",
        backgroundColor: "#14D496",
        height: "180px",
        width: "300px",
        borderRadius: "10px",
        flexDirection: "column"
}}
onClick={data.onClick}
>
{ data.value}
</div>
)
}
```

@guifeliper  this is the structure  my custom card component

**Comment by guifeliper** [comment]
Thank you so much @Arrow66
