### ISSUE TITLE
Passing components to the Lane

### ISSUE THREAD

**Issue by vctormb** [rcdexta/react-trello#32]
Is it possible to pass components to the lane?

**For example:** The Lane has a label, but it accepts only string. Is it possible to pass a custom component inside a lane? For example, I would like to pass an 'options' component there instead a string, or maybe pass a custom 'button' component at the end of the lane, to add cards to the lanes.

**Comment by rcdexta** [comment]
Might need a day or two to get this implemented. Will push by weekend...

**Comment by rcdexta** [comment]
Check this story for sample code: https://github.com/rcdexta/react-trello/blob/master/stories/CustomLaneStyling.story.js

Illustrative example here: https://rcdexta.github.io/react-trello/?selectedKind=React%20Trello&selectedStory=Custom%20Lane%20Template&full=0&down=0&left=1&panelRight=0
