### ISSUE TITLE
When adding a new card, I do not receive the nextData

### ISSUE THREAD

**Issue by vctormb** [rcdexta/react-trello#33]
When I add a card to the board using .publish({type: 'ADD_CARD', ...}); I do not receive the nextData inside the function called 'shouldReceiveNewData'.

When I add a card, the component does not render again to get the new state.
The state is not updating with the new card added.

**My example:**

```
addCard = () => {
        const { eventBus, } = this.state;

        eventBus.publish({
            type: 'ADD_CARD',
            laneId: 'lane1',
            card: {
                id: `card1`,
                title: 'new card',
                label: '30 mins',
                description: 'new task',
                metadata: { laneId: 'lane1' }
            }
        });
    }
```

```
shouldReceiveNewData = nextData => {
        console.log('it is not being called);
        console.log(nextData);
    }
```

`<Board data={this.state.boardData} eventBusHandle={this.setEventBus} onDataChange{this.shouldReceiveNewData}/>`

**Comment by rcdexta** [comment]
Thanks for pointing this out. This functionality broke in a recent release I guess. Fixed now. Please pull v1.22.2.

Refer to storybook again for updated behaviour..
