### ISSUE TITLE
Any specific lane style.

### ISSUE THREAD

**Issue by mohaimenmahi** [rcdexta/react-trello#330]
I am using react-trello for my recent project. I need to style on an specific lane, ex: the width of first lane should be larger then the others as well as the cards on that lane will be fitted to the lane. Is it possible somehow to do this?

**Comment by dapi** [comment]
Create and customise you own Lane component - https://github.com/rcdexta/react-trello#3-completely-customize-the-look-and-feel-by-using-components-dependency-injection
