### ISSUE TITLE
npm install react-trello not installed

### ISSUE THREAD

**Issue by priteshbhoi** [rcdexta/react-trello#332]
I am trying to install react-trello to my project but it is not installed on my project.
**below is my snap:** 
![image](https://user-images.githubusercontent.com/58101766/70044623-ba468080-15e8-11ea-8e5c-40cb2a4bede5.png)

**Desktop (please complete the following information):**
 - Window 10 Pro
 - Google Chrome

**When I am Install I got this:**
`

- 0 info it worked if it ends with ok
- 1 verbose cli [
- 1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
- 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
- 1 verbose cli   'install',
- 1 verbose cli   'react-trello'
- 1 verbose cli ]
- 2 info using npm@6.12.0
- 3 info using node@v12.13.0
- 4 verbose npm-session 7753f30f3eb314b7
- 5 silly install loadCurrentTree
- 6 silly install readLocalPackageData
- 7 http fetch GET 304 https://registry.npmjs.org/react-trello 245ms (from cache)
- 8 silly pacote tag manifest for react-trello@latest fetched in 281ms
- 9 timing stage:loadCurrentTree Completed in 990ms
- 10 silly install loadIdealTree
- 11 silly install cloneCurrentTreeToIdealTree
- 12 timing stage:loadIdealTree:cloneCurrentTree Completed in 4ms
- 13 silly install loadShrinkwrap
- 14 timing stage:loadIdealTree:loadShrinkwrap Completed in 342ms
- 15 silly install loadAllDepsIntoIdealTree
- 16 silly resolveWithNewModule react-trello@2.2.3 checking installable status
- 17 silly fetchPackageMetaData error for smooth-dnd@git+https://github.com/rcdexta/smooth-dnd.git Error while executing:
- 17 silly fetchPackageMetaData undefined ls-remote -h -t https://github.com/rcdexta/smooth-dnd.git
- 17 silly fetchPackageMetaData
- 17 silly fetchPackageMetaData
- 17 silly fetchPackageMetaData spawn git ENOENT
- 18 silly fetchPackageMetaData error for react-click-outside@github:tj/react-click-outside Error while executing:
- 18 silly fetchPackageMetaData undefined ls-remote -h -t ssh://git@github.com/tj/react-click-outside.git
- 18 silly fetchPackageMetaData
- 18 silly fetchPackageMetaData
- 18 silly fetchPackageMetaData spawn git ENOENT
- 19 http fetch GET 304 https://registry.npmjs.org/react-redux 89ms (from cache)
- 20 silly pacote range manifest for react-redux@^5.0.7 fetched in 102ms
- 21 silly resolveWithNewModule react-redux@5.1.2 checking installable status
- 22 http fetch GET 304 https://registry.npmjs.org/autosize 172ms (from cache)
- 23 silly pacote range manifest for autosize@^4.0.2 fetched in 182ms
- 24 silly resolveWithNewModule autosize@4.0.2 checking installable status
- 25 http fetch GET 304 https://registry.npmjs.org/immutability-helper 183ms (from cache)
- 26 silly pacote range manifest for immutability-helper@^2.8.1 fetched in 194ms
- 27 silly resolveWithNewModule immutability-helper@2.9.1 checking installable status
- 28 timing stage:rollbackFailedOptional Completed in 0ms
- 29 timing stage:runTopLevelLifecycles Completed in 1550ms
- 30 silly saveTree Template
- 30 silly saveTree +-- @babel/code-frame@7.5.5
- 30 silly saveTree | `-- @babel/highlight@7.5.0
- 30 silly saveTree |   +-- chalk@2.4.2
- 30 silly saveTree |   | +-- ansi-styles@3.2.1
- 30 silly saveTree |   | | `-- color-convert@1.9.3
- 30 silly saveTree |   | |   `-- color-name@1.1.3
- 30 silly saveTree |   | +-- escape-string-regexp@1.0.5
- 30 silly saveTree |   | `-- supports-color@5.5.0
- 30 silly saveTree |   |   `-- has-flag@3.0.0
- 30 silly saveTree |   +-- esutils@2.0.3
- 30 silly saveTree |   `-- js-tokens@4.0.0
- 30 silly saveTree +-- @babel/generator@7.7.4
- 30 silly saveTree | +-- @babel/types@7.7.4
- 30 silly saveTree | | +-- lodash@4.17.15
- 30 silly saveTree | | `-- to-fast-properties@2.0.0
- 30 silly saveTree | +-- jsesc@2.5.2
- 30 silly saveTree | +-- lodash@4.17.15
- 30 silly saveTree | `-- source-map@0.5.7
- 30 silly saveTree +-- @babel/helper-annotate-as-pure@7.7.4
- 30 silly saveTree +-- @babel/helper-function-name@7.7.4
- 30 silly saveTree | +-- @babel/helper-get-function-arity@7.7.4
- 30 silly saveTree | `-- @babel/template@7.7.4
- 30 silly saveTree |   `-- @babel/parser@7.7.4
- 30 silly saveTree +-- @babel/helper-get-function-arity@7.7.4
- 30 silly saveTree +-- @babel/helper-module-imports@7.7.4
- 30 silly saveTree +-- @babel/helper-split-export-declaration@7.7.4
- 30 silly saveTree +-- @babel/highlight@7.5.0
- 30 silly saveTree +-- @babel/parser@7.7.4
- 30 silly saveTree +-- @babel/runtime@7.7.4
- 30 silly saveTree | `-- regenerator-runtime@0.13.3
- 30 silly saveTree +-- @babel/template@7.7.4
- 30 silly saveTree +-- @babel/traverse@7.7.4
- 30 silly saveTree | +-- debug@4.1.1
- 30 silly saveTree | | `-- ms@2.1.2
- 30 silly saveTree | `-- globals@11.12.0
- 30 silly saveTree +-- @babel/types@7.7.4
- 30 silly saveTree +-- @emotion/is-prop-valid@0.8.5
- 30 silly saveTree | `-- @emotion/memoize@0.7.3
- 30 silly saveTree +-- @emotion/memoize@0.7.3
- 30 silly saveTree +-- @emotion/unitless@0.7.4
- 30 silly saveTree +-- @fullcalendar/daygrid@4.3.0
- 30 silly saveTree +-- @fullcalendar/timegrid@4.3.0
- 30 silly saveTree +-- @rooks/use-mutation-observer@3.4.0
- 30 silly saveTree +-- abbrev@1.1.1
- 30 silly saveTree +-- ajv@6.10.2
- 30 silly saveTree | +-- fast-deep-equal@2.0.1
- 30 silly saveTree | +-- fast-json-stable-stringify@2.0.0
- 30 silly saveTree | +-- json-schema-traverse@0.4.1
- 30 silly saveTree | `-- uri-js@4.2.2
- 30 silly saveTree |   `-- punycode@2.1.1
- 30 silly saveTree +-- amdefine@1.0.1
- 30 silly saveTree +-- ansi-regex@2.1.1
- 30 silly saveTree +-- ansi-styles@2.2.1
- 30 silly saveTree +-- aproba@1.2.0
- 30 silly saveTree +-- are-we-there-yet@1.1.5
- 30 silly saveTree | +-- delegates@1.0.0
- 30 silly saveTree | `-- readable-stream@2.3.6
- 30 silly saveTree |   +-- core-util-is@1.0.2
- 30 silly saveTree |   +-- inherits@2.0.4
- 30 silly saveTree |   +-- isarray@1.0.0
- 30 silly saveTree |   +-- process-nextick-args@2.0.1
- 30 silly saveTree |   +-- safe-buffer@5.1.2
- 30 silly saveTree |   +-- string_decoder@1.1.1
- 30 silly saveTree |   `-- util-deprecate@1.0.2
- 30 silly saveTree +-- array-find-index@1.0.2
- 30 silly saveTree +-- asn1@0.2.4
- 30 silly saveTree | `-- safer-buffer@2.1.2
- 30 silly saveTree +-- assert-plus@1.0.0
- 30 silly saveTree +-- async-foreach@0.1.3
- 30 silly saveTree +-- asynckit@0.4.0
- 30 silly saveTree +-- aws-sign2@0.7.0
- 30 silly saveTree +-- aws4@1.9.0
- 30 silly saveTree +-- babel-plugin-styled-components@1.10.6
- 30 silly saveTree | `-- babel-plugin-syntax-jsx@6.18.0
- 30 silly saveTree +-- babel-plugin-syntax-jsx@6.18.0
- 30 silly saveTree +-- babel-runtime@6.26.0
- 30 silly saveTree | +-- core-js@2.6.10
- 30 silly saveTree | `-- regenerator-runtime@0.11.1
- 30 silly saveTree +-- balanced-match@1.0.0
- 30 silly saveTree +-- bcrypt-pbkdf@1.0.2
- 30 silly saveTree | `-- tweetnacl@0.14.5
- 30 silly saveTree +-- block-stream@0.0.9
- 30 silly saveTree +-- brace-expansion@1.1.11
- 30 silly saveTree | `-- concat-map@0.0.1
- 30 silly saveTree +-- camelcase-keys@2.1.0
- 30 silly saveTree | +-- camelcase@2.1.1
- 30 silly saveTree | `-- map-obj@1.0.1
- 30 silly saveTree +-- camelcase@2.1.1
- 30 silly saveTree +-- camelize@1.0.0
- 30 silly saveTree +-- caseless@0.12.0
- 30 silly saveTree +-- chalk@1.1.3
- 30 silly saveTree | +-- has-ansi@2.0.0
- 30 silly saveTree | +-- strip-ansi@3.0.1
- 30 silly saveTree | `-- supports-color@2.0.0
- 30 silly saveTree +-- classnames@2.2.6
- 30 silly saveTree +-- cliui@3.2.0
- 30 silly saveTree | +-- string-width@1.0.2
- 30 silly saveTree | | +-- code-point-at@1.1.0
- 30 silly saveTree | | `-- is-fullwidth-code-point@1.0.0
- 30 silly saveTree | |   `-- number-is-nan@1.0.1
- 30 silly saveTree | `-- wrap-ansi@2.1.0
- 30 silly saveTree +-- code-point-at@1.1.0
- 30 silly saveTree +-- color-convert@1.9.3
- 30 silly saveTree +-- color-name@1.1.3
- 30 silly saveTree +-- combined-stream@1.0.8
- 30 silly saveTree | `-- delayed-stream@1.0.0
- 30 silly saveTree +-- concat-map@0.0.1
- 30 silly saveTree +-- console-control-strings@1.1.0
- 30 silly saveTree +-- core-js@2.6.10
- 30 silly saveTree +-- core-util-is@1.0.2
- 30 silly saveTree +-- cross-spawn@3.0.1
- 30 silly saveTree | +-- lru-cache@4.1.5
- 30 silly saveTree | | +-- pseudomap@1.0.2
- 30 silly saveTree | | `-- yallist@2.1.2
- 30 silly saveTree | `-- which@1.3.1
- 30 silly saveTree |   `-- isexe@2.0.0
- 30 silly saveTree +-- css-color-keywords@1.0.0
- 30 silly saveTree +-- css-to-react-native@2.3.2
- 30 silly saveTree | `-- postcss-value-parser@3.3.1
- 30 silly saveTree +-- currently-unhandled@0.4.1
- 30 silly saveTree +-- d3-array@2.4.0
- 30 silly saveTree +-- d3-color@1.4.0
- 30 silly saveTree +-- d3-format@1.4.2
- 30 silly saveTree +-- d3-interpolate@1.4.0
- 30 silly saveTree +-- d3-path@1.0.9
- 30 silly saveTree +-- d3-scale@3.2.1
- 30 silly saveTree | +-- d3-time-format@2.2.2
- 30 silly saveTree | | `-- d3-time@1.1.0
- 30 silly saveTree | `-- d3-time@1.1.0
- 30 silly saveTree +-- d3-shape@1.3.7
- 30 silly saveTree +-- d3-time-format@2.2.2
- 30 silly saveTree +-- d3-time@1.1.0
- 30 silly saveTree +-- dashdash@1.14.1
- 30 silly saveTree +-- debug@4.1.1
- 30 silly saveTree +-- decamelize@1.2.0
- 30 silly saveTree +-- decimal.js-light@2.5.0
- 30 silly saveTree +-- deep-diff@0.3.8
- 30 silly saveTree +-- delayed-stream@1.0.0
- 30 silly saveTree +-- delegates@1.0.0
- 30 silly saveTree +-- detect-node@2.0.4
- 30 silly saveTree +-- dom-helpers@3.4.0
- 30 silly saveTree +-- ecc-jsbn@0.1.2
- 30 silly saveTree | `-- jsbn@0.1.1
- 30 silly saveTree +-- error-ex@1.3.2
- 30 silly saveTree | `-- is-arrayish@0.2.1
- 30 silly saveTree +-- escape-string-regexp@1.0.5
- 30 silly saveTree +-- esutils@2.0.3
- 30 silly saveTree +-- extend@3.0.2
- 30 silly saveTree +-- extsprintf@1.3.0
- 30 silly saveTree +-- fast-deep-equal@2.0.1
- 30 silly saveTree +-- fast-json-stable-stringify@2.0.0
- 30 silly saveTree +-- find-up@1.1.2
- 30 silly saveTree | +-- path-exists@2.1.0
- 30 silly saveTree | | `-- pinkie-promise@2.0.1
- 30 silly saveTree | |   `-- pinkie@2.0.4
- 30 silly saveTree | `-- pinkie-promise@2.0.1
- 30 silly saveTree +-- focus-lock@0.6.6
- 30 silly saveTree +-- focus-outline-manager@1.0.2
- 30 silly saveTree +-- forever-agent@0.6.1
- 30 silly saveTree +-- form-data@2.3.3
- 30 silly saveTree | `-- mime-types@2.1.25
- 30 silly saveTree |   `-- mime-db@1.42.0
- 30 silly saveTree +-- fs.realpath@1.0.0
- 30 silly saveTree +-- fstream@1.0.12
- 30 silly saveTree | +-- graceful-fs@4.2.3
- 30 silly saveTree | +-- mkdirp@0.5.1
- 30 silly saveTree | | `-- minimist@0.0.8
- 30 silly saveTree | `-- rimraf@2.7.1
- 30 silly saveTree |   `-- glob@7.1.6
- 30 silly saveTree |     +-- inflight@1.0.6
- 30 silly saveTree |     | +-- once@1.4.0
- 30 silly saveTree |     | | `-- wrappy@1.0.2
- 30 silly saveTree |     | `-- wrappy@1.0.2
- 30 silly saveTree |     +-- minimatch@3.0.4
- 30 silly saveTree |     +-- once@1.4.0
- 30 silly saveTree |     `-- path-is-absolute@1.0.1
- 30 silly saveTree +-- gauge@2.7.4
- 30 silly saveTree | +-- has-unicode@2.0.1
- 30 silly saveTree | +-- object-assign@4.1.1
- 30 silly saveTree | +-- signal-exit@3.0.2
- 30 silly saveTree | `-- wide-align@1.1.3
- 30 silly saveTree +-- gaze@1.1.3
- 30 silly saveTree | `-- globule@1.2.1
- 30 silly saveTree +-- get-caller-file@1.0.3
- 30 silly saveTree +-- get-stdin@4.0.1
- 30 silly saveTree +-- getpass@0.1.7
- 30 silly saveTree +-- glob@7.1.6
- 30 silly saveTree +-- globals@11.12.0
- 30 silly saveTree +-- globule@1.2.1
- 30 silly saveTree +-- graceful-fs@4.2.3
- 30 silly saveTree +-- har-schema@2.0.0
- 30 silly saveTree +-- har-validator@5.1.3
- 30 silly saveTree +-- has-ansi@2.0.0
- 30 silly saveTree +-- has-flag@3.0.0
- 30 silly saveTree +-- has-unicode@2.0.1
- 30 silly saveTree +-- hoist-non-react-statics@2.5.5
- 30 silly saveTree +-- hosted-git-info@2.8.5
- 30 silly saveTree +-- http-signature@1.2.0
- 30 silly saveTree | +-- jsprim@1.4.1
- 30 silly saveTree | | +-- json-schema@0.2.3
- 30 silly saveTree | | `-- verror@1.10.0
- 30 silly saveTree | `-- sshpk@1.16.1
- 30 silly saveTree +-- immutability-helper@3.0.1
- 30 silly saveTree | `-- invariant@2.2.4
- 30 silly saveTree |   `-- loose-envify@1.4.0
- 30 silly saveTree +-- in-publish@2.0.0
- 30 silly saveTree +-- indent-string@2.1.0
- 30 silly saveTree | `-- repeating@2.0.1
- 30 silly saveTree |   `-- is-finite@1.0.2
- 30 silly saveTree +-- inflight@1.0.6
- 30 silly saveTree +-- inherits@2.0.4
- 30 silly saveTree +-- invariant@2.2.4
- 30 silly saveTree +-- invert-kv@1.0.0
- 30 silly saveTree +-- is-arrayish@0.2.1
- 30 silly saveTree +-- is-finite@1.0.2
- 30 silly saveTree +-- is-fullwidth-code-point@1.0.0
- 30 silly saveTree +-- is-typedarray@1.0.0
- 30 silly saveTree +-- is-utf8@0.2.1
- 30 silly saveTree +-- is-what@3.4.0
- 30 silly saveTree +-- isarray@1.0.0
- 30 silly saveTree +-- isexe@2.0.0
- 30 silly saveTree +-- isstream@0.1.2
- 30 silly saveTree +-- js-base64@2.5.1
- 30 silly saveTree +-- js-tokens@4.0.0
- 30 silly saveTree +-- jsbn@0.1.1
- 30 silly saveTree +-- jsesc@2.5.2
- 30 silly saveTree +-- json-schema-traverse@0.4.1
- 30 silly saveTree +-- json-schema@0.2.3
- 30 silly saveTree +-- json-stringify-safe@5.0.1
- 30 silly saveTree +-- jsprim@1.4.1
- 30 silly saveTree +-- just-curry-it@3.1.0
- 30 silly saveTree +-- lcid@1.0.0
- 30 silly saveTree +-- load-json-file@1.1.0
- 30 silly saveTree | +-- parse-json@2.2.0
- 30 silly saveTree | +-- pify@2.3.0
- 30 silly saveTree | `-- strip-bom@2.0.0
- 30 silly saveTree +-- lodash-es@4.17.15
- 30 silly saveTree +-- lodash.debounce@4.0.8
- 30 silly saveTree +-- lodash.pick@4.4.0
- 30 silly saveTree +-- lodash@4.17.15
- 30 silly saveTree +-- loose-envify@1.4.0
- 30 silly saveTree +-- loud-rejection@1.6.0
- 30 silly saveTree +-- lru-cache@4.1.5
- 30 silly saveTree +-- map-obj@1.0.1
- 30 silly saveTree +-- math-expression-evaluator@1.2.17
- 30 silly saveTree +-- memoize-one@5.1.1
- 30 silly saveTree +-- meow@3.7.0
- 30 silly saveTree | +-- minimist@1.2.0
- 30 silly saveTree | +-- normalize-package-data@2.5.0
- 30 silly saveTree | | +-- resolve@1.13.1
- 30 silly saveTree | | | `-- path-parse@1.0.6
- 30 silly saveTree | | +-- semver@5.7.1
- 30 silly saveTree | | `-- validate-npm-package-license@3.0.4
- 30 silly saveTree | |   +-- spdx-correct@3.1.0
- 30 silly saveTree | |   | +-- spdx-expression-parse@3.0.0
- 30 silly saveTree | |   | | +-- spdx-exceptions@2.2.0
- 30 silly saveTree | |   | | `-- spdx-license-ids@3.0.5
- 30 silly saveTree | |   | `-- spdx-license-ids@3.0.5
- 30 silly saveTree | |   `-- spdx-expression-parse@3.0.0
- 30 silly saveTree | +-- read-pkg-up@1.0.1
- 30 silly saveTree | | `-- read-pkg@1.1.0
- 30 silly saveTree | |   `-- path-type@1.1.0
- 30 silly saveTree | +-- redent@1.0.0
- 30 silly saveTree | | `-- strip-indent@1.0.1
- 30 silly saveTree | `-- trim-newlines@1.0.0
- 30 silly saveTree +-- merge-anything@2.4.4
- 30 silly saveTree +-- mime-db@1.42.0
- 30 silly saveTree +-- mime-types@2.1.25
- 30 silly saveTree +-- minimatch@3.0.4
- 30 silly saveTree +-- minimist@1.2.0
- 30 silly saveTree +-- mkdirp@0.5.1
- 30 silly saveTree +-- ms@2.1.2
- 30 silly saveTree +-- nan@2.14.0
- 30 silly saveTree +-- node-gyp@3.8.0
- 30 silly saveTree | +-- nopt@3.0.6
- 30 silly saveTree | +-- npmlog@4.1.2
- 30 silly saveTree | | `-- set-blocking@2.0.0
- 30 silly saveTree | +-- osenv@0.1.5
- 30 silly saveTree | | +-- os-homedir@1.0.2
- 30 silly saveTree | | `-- os-tmpdir@1.0.2
- 30 silly saveTree | +-- request@2.88.0
- 30 silly saveTree | | +-- oauth-sign@0.9.0
- 30 silly saveTree | | +-- performance-now@2.1.0
- 30 silly saveTree | | +-- qs@6.5.2
- 30 silly saveTree | | +-- tough-cookie@2.4.3
- 30 silly saveTree | | | +-- psl@1.5.0
- 30 silly saveTree | | | `-- punycode@1.4.1
- 30 silly saveTree | | +-- tunnel-agent@0.6.0
- 30 silly saveTree | | `-- uuid@3.3.3
- 30 silly saveTree | +-- semver@5.3.0
- 30 silly saveTree | `-- tar@2.2.2
- 30 silly saveTree +-- node-sass@4.13.0
- 30 silly saveTree | +-- sass-graph@2.2.4
- 30 silly saveTree | | +-- scss-tokenizer@0.2.3
- 30 silly saveTree | | | `-- source-map@0.4.4
- 30 silly saveTree | | `-- yargs@7.1.0
- 30 silly saveTree | |   +-- camelcase@3.0.0
- 30 silly saveTree | |   +-- os-locale@1.4.0
- 30 silly saveTree | |   +-- require-directory@2.1.1
- 30 silly saveTree | |   +-- require-main-filename@1.0.1
- 30 silly saveTree | |   +-- which-module@1.0.0
- 30 silly saveTree | |   +-- y18n@3.2.1
- 30 silly saveTree | |   `-- yargs-parser@5.0.0
- 30 silly saveTree | |     `-- camelcase@3.0.0
- 30 silly saveTree | +-- stdout-stream@1.4.1
- 30 silly saveTree | `-- true-case-path@1.0.3
- 30 silly saveTree +-- nopt@3.0.6
- 30 silly saveTree +-- normalize-package-data@2.5.0
- 30 silly saveTree +-- npmlog@4.1.2
- 30 silly saveTree +-- number-is-nan@1.0.1
- 30 silly saveTree +-- oauth-sign@0.9.0
- 30 silly saveTree +-- object-assign@4.1.1
- 30 silly saveTree +-- once@1.4.0
- 30 silly saveTree +-- os-homedir@1.0.2
- 30 silly saveTree +-- os-locale@1.4.0
- 30 silly saveTree +-- os-tmpdir@1.0.2
- 30 silly saveTree +-- osenv@0.1.5
- 30 silly saveTree +-- parse-json@2.2.0
- 30 silly saveTree +-- path-exists@2.1.0
- 30 silly saveTree +-- path-is-absolute@1.0.1
- 30 silly saveTree +-- path-parse@1.0.6
- 30 silly saveTree +-- path-type@1.1.0
- 30 silly saveTree +-- performance-now@2.1.0
- 30 silly saveTree +-- pify@2.3.0
- 30 silly saveTree +-- pinkie-promise@2.0.1
- 30 silly saveTree +-- pinkie@2.0.4
- 30 silly saveTree +-- postcss-value-parser@3.3.1
- 30 silly saveTree +-- process-nextick-args@2.0.1
- 30 silly saveTree +-- prop-types@15.7.2
- 30 silly saveTree | `-- react-is@16.12.0
- 30 silly saveTree +-- pseudomap@1.0.2
- 30 silly saveTree +-- psl@1.5.0
- 30 silly saveTree +-- punycode@2.1.1
- 30 silly saveTree +-- qs@6.5.2
- 30 silly saveTree +-- raf-schd@4.0.2
- 30 silly saveTree +-- raf@3.4.1
- 30 silly saveTree +-- react-click-outside@3.0.1
- 30 silly saveTree +-- react-clientside-effect@1.2.2
- 30 silly saveTree +-- react-dom@16.12.0
- 30 silly saveTree | `-- scheduler@0.18.0
- 30 silly saveTree +-- react-focus-lock@2.2.1
- 30 silly saveTree | +-- use-callback-ref@1.2.1
- 30 silly saveTree | `-- use-sidecar@1.0.2
- 30 silly saveTree |   `-- tslib@1.10.0
- 30 silly saveTree +-- react-is@16.12.0
- 30 silly saveTree +-- react-lifecycles-compat@3.0.4
- 30 silly saveTree +-- react-popopo@2.1.9
- 30 silly saveTree | +-- react@16.12.0
- 30 silly saveTree | `-- styled-components@4.4.1
- 30 silly saveTree |   +-- stylis-rule-sheet@0.0.10
- 30 silly saveTree |   +-- stylis@3.5.4
- 30 silly saveTree |   `-- supports-color@5.5.0
- 30 silly saveTree +-- react-redux@7.1.3
- 30 silly saveTree | `-- hoist-non-react-statics@3.3.1
- 30 silly saveTree +-- react-resize-detector@4.2.1
- 30 silly saveTree | `-- resize-observer-polyfill@1.5.1
- 30 silly saveTree +-- react-smooth-dnd@0.11.1
- 30 silly saveTree | `-- smooth-dnd@0.12.1
- 30 silly saveTree +-- react-smooth@1.0.5
- 30 silly saveTree | `-- react-transition-group@2.9.0
- 30 silly saveTree +-- react-transition-group@2.9.0
- 30 silly saveTree +-- react-trello@2.2.3
- 30 silly saveTree | +-- autosize@4.0.2
- 30 silly saveTree | +-- immutability-helper@2.9.1
- 30 silly saveTree | +-- react-redux@5.1.2
- 30 silly saveTree | +-- redux-actions@2.6.5
- 30 silly saveTree | | +-- reduce-reducers@0.4.3
- 30 silly saveTree | | `-- to-camel-case@1.0.0
- 30 silly saveTree | |   `-- to-space-case@1.0.0
- 30 silly saveTree | |     `-- to-no-case@1.0.2
- 30 silly saveTree | +-- redux-logger@3.0.6
- 30 silly saveTree | `-- redux@4.0.4
- 30 silly saveTree |   `-- symbol-observable@1.2.0
- 30 silly saveTree +-- react-window-size@1.2.2
- 30 silly saveTree +-- react@16.12.0
- 30 silly saveTree +-- reactour@1.15.5
- 30 silly saveTree | +-- scroll-smooth@1.1.0
- 30 silly saveTree | `-- scrollparent@2.0.1
- 30 silly saveTree +-- read-pkg-up@1.0.1
- 30 silly saveTree +-- read-pkg@1.1.0
- 30 silly saveTree +-- readable-stream@2.3.6
- 30 silly saveTree +-- recharts-scale@0.4.3
- 30 silly saveTree +-- recharts@2.0.0-beta.1
- 30 silly saveTree | +-- core-js@3.4.7
- 30 silly saveTree | `-- reduce-css-calc@1.3.0
- 30 silly saveTree |   +-- balanced-match@0.4.2
- 30 silly saveTree |   `-- reduce-function-call@1.0.3
- 30 silly saveTree +-- redent@1.0.0
- 30 silly saveTree +-- reduce-css-calc@1.3.0
- 30 silly saveTree +-- reduce-function-call@1.0.3
- 30 silly saveTree +-- reduce-reducers@0.4.3
- 30 silly saveTree +-- redux-actions@2.6.5
- 30 silly saveTree +-- redux-logger@3.0.6
- 30 silly saveTree +-- redux@4.0.4
- 30 silly saveTree +-- regenerator-runtime@0.13.3
- 30 silly saveTree +-- repeating@2.0.1
- 30 silly saveTree +-- request@2.88.0
- 30 silly saveTree +-- require-directory@2.1.1
- 30 silly saveTree +-- require-main-filename@1.0.1
- 30 silly saveTree +-- resize-observer-polyfill@1.5.1
- 30 silly saveTree +-- resolve@1.13.1
- 30 silly saveTree +-- rimraf@2.7.1
- 30 silly saveTree +-- safe-buffer@5.1.2
- 30 silly saveTree +-- safer-buffer@2.1.2
- 30 silly saveTree +-- sass-graph@2.2.4
- 30 silly saveTree +-- scheduler@0.18.0
- 30 silly saveTree +-- scroll-smooth@1.1.0
- 30 silly saveTree +-- scrollparent@2.0.1
- 30 silly saveTree +-- scss-tokenizer@0.2.3
- 30 silly saveTree +-- semver@5.7.1
- 30 silly saveTree +-- set-blocking@2.0.0
- 30 silly saveTree +-- signal-exit@3.0.2
- 30 silly saveTree +-- slick-carousel@1.8.1
- 30 silly saveTree +-- smooth-dnd@0.12.1
- 30 silly saveTree +-- source-map@0.4.4
- 30 silly saveTree +-- spdx-correct@3.1.0
- 30 silly saveTree +-- spdx-exceptions@2.2.0
- 30 silly saveTree +-- spdx-expression-parse@3.0.0
- 30 silly saveTree +-- spdx-license-ids@3.0.5
- 30 silly saveTree +-- sshpk@1.16.1
- 30 silly saveTree +-- stdout-stream@1.4.1
- 30 silly saveTree +-- string_decoder@1.1.1
- 30 silly saveTree +-- string-width@1.0.2
- 30 silly saveTree +-- strip-ansi@3.0.1
- 30 silly saveTree +-- strip-bom@2.0.0
- 30 silly saveTree +-- strip-indent@1.0.1
- 30 silly saveTree +-- styled-components@4.4.1
- 30 silly saveTree +-- stylis-rule-sheet@0.0.10
- 30 silly saveTree +-- stylis@3.5.4
- 30 silly saveTree +-- supports-color@2.0.0
- 30 silly saveTree +-- sweetalert2-react-content@2.0.2
- 30 silly saveTree +-- symbol-observable@1.2.0
- 30 silly saveTree +-- tar@2.2.2
- 30 silly saveTree +-- to-camel-case@1.0.0
- 30 silly saveTree +-- to-fast-properties@2.0.0
- 30 silly saveTree +-- to-no-case@1.0.2
- 30 silly saveTree +-- to-space-case@1.0.0
- 30 silly saveTree +-- tough-cookie@2.4.3
- 30 silly saveTree +-- trim-newlines@1.0.0
- 30 silly saveTree +-- true-case-path@1.0.3
- 30 silly saveTree +-- tslib@1.10.0
- 30 silly saveTree +-- tunnel-agent@0.6.0
- 30 silly saveTree +-- tweetnacl@0.14.5
- 30 silly saveTree +-- uri-js@4.2.2
- 30 silly saveTree +-- use-callback-ref@1.2.1
- 30 silly saveTree +-- use-sidecar@1.0.2
- 30 silly saveTree +-- util-deprecate@1.0.2
- 30 silly saveTree +-- uuid@3.3.3
- 30 silly saveTree +-- validate-npm-package-license@3.0.4
- 30 silly saveTree +-- validator@12.1.0
- 30 silly saveTree +-- verror@1.10.0
- 30 silly saveTree +-- which-module@1.0.0
- 30 silly saveTree +-- which@1.3.1
- 30 silly saveTree +-- wide-align@1.1.3
- 30 silly saveTree +-- wrap-ansi@2.1.0
- 30 silly saveTree +-- wrappy@1.0.2
- 30 silly saveTree +-- y18n@3.2.1
- 30 silly saveTree +-- yallist@2.1.2
- 30 silly saveTree +-- yargs-parser@5.0.0
- 30 silly saveTree `-- yargs@7.1.0
- 31 verbose stack Error: spawn git ENOENT
- 31 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
- 31 verbose stack     at onErrorNT (internal/child_process.js:456:16)
- 31 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
- 32 verbose cwd E:\React\able-pro\React\Template
- 33 verbose Windows_NT 10.0.18362
- 34 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "react-trello"
- 35 verbose node v12.13.0
- 36 verbose npm  v6.12.0
- 37 error code ENOENT
- 38 error syscall spawn git
- 39 error path git
- 40 error errno ENOENT
- 41 error enoent Error while executing:
- 41 error enoent undefined ls-remote -h -t https://github.com/rcdexta/smooth-dnd.git
- 41 error enoent
- 41 error enoent
- 41 error enoent spawn git ENOENT
- 42 error enoent This is related to npm not being able to find a file.
- 43 verbose exit [ 1, true ]

`

**Comment by dapi** [comment]
@rcdexta I propose to publicise this dependency as npm-module with name `rcdexta-smooth-dnd` or so

**Comment by dapi** [comment]
same issue - https://github.com/rcdexta/react-trello/issues/317

**Comment by rcdexta** [comment]
@dapi I remember forking out of smooth-dnd as there were some bugs that were causing us issues with drag-n-drop. Let me check if that has been resolved, else will follow your suggestion and publish it as an independent library and refer it here..

Again thanks for all the hard work! :)

**Comment by alexandrakollarova** [comment]
hey @rcdexta :), I'm using your react-trello - amazing functioning trello board btw! However, I'm  also having the issue with dragging/dropping cards, so when you do you get numerous errors that look like this: 

[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

Have you guys figured out what to do? Is that a version thing because in react-trello you define smooth-dnd to a git repo so I don't even know what version it is.. 

Anyways, if you can let me know that would be awesome - thanks!!

**Comment by AndysonDK** [comment]
Having the same issue.

When running the following command in command prompt in windows 10:
`npm i react-trello`

I'm receiving the following errors:

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/rcdexta/smooth-dnd.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Anders\AppData\Roaming\npm-cache\_logs\2020-03-03T20_42_45_576Z-debug.log

**Comment by rcdexta** [comment]
This should be fixed now. Pls pull latest version
