### ISSUE TITLE
Pass laneId when clicking in a card

### ISSUE THREAD

**Issue by vctormb** [rcdexta/react-trello#34]
Currently, when we click on a card, the onCardClick() function is passing only the cardId. Is it possible to pass the laneId too (or maybe the entire card object)? It gonna be better to find the card inside the lane or receive all the data from the card.

For example: When I click on a card, I want to open a modal with details about the card. It will be more easy to get the card inside the lane that I want passing the laneId too.

Example: (cardId, metadata, **laneId**) => alert(laneId) **or** (cardObject) => alert(cardObject)

I created a PR for this.

**Comment by rcdexta** [comment]
Thanks for the PR. Merged and released. Please fetch v1.23.1
