### ISSUE TITLE
Custom Lane Header with editable title does not work

### ISSUE THREAD

**Issue by tanmay-keystride** [rcdexta/react-trello#349]
I am using a custom lane header component which seems to work fine, except when I am trying to update the title through the custom input box blur event. 
On blur it still retains the original title and does not reflect the new title that has been typed by the user.

Please help if this works for someone already.
I couldnt find any example.

**Comment by MukeshNegi-brillmark** [comment]
@tanmay-keystride Me 2 facing the same issue So I went through their storybook and find out they have not written any code to handle `editLaneTitle`  in the repo.

I am in middle of my project and got stuck in this.
Please help if you got out of it.

**Comment by dapi** [comment]
Thank you for reporting! I am digging into it

**Comment by MukeshNegi-brillmark** [comment]
@dapi  I have made it work for me like this is

`const CustomLaneHeader = ({id, label, cards, title, current, target}) => {
  const [laneOpt, setLaneOpt] = useState(false);
  const [editMode, setEditMode] = useState(false);
  const [newValue, setNewValue] = useState(title);
  const [newTitle, updateLaneTitle] = useState('');

  const inputEl = createRef<HTMLInputElement>();

  const buttonHandler = () => {
    setLaneOpt(!laneOpt);
  };

  const titleEditMode = () => {
    setEditMode(!editMode);
  };

  useEffect(() => {
    const node = inputEl.current;
    if (node) {
      node.focus();
    }
  }, [editMode]);

  const handleNewValue = e => {
    setNewValue(e.target.value);
  };

  const handleTitleBlur = () => {
    updateLaneTitle(newValue);
    setEditMode(!editMode);
  };

  const handleLaneDelete = () => {
    alert(`need to delete ${id} and update data using saga`);
  };
  return (
    <div>
      <LaneHeaderWrapper>
        {
          editMode ?
          <input ref={inputEl} className="renameTitle" type="text" value={newValue}
            onChange={e => handleNewValue(e)} onBlur={handleTitleBlur}/>
          :
          <div className="title" onClick={titleEditMode}>
            {newTitle ? newTitle : title}
          </div>
        }
        {!editMode && (
          <Dots onClick={buttonHandler}>
            ...
          </Dots>
        )}
        {
          laneOpt ? (
            <div className="laneOpt">
              <span>View Audience</span>
              <span>Rename Column</span>
              <span style={{color: '#FF7D5E'}} onClick={handleLaneDelete}>Delete Column</span>
            </div>
          ) : null
        }
      </LaneHeaderWrapper>
    </div>
  );
};

export default CustomLaneHeader;`

is It Okay to do it like this

**Comment by dapi** [comment]
@tanmay-keystride fixes in master branch. Could you checkout and confirm?

**Comment by tanmay-keystride** [comment]
I am using react-trello as npm module, so how can i get all the updated master changes in my npm react-trello package?

**Comment by rcdexta** [comment]
This should be fixed in v2.2.5. Pls reopen issue otherwise
