### ISSUE TITLE
Adding draggable property to specific lane

### ISSUE THREAD

**Issue by VBDzzz** [rcdexta/react-trello#351]
Hello!

I want to prevent some lane from dragging.
It would be cool to add **draggable** property similar to the card

Example:
```javascript
const data = {
  lanes: [
    {
      id: 'lane1',
      title: 'Planned Tasks',
      label: '2/2',
      draggable: false,
      cards: [
        {id: 'Card1', title: 'Write Blog', draggable: false},
        {id: 'Card2', title: 'Pay Rent'}
      ]
    },
    {
      id: 'lane2',
      title: 'Completed',
      label: '0/0',
      cards: [
        {id: 'Card3', title: 'Pay Rent 3'}
      ]
    },
    {
      id: 'lane3',
      title: 'Release',
      label: '0/0',
      cards: []
    }
  ]
}
```
In this example, we cannot drag  `lane1`. But we can swap `lane2` and `lane3`

Is there such an opportunity now?

**Comment by dapi** [comment]
You can do it by overriding LaneHeader component. Here is an example - https://github.com/rcdexta/react-trello/blob/e46c8791fbf09021840077e0fc1096288083eaee/stories/CustomLaneHeader.story.js

It already has `laneDraggable` property https://github.com/rcdexta/react-trello/blob/4b2101bf231e804100651977b389a8fc3580e715/src/components/Lane/LaneHeader.js#L13
