### ISSUE TITLE
Getting errors on each drag and drop using react-trello/smooth-dnd

### ISSUE THREAD

**Issue by alexandrakollarova** [rcdexta/react-trello#354]
**Describe the bug**
I'm having an issue with dragging/dropping cards, so when you do you get numerous errors that look like this:

[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

**To Reproduce**
Drag and drop trello cards on mobile and see your console.. https://visbo.now.sh

**Expected behavior**
Error free

**Screenshots**
![Screenshot (80)](https://user-images.githubusercontent.com/44532237/75121814-aa798e00-5665-11ea-89fd-d0052e3c29b3.png)

**Comment by alexandrakollarova** [comment]
![Screenshot (80)](https://user-images.githubusercontent.com/44532237/75121839-f4fb0a80-5665-11ea-8a91-0b5e75d4f51c.png)

**Comment by alexandrakollarova** [comment]
@rcdexta

**Comment by rcdexta** [comment]
Should be addressed in https://github.com/rcdexta/react-trello/pull/357

**Comment by rcdexta** [comment]
This should be addressed now in v2.2.4. Can you check pls

**Comment by alexandrakollarova** [comment]
v2.2.4 Failed to compile @rcdexta 
node_modules\react-trello\src\components\AddCardLink.js: Unexpected token (4:35)

  2 | import AddCardLink from 'rt/styles/Base'
  3 | 
> 4 | export default ({ onClick, t }) => <AddCardLink onClick={onClick}>{t('Click to add card')}</AddCardLink>
    |                                    ^
  5 |

**Comment by oplengs001** [comment]
> v2.2.4 Failed to compile @rcdexta
> node_modules\react-trello\src\components\AddCardLink.js: Unexpected token (4:35)
> 
> 2 | import AddCardLink from 'rt/styles/Base'
> 3 |
> 
> > 4 | export default ({ onClick, t }) => {t('Click to add card')}
> > |                                    ^
> > 5 |

any updates?

**Comment by mehuljariwala** [comment]
downgrade the version @oplengs001

**Comment by orlandovallejos** [comment]
Same issue here than @alexandrakollarova

**Comment by iIdiomatic** [comment]
This issue comes while just rendering, and should be marked as bug

**Comment by rcdexta** [comment]
Thanks for your patience. Fixed in V2.2.5
