### ISSUE TITLE
jsnext:main and module values in package.json are incorrect

### ISSUE THREAD

**Issue by jprosevear** [rcdexta/react-trello#359]
jsnext:main and module values in package.json are incorrect and can cause build breakage.  Previously they did not cause a problem because they were pointing to invalid values and essentially not used.

Since both point to modules that require more than ES2015 syntax, I believe the simplest solution is both should be removed then tools like babel/webpack will use dist/ instead which is already transpiled.

Alternately transpile the module file.

https://github.com/jsforum/jsforum/issues/5
https://shuheikagawa.com/blog/2017/01/05/main-jsnext-main-and-module/

**Comment by jprosevear** [comment]
PR #360 for this

**Comment by rcdexta** [comment]
Addressed in v2.2.5
