### ISSUE TITLE
Cannot find module: 'rt/styles/Base'. Make sure this package is installed.

### ISSUE THREAD

**Issue by tanmay-keystride** [rcdexta/react-trello#361]
While deploying the project on Netlify I am facing this issue because the internal components refer to each other using "rt" instead of "react-trello"

**Comment by luizfilipefc-sp** [comment]
It seems that you're using it in a different way, I got the same problem but I was calling the import wrongly, the correct statement should be `import Board from 'react-trello'`

**Comment by jprosevear** [comment]
This is a duplicate of #359

**Comment by rcdexta** [comment]
Closed in https://github.com/rcdexta/react-trello/releases/tag/v2.2.5 Thanks for the comments @jprosevear
