### ISSUE TITLE
Auto generating Classes

### ISSUE THREAD

**Issue by jlbmagic** [rcdexta/react-trello#364]
Questions about the classNames that are generated.

I need to ensure that the class name that is generated during runtime be the same all the time. 
I'm dealing with the IE11 issue, and in another [post](https://github.com/rcdexta/react-trello/issues/320), the className generated as `rXSjd`, but in my version it has changed to `fYZyZu`.

Am I correct that the string will change? if so, I need to assign that exact div with a hard-coded class so that I can ensure the style   `flex-basis: auto !important;` is always applied.

So:
![2020-03-23_14-11-32](https://user-images.githubusercontent.com/20194907/77354196-c5005f00-6d18-11ea-8710-58f14b771d7b.png)

1. that class name will be atuo-generated and changed? Yes?
2. where's the code that auto-generates this class? I need to somehow override it to always assign a class of my chosing.
3. Alternatively: how can I target the div in question to make sure that the flex-basis style gets added all the time?

Thanks

**Comment by rcdexta** [comment]
@jlbmagic this library uses [styled-components](https://styled-components.com/) for managing CSS styling using JS. So, the class names would be generated dynamically during build time and it is definitely going to change from one release to another. Please do not use the generated classes to customize the styling of the components.

Please refer to https://github.com/rcdexta/react-trello#style-customization and https://github.com/rcdexta/react-trello#styling-and-customization sections to see if they can help with your requirement. Else revert back with what exactly on the board you would like to customize and we can help with a corresponding binding for that

**Comment by jlbmagic** [comment]
Hello @rcdexta  and thanks for the information. I didn't receive notification on this. 
FOr what it's worth, I tracked down the templateObject that generates the lanes (_templateObject11() in react-trello/dist/styles/Base.js (line 199) ) and added this to the styles there:
\n flex-basis:auto !important

That seems to work.
