### ISSUE TITLE
Unable to run the application

### ISSUE THREAD

**Issue by sravanithamatamqualbrain** [rcdexta/react-trello#370]
Hi Team,

I am unable to run the application, when i run command "npm start" i am getting some error saying that "start" is not found. 

I checked for "start" attribute in packages.json file, but it doesn't exist.

Please provide me the steps to run the application.

I run the command i.e, "npm install --save react-trello", this command is executed successfully. 
But unable to run the apllication.

Thank you
Sravani Thamatam

**Comment by rcdexta** [comment]
@sravanithamatamqualbrain adding this library to your codebase does not add any npm scripts. Please refer to https://github.com/rcdexta/react-trello-example for sample usage. You have to refer to the scripts section of your `package.json` for more details about the `start` command
