### ISSUE TITLE
Unversioned dependency on `react-outclick` points to github master

### ISSUE THREAD

**Issue by styfle** [rcdexta/react-trello#377]
**Is your feature request related to a problem? Please describe.**
One of the dependencies, `react-click-outside`, is using git instead of npm and does not follow semver, its linked to the master branch.

https://github.com/rcdexta/react-trello/blob/8fbde5c57aa1c5ab63bb3aab39a07b8acec617a4/package.json#L46

**Describe the solution you'd like**
Consider using `react-outclick` instead like this message suggests https://github.com/tj/react-click-outside/issues/10#issuecomment-335558252

**Describe alternatives you've considered**
- Publish `react-click-outside` to npm as-is and depend on that.
- Specify a git tag but it is outdated and still depends on git.

**Additional context**
https://github.com/tj/react-click-outside/issues/10

**Comment by pbrink231** [comment]
having the same problem

![image](https://user-images.githubusercontent.com/8224560/82135837-23a3ff80-97d5-11ea-9bdc-fa6911bccbf9.png)

**Comment by rcdexta** [comment]
should be fixed in latest release

**Comment by styfle** [comment]
Wow that was quick, thanks!

Now I'm able to see the install size 😎

https://packagephobia.now.sh/result?p=react-trello@2.2.6
