### ISSUE TITLE
One Lane with two columns

### ISSUE THREAD

**Issue by vinpereira** [rcdexta/react-trello#384]
First, I know this is not a Trello feature.

I would like to create a Lane with two columns (like In Progress and Done). The tricky here is that the Limit WIP is share between the columns.

![image](https://user-images.githubusercontent.com/329623/85064234-a37d0b00-b181-11ea-9233-2a86b39d6efa.png)

Is it possible?

**Comment by rcdexta** [comment]
@vinpereira You can customize the lanes and cards as you want here by following the steps here: https://github.com/rcdexta/react-trello#3-completely-customize-the-look-and-feel-by-using-components-dependency-injection
