### ISSUE TITLE
laneStyle prop has no effect

### ISSUE THREAD

**Issue by ivanjeremic** [rcdexta/react-trello#385]
laneStyle has no effect what is wrong with the prop?

````
<Board
      laneStyle={{
        background: "green",
        height: "100vh",
        maxHeight: "100%"
      }}
      data={data}
      draggable
      laneDraggable
      cardStyle={{ background: "red" }}
    />
```

**Comment by rcdexta** [comment]
I see the `laneStyle` prop working correctly for your code as seen here: https://codesandbox.io/s/blue-water-wxfnb?file=/src/App.js

**Comment by ivanjeremic** [comment]
> I see the `laneStyle` prop working correctly for your code as seen here: https://codesandbox.io/s/blue-water-wxfnb?file=/src/App.js

Yes but only on Create-React-App not NextJS
