### ISSUE TITLE
Allow tag title to be a react element not only a string

### ISSUE THREAD

**Issue by groupespc69** [rcdexta/react-trello#386]
The goal is to be able to add buttons in the footer like this

        lanes: [
            {
                id: 'L01', title: 'Started', label: '1/1', cards: [
                    {
                        id: '4', title: 'My task', description: 'My task description', label: 'MyTask', tags: [
                            {
                                title: <IconButton aria-label="comment" size="small" onClick={e => handleCommentClick(e, 4)}><ChatBubbleOutlineIcon /></IconButton>, bgcolor: 'transparent'
                            },
                        ]
                    },

                ]
            },
        ]
    });

It is possible so far to put React Elements in this field but it triggers a prop-types warning.

I suppose that something like this will do the trick :

Tag.propTypes = {
  title: PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.element,
  ]).isRequired,
  color: PropTypes.string,
  bgcolor: PropTypes.string,
  tagStyle: PropTypes.object
}

**Comment by rcdexta** [comment]
@groupespc69 Though the feature request looks appealing, we consciously decided to keep json strictly data only and without definitions.

For you need, you should look at this https://github.com/rcdexta/react-trello#3-completely-customize-the-look-and-feel-by-using-components-dependency-injection
