### ISSUE TITLE
publish event 'UPDATE_CARD' is not updating the custom card states

### ISSUE THREAD

**Issue by uday-bhardwaj** [rcdexta/react-trello#387]
**Describe the bug**
publishing the event 'UPDATE_CARD' from a lifecycle method in custom card component is not behaving properly. It's not updating the card state/props and thus not updating the UI.

**To Reproduce**
this.props.tagStyle.eventBus.publish({type: 'UPDATE_CARD', laneId: 3, card: {id: this.props.id, properties:response.properties}})

Though 'MOVE_CARD' event is published successfully from my custom card.

**Expected behavior**
This should update the card states/props (properties props) and thus re-render the card

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chrome]
 - Version [83]

**Comment by ACronje** [comment]
I see that the 'UPDATE_CARD'` event is not available in 2.2.6. So the README is a little deceiving.

@rcdexta any chance we can have a release tomorrow that includes this new event? 😋

**Comment by rcdexta** [comment]
https://github.com/rcdexta/react-trello/releases/tag/v2.2.7 published today
