### ISSUE TITLE
Storybook dead

### ISSUE THREAD

**Issue by Mistes974** [rcdexta/react-trello#408]
Hi, 
The storybook for detailed examples is dead https://rcdexta.com/react-trello/

**Comment by patcon** [comment]
Tried spinning it up locally, and it's not working locally either.

If maintainer knows a date on which it definitely worked, I can prob trace back, so pls do feel free to share! Thanks!

**Comment by patcon** [comment]
Ah, found my same issue here: https://github.com/rcdexta/react-trello/issues/309#issuecomment-519140327 (with resolution)

**Comment by patcon** [comment]
Fixed for now, for anyone curious to explore: 
https://fix-storybook--5fa1bc874bc37200228d96ca.chromatic.com/

**Comment by rcdexta** [comment]
Had some issues with the domain and should be resolved now. Thanks for reporting @Mistes974
