### ISSUE TITLE
Manage Position on 1 Lane

### ISSUE THREAD

**Issue by Thangdkpro** [rcdexta/react-trello#41]
After I adjust position and send to API to save. But when i reload it, it gone. How can i get property position to save string index. and save it.
Help me plz !!! Tks all guys

**Comment by hoangphuc127** [comment]
same issue!!

**Comment by rcdexta** [comment]
If you listen to `onDataChange` prop, the callback should give you the updated board data which should contain the cards in the new order after changing position.

Let me know if that works. What are you specifically using to track the position of a card? That will give me more details to assist you better.

**Comment by rcdexta** [comment]
@Thangdkpro and @hoangphuc127 Please revert back in case you are not able to solve this! Closing this issue for now. Feel free to reopen it later, if needed!
