### ISSUE TITLE
Add and Delete Button

### ISSUE THREAD

**Issue by hoangphuc127** [rcdexta/react-trello#42]
Do this library have Add and delete button for card and lane like real Trello? If have, pls let me know how to using it? Tks

**Comment by rcdexta** [comment]
Right now there are no add and delete buttons for card. Delete should be easy to do. But Add might lead to invoking a form containing fields to create a card. Will keep you posted on both the features on this thread!

**Comment by rcdexta** [comment]
The latest release includes changes to add or delete cards within a lane.
![dec-24-2017 21-22-06](https://user-images.githubusercontent.com/900028/34327676-bd7713fe-e8f0-11e7-905f-843d1c8fd57f.gif)

Check this [story](https://rcdexta.github.io/react-trello/?selectedKind=Editable%20Board&selectedStory=Add%2FDelete%20Cards&full=0&down=0&left=1&panelRight=0) for example. All starts with setting the `editable` board prop to true.

**Comment by buddythumbs** [comment]
Hi - Thanks for your work! Just wondering if it is possible to add custom component to the delete button? It fits well with standard setup but my styling is using material-ui components and I would like to change the delete button (or actually remove it - so I could have a popup show info on click)

![image](https://user-images.githubusercontent.com/24975408/35304821-da6b44c0-008e-11e8-9653-a69ae8b9a339.png)


Any idea??

Cheers,

M

**Comment by rcdexta** [comment]
@buddythumbs Opened a new issue to track customizable delete buttons!
