### ISSUE TITLE
number label does not change

### ISSUE THREAD

**Issue by KnowsCount** [rcdexta/react-trello#420]
**Describe the bug**
I followed `readme.md` and created a file with content below

```js
import React from 'react'
import Board from 'react-trello'
import './App.css'

export default class App extends React.Component {
	render() {
		return <Board data={data} class='board' />
	}
}
const data = {
	lanes: [
		{
			id: 'lane1',
			title: 'To-do',
			label: '2/2',
			cards: [
				{
					id: 'Card1',
					title: 'Write Blog',
					description: 'Can AI make memes',
					label: '30 mins',
					draggable: true,
				},
				{
					id: 'Card2',
					title: 'Pay Rent',
					description: 'Transfer via NEFT',
					label: '5 mins',
					metadata: { sha: 'be312a1' },
				},
			],
		},
		{
			id: 'lane2',
			title: 'Completed',
			label: '0/0',
			cards: [],
		},
	],
}
```

When I give it a label `'0/0'` or `'2/2'`, it works, however, when I drag a card from lane 1 to lane 2, the number in lane 2 is still `0/0`, likewise, the number in lane 1 is still `2/2`. 

This would most certainly happen.. I used label to define it. But can I achieve **Expected Behaviour** in some way?

**To Reproduce**
1. Create `foo.js`
2. Write in code provided above
3. `yarn start`
4. drag cards
5. see error

**Expected behaviour**
The numbers are expected to change into `1/2` and `1/0` or something (this is a bad expectation..)

**Screenshots**
![screenshot1](https://knowscount-1304485449.cos.ap-shanghai.myqcloud.com/img/Screenshot%202020-12-24%20at%2010.03.13.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari 
 - Version: 14.0

**Additional context**
Nah.. probably my problem.

**Comment by KnowsCount** [comment]
speaking of which why is four-spaced tab so large on GitHub??

**Comment by dfibuch** [comment]
Not sure if this will help you, looks like it's been a while but I've started using this library recently and wanted my labels to update when I moved cards around and used the `onDataChange` callback with the `eventBus` to make it happen

For reference, `boardData` is my `{ lanes: [] }` object that I pass to `<Board data={boardData} />`
``` ts
  const onDataChange = useCallback(( newData: any ) => {
   // Checking if any data changed, otherwise do nothing
   // Also helps with the scenario when data is first loaded from the server and eventBus is not init yet
    if (JSON.stringify(boardData) === JSON.stringify(newData))
    {
      return;
    }

   // Iterate through each lane and count the cards, then set it back in the object
    newData.lanes.forEach((lane : any) => {
      lane.label = `${lane.cards.length}`;
    });

   // Pass the new lane data to the eventBus
    eventBus.publish({ type: "UPDATE_LANES", lanes: newData.lanes });
  },[boardData, eventBus]);
```

**Comment by KnowsCount** [comment]
> Not sure if this will help you, looks like it's been a while but I've started using this library recently and wanted my labels to update when I moved cards around and used the `onDataChange` callback with the `eventBus` to make it happen
> 
> For reference, `boardData` is my `{ lanes: [] }` object that I pass to `<Board data={boardData} />`
> 
> ```ts
>   const onDataChange = useCallback(( newData: any ) => {
>    // Checking if any data changed, otherwise do nothing
>    // Also helps with the scenario when data is first loaded from the server and eventBus is not init yet
>     if (JSON.stringify(boardData) === JSON.stringify(newData))
>     {
>       return;
>     }
> 
>    // Iterate through each lane and count the cards, then set it back in the object
>     newData.lanes.forEach((lane : any) => {
>       lane.label = `${lane.cards.length}`;
>     });
> 
>    // Pass the new lane data to the eventBus
>     eventBus.publish({ type: "UPDATE_LANES", lanes: newData.lanes });
>   },[boardData, eventBus]);
> ```

Thanks for responding—really appreciate it! I vaguely remember figuring something out in the end back then but I cannot recall how—it has, as you said, been a while. It is quite negligent of me to not post the solution nor close this issue though... as you have provided a useful solution and I myself one a while back, I believe this issue can be closed.

Thanks again!
