### ISSUE TITLE
Issue with Lane Pagination due to micro difference between scrollTop and scrollHeight.

### ISSUE THREAD

**Issue by deve-sh** [rcdexta/react-trello#422]
https://github.com/rcdexta/react-trello/blob/58d539638ab0d3da950589ab30532c9343839819/src/controllers/Lane.js#L27

Hey There, thanks for the brilliant library, it's very useful. I have an issue with the lane pagination. The issue isn't directly reproducable but is noticeable at certain times due to screen size differences and the ways in which the lane scroll container is styled.

It is noticeable in certain scenarios that `scrollHeight` or `scrollTop` are off by a margin of less than 1px, for example: Instead of 692px they will be 691.45555555px. The `elemScrollPosition` variable might be greater than 0 in some cases due to that even though the user has scrolled all the way down and is expecting more cards to load.

Suggest using something like `Math.floor` or `Math.ceil` in combination with `node.offsetHeight` to counter that issue.

**Comment by oliviervanbulck** [comment]
I believe I have the same problem. My lanes are having a dynamic height based on the window height. On my laptop screen it's not workingat all, on my second screen everything works perfectly.

**Comment by oliviervanbulck** [comment]
I added a pull request for this by changing the check to maximum 1. That should work.

**Comment by deve-sh** [comment]
Thank you so much. Hoping for the issue to be resolved in the next release.

**Comment by deve-sh** [comment]
Closing this issue since this has already been fixed with the mentioned PR long ago. #431
