### ISSUE TITLE
Different color to each cards

### ISSUE THREAD

**Issue by bipindubey-technoark** [rcdexta/react-trello#423]
I want to have a different color to each card based on status so how to implement this

I have following json 
[
{id:1, title:'ABC", description:'ABC", color:'#f23323'},
{id:2, title:'XYZ", description:'ABC", color:'#ffffff'},
] 

Thanks

**Comment by mateomorrison** [comment]
Pass classCard as an object. Currently using my phone, tomorrow morning I'll share the code that worked.

**Comment by bipindubey-technoark** [comment]
> Pass cardStyle as an object. Currently using my phone, tomorrow morning I'll share the code that worked.

ok

**Comment by mateomorrison** [comment]
To pass style to a card do the following per docs:

`
// your data

const data = {
  lanes: [
    {
      id: 'lane1',
      title: 'Planned Tasks',
      style: { backgroundColor: 'yellow' },  // Style of Lane
      cardStyle: { backgroundColor: 'blue' } // Style of Card
      ...
};

// your board

<Board 
  style={{backgroundColor: 'red'}}  // Style of BoardWrapper
  data={data}
  />`

**Comment by bipindubey-technoark** [comment]
Thanks @mateomorrison
