### ISSUE TITLE
Problem card order when drag card between two lanes

### ISSUE THREAD

**Issue by fritzZz** [rcdexta/react-trello#44]
I'm using customCards and when I drag a card from a column A to a column B I can drop my item in any position, but when I leave the item the items is added at the end of the list.
Is this the expected behaviour? I'm the only one with this problem?
thank you!

**Comment by rcdexta** [comment]
Right now due to the limitation of the library being used for drag-n-drop, a new card added to a lane will be added to the end of the lane. I am working on fixing this. Will keep you posted!

**Comment by fritzZz** [comment]
Thank you very much!! Another little problem moving a card to another lane:
If you have custom cards with different heights, when you try to drag and drop in the same lane, the placeholder for the card has the same height of the card you're trying to move (correct). But if you try to move the same card in another lane the height of the placeholder is wrong.

**Comment by fritzZz** [comment]
Do you have any update about this bug? Thank you!

**Comment by rcdexta** [comment]
It's in WiP and should be done by end of this week..

**Comment by rcdexta** [comment]
This is addressed in the latest release. @fritzZz please test from your side and let know if things look good! Thanks

**Comment by fritzZz** [comment]
It works better for the first part : move a card to another lane in a specific order
But I've 2 different little problems : 
- when there are more than N cards in a single lane and the scrollbar appears, the scrollbar overlaps the right side of the card. (https://drive.google.com/file/d/1qWlJzSIPHtKEddM63kpMbwpkn7NzRWcw/view?usp=sharing)
- the placeholder (dark) has disappeared : when you want to drop in the same or another lane the shift to create the right space for the cards seems to work fine, but there is no placeholder.

**Comment by changyu72** [comment]
![2018-05-06_12-43-51](https://user-images.githubusercontent.com/18181509/39669909-4a427650-512b-11e8-9874-beefb2847480.gif)
