### ISSUE TITLE
Add a card button

### ISSUE THREAD

**Issue by hgbink** [rcdexta/react-trello#45]
Do you have plan to implement the "Add a  card" button on the bottom of the lane like Trello?

**Comment by asveloper** [comment]
@hgbink you can use our package here https://www.npmjs.com/package/@mobylogix/react-trello

Cheers!

**Comment by rcdexta** [comment]
@hgbink Added to next milestone. Most probably will be released this weekend.. Will keep you posted!

**Comment by hgbink** [comment]
Amazing!  Thanks @rcdexta .  Look forward to it.

**Comment by asveloper** [comment]
@hgbink  here you go mate https://www.npmjs.com/package/@mobylogix/react-trello

**Comment by hgbink** [comment]
@asveloper  Do you have an example on how to use it?  And which version are you using?  I tried to use the inputPlaceholder in 1.24.3, but it didn't take any effect.

**Comment by asveloper** [comment]
@hgbink kindly do check the link that is seperate package do install it npm i @mobylogix/react-trello@latest --save

**Comment by hgbink** [comment]
Thanks @asveloper.  
I have tried your version and had a few issues:
1. The lane.css caused some problem with my webpack config.  I solved it by moving it to my app level css.
2. I found a few bug that I don't find in this repository.
3. I tried set inputPlaceholder, but it didn't work for me.  Do you have an example?

Is this a separate version of this repository?  Looks like you have made some progress. Why don't you create a pull request so others can help?

**Comment by rcdexta** [comment]
The latest release includes changes to add or delete cards within a lane.
![dec-24-2017 21-22-06](https://user-images.githubusercontent.com/900028/34327676-bd7713fe-e8f0-11e7-905f-843d1c8fd57f.gif)

Check this [story](https://rcdexta.github.io/react-trello/?selectedKind=Editable%20Board&selectedStory=Add%2FDelete%20Cards&full=0&down=0&left=1&panelRight=0) for example. All starts with setting the `editable` board prop to true.
