### ISSUE TITLE
Using component= {{}} for custom card and header 

### ISSUE THREAD

**Issue by Faayakhun** [rcdexta/react-trello#451]
Hello,I'm new to react,I manage to made kanban using this wonderfull package. But I have one issue,when I'm using components = {{Card: this.customCard}} it erases my components = {{LaneHeader: this.customLaneHeader}} both of them on the same <Board/> callback,is there any way to use custom card and custom header at the same time?.

Thank you for your answer

**Comment by KaiSpencer** [comment]
the components prop expected type is an object containing a list of overrides. In your case, the implementation should be `components = {{Card: this.customCard, LaneHeader: this.customLaneHeader}}`

**Comment by Faayakhun** [comment]
yeah, that works, thanks a lot
