### ISSUE TITLE
onLaneScroll is not getting called, New release can fix this issue

### ISSUE THREAD

**Issue by satya-imaginea** [rcdexta/react-trello#455]
I see fix for this issue in this line - https://github.com/rcdexta/react-trello/blob/c4a59657f644ea39303e2f9aeac82ee6cc2724a9/src/controllers/Lane.js#L30,
 
 Would you please release new package?
 
 @rcdexta @dapi @oliviervanbulck @yashutanna

**Comment by rcdexta** [comment]
pls pull v2.2.11
