### ISSUE TITLE
OnClick "delete card" : stop propagation

### ISSUE THREAD

**Issue by julienpillias** [rcdexta/react-trello#46]
Hi,

First, thank you for your work ! Helps a lot 👍 

I'm using your new feature "editable" board, wich works well.

Just one problem, I'm using "onCardClick" to display a popin with more informations about the card. 
When I click on the delete button, the onCardClick is triggered too. 

Since their is no "onCardDelete", we can not overwrite this. Could you change it, so onCardClick is not triggered anymore ?

Best regards.

NB : a "onCardAdd" would be great too :)

**Comment by rcdexta** [comment]
> Just one problem, I'm using "onCardClick" to display a popin with more informations about the card.
> When I click on the delete button, the onCardClick is triggered too.
Fixed!

Added `onCardAdd` and `onCardDelete` callback functions
