### ISSUE TITLE
how to save board data after refresh browser?

### ISSUE THREAD

**Issue by yluang** [rcdexta/react-trello#467]
**my code here:** : 
If I add/delete/update a card in the board, after refreshing the browser, the data is get lost. How can i save my data by using local storage or mongoDB?

import React, { Component, useState, useEffect } from "react";
import { withRouter } from "react-router-dom";

import { connect, useSelector } from "react-redux";

//import BoardComponent from "../components/BoardComponent";
import Board from 'react-trello'

/**
 * For register new users
 * @param {props} props
 */

function BoardView() {
  //const [retrievedObject, setRetrievedObject] = useState([]);
  
    const data = {
      lanes: [
      {
        id: 'lane1',
        title: 'To Do',
        cards: [
          {id: 'Card1', title: 'Assignment 1', description: 'Deadline: Sunday, May 2nd.',assignee: 'None', priority:'low ❗', reviewer: 'None', label: '3 Points', draggable: true},
          {id: 'Card2', title: 'Assignment 2', description: 'Deadline: Sunday, May 16th.', assignee: 'None', priority:'low ❗', reviewer: 'None',  label: '5 Points', metadata: {sha: 'be312a1'}},
          {id: 'Card3', title: 'Assignment 3', description: 'Deadline: Sunday, July 25th.', assignee: 'None', priority:'high ❗❗', reviewer: 'None', label: '8 Points', metadata: {sha: 'be312a1'}},
          {id: 'Card4', title: 'Final Exam', description: 'Deadline: Friday, Augusr 6th.',  assignee: 'None', priority:'high ❗❗', reviewer: 'None', label: '8 Points', metadata: {sha: 'be312a1'}}
        ]
      },
      {
        id: 'lane2',
        title: 'In Progress',
        cards: []
     
      },
      {
        id: 'lane3',
        title: 'In Review',
        cards: []
       
      },
      {
        id: 'lane4',
        title: 'Done',
        cards: []
      
      }
    ]
  };

  localStorage.setItem('data', JSON.stringify(data));
  var retrievedObject = localStorage.getItem('data');
  console.log('data: ', JSON.parse(retrievedObject));

    return (
      <Board style = {{backgroundColor: 'grey'}}
      editable
       onDataChange={(newData) => {console.log(newData)}}
       onCardAdd={(card) => {localStorage.setItem('data', JSON.stringify(card));
                         var retrievedObject = localStorage.getItem('data');
                         console.log(retrievedObject)}}
                         cardDraggable
                         draggable
                         data={JSON.parse(retrievedObject)}
                         collapsibleLanes
                         />                    
    );
  
}

export default connect()(withRouter(BoardView));

**Comment by Yongli-Huang** [comment]
Thanks.
