### ISSUE TITLE
Give possibility to change text "Add card"

### ISSUE THREAD

**Issue by julienpillias** [rcdexta/react-trello#47]
Hi,

Would be great if we can change the text "Add card". 

I think the best solution would be to add a "text" entrie in the json lane definition.

Best regards

**Comment by rcdexta** [comment]
You mean make the “Add Card” link label customisable? To say `New Card` for example?

**Comment by julienpillias** [comment]
Yes this it :)

**Comment by rcdexta** [comment]
Check out the `addCardLink` prop for overriding the appearance of Add Card.

Example: https://rcdexta.github.io/react-trello/?selectedKind=Editable%20Board&selectedStory=Customizations&full=0&down=0&left=1&panelRight=0

**Comment by julienpillias** [comment]
Thank's for this update.

I've just tried, and the addCardLin does not work. No errors ! 
At the same time, onCardAdd and onCardDelete works fine.

My code : 

```
<Board
            editable={true}
            tagStyle={{fontSize: '70%'}}
            onCardClick={(cardId, metadata, laneId) => this.openEditCard(cardId)}
            onCardAdd={(card, laneId)=>this.addCard(card, laneId)}
            onCardDelete={(cardId, laneId)=>this.askDeleteCard(cardId, laneId)}
            customCardLayout
            data={data}
            addCardLink={<button />}
          >
            <CustomCard/>
</Board>
```

**Comment by rcdexta** [comment]
That's weird.. Ok checking..

**Comment by rcdexta** [comment]
Can you please try again with v1.25.3. Should work!

**Comment by julienpillias** [comment]
Work's fine 👍 
Thank's
