### ISSUE TITLE
Translation Kanban to PT-BR

### ISSUE THREAD

**Issue by mateusbays** [rcdexta/react-trello#470]
Hello everyone,
I want to improve the react-trello. Translating this for PT-BR.

Release description:
Translating the words to PT-BR.

**Comment by mateusbays** [comment]
May i be a contributor?

**Comment by wallace-sf** [comment]
You can contribute. Go ahead.

**Comment by rubensflinco** [comment]
https://github.com/rcdexta/react-trello/pull/524
