### ISSUE TITLE
Give possibility to have a customAddCardLayout

### ISSUE THREAD

**Issue by julienpillias** [rcdexta/react-trello#48]
Hi again :)

Would be great to have a customAddCardLayout, working the same way as customCardLayout.

**Comment by rcdexta** [comment]
Yes this is on the roadmap for the next milestone. We will track and close it here when done.

**Comment by julienpillias** [comment]
Great thank you

**Comment by julienpillias** [comment]
Hi,

Should this issue be linked to the milestone "Add and Delete cards" ?

**Comment by rcdexta** [comment]
Added the ability to pass `newCardTemplate` prop to override the new card form when adding a card to a lane.

Example usage here: https://github.com/rcdexta/react-trello/blob/master/stories/EditableBoard.story.js#L77
