### ISSUE TITLE
Lane Dragging not working correctly?

### ISSUE THREAD

**Issue by jdclifton2** [rcdexta/react-trello#482]
Hello! 

I am just testing your library but it appears that the ability to drag lanes is not working properly. It seems that I can drag the cards properly, just not the lanes even when I set the draggable field to true. 

This could be pilot error on my part. I am currently just using static data if that matters.

**Comment by dfibuch** [comment]
> Nevermind. Just dumb.

I know this is a while ago and close but do you remember what fixed it? I've literally come across the same issue and I have no idea what I'm missing.

**Comment by dfibuch** [comment]
I was also being stupid, forgot to add the `draggable` param to `<Board>`.
