### ISSUE TITLE
onCardClick -> open Editor Modal for Task? 

### ISSUE THREAD

**Issue by MaxGolem** [rcdexta/react-trello#488]
Hey,
I'm pretty new to javascript, but I have to create a dashboard as a project for my intership.
Currently I'm trying to create some kind of card editor, which opens after a card is clicked.
My Idea was to create a class which extends components and loads the details of the clicked task by Id to a form (opens as a modal), which can be edited and the chages are saved (modal closes).
Is there a solution to get from card click to the opening of the editor?
I'm thankful for every type of input, thanks!

**Comment by MaxGolem** [comment]
I saw issue  #188. But I'm still not sure how to use that advise. Do I add this code to my app class or do i create a new class with the given code. I tried implementing it into my app class. The result is no error and no event.

**Comment by KaiSpencer** [comment]
Hi @MaxGolem 

I achieved this in my own application by using the custom component override ability, creating a near copy of the Card component, then making the necessary changes to the `MovableCardWrapper` component in the Card to use an onClick handler and then toggle a modal which I defined in my Card override.
