### ISSUE TITLE
Update board data issue

### ISSUE THREAD

**Issue by Felonius-Gru** [rcdexta/react-trello#49]
I am using custom card layout and I want to change card color when I move a card into another lane.
So, I set the draggable props to true.
And in handleDragEnd function, I set the status of class, so the component must be rendered again, but the color of the card was not changed.
I tried to debug and I noticed that update board view event occurs later than drawing cards.
Please check this issue and let me know how to solve this problem.
Thanks.

**Comment by rcdexta** [comment]
@Felonius-Gru To understand better, can you share your `handleDragEnd` function and any other relevant code pieces?

**Comment by Felonius-Gru** [comment]
Here is the code.

const CustomCard = props => {
    return (
            <div className='ticketIcon'
                style={{
                    border: '4px solid ' + props.cardColor
                }}>
                {props.icon ? <img alt="#" src={props.icon} /> : ''}
            </div>
    )
}

    onDragEnd = (cardId, sourceLandId, targetLaneId) => {
        const tickets = this.state.tickets
        var card = tickets.find((ticket) => { return ticket.id.toString() === cardId })
        card.status.color = tickets.find((ticket) => { return ticket.status.text.toString() === targetLaneId }).status.color
this.setState(card.status.color)
    };

  render() {
 // make data
// get color from status and set that one to data
        return (
                <Board
                    data={board}
                    draggable={true}
                    handleDragEnd={this.onDragEnd}
                    customCardLayout
                    style={style} >
                    <CustomCard/>
                </Board>
        );
    }

**Comment by rcdexta** [comment]
Okay I get what you are trying to do. I have created a new story to illustrate what you are attempting:

https://rcdexta.github.io/react-trello/?selectedKind=Custom%20Templates&selectedStory=Drag-n-Drop%20Styling&full=0&down=0&left=1&panelRight=0

![jan-09-2018 21-29-22](https://user-images.githubusercontent.com/900028/34731224-bbdb62f4-f587-11e7-86c9-4e5b0ba8aa5e.gif)

Refer to the code here: https://github.com/rcdexta/react-trello/blob/master/stories/CustomCardWithDrag.story.js

Also pull the latest release
