### ISSUE TITLE
Module Parse Error

### ISSUE THREAD

**Issue by Sokvanna1** [rcdexta/react-trello#5]
I get this error after I install react-trello then I run my environment. I'm using latest webpack, any ideas on how I can resolve this?

ERROR in ./~/react-trello/dist/styles/Dragula.scss
Module parse failed: /ui/node_modules/react-trello/dist/styles/Dragula.scss Unexpected token (1:0)
You may need an appropriate loader to handle this file type.

Thanks.

**Comment by rcdexta** [comment]
v1.11.5 should fix this issue. Thanks for pointing this out!

**Comment by Sokvanna1** [comment]
Almost but now when I run my environment I get this error:

webpack:///./~/custom-event/index.js?:24
'function' === typeof document.createEvent ? function CustomEvent (type,
params) {
                      ^

ReferenceError: document is not defined
    at eval (webpack:///./~/custom-event/index.js?:24:23)
    at eval (webpack:///./~/crossvent/src/crossvent.js?:3:19)
    at eval (webpack:///./~/dragula/dragula.js?:4:17)
    at eval
(webpack:///./~/react-trello/dist/components/BoardContainer.js?:21:16)

If I don't import Board from react-trello onto my component and run my
environment everything works fine no error. Then after that if I import the
board while my environment is running then it works. But if I stop my
environment then run it again with the Board import saved on my component,
I get the error above.

**Comment by rcdexta** [comment]
We have moved away from Dragula to React-dnd for drag-n-drop functionality. This dependency is no longer valid. @Sokvanna1 Can you please try again with the latest build?

**Comment by Sokvanna1** [comment]
thanks, looks like this works!
