### ISSUE TITLE
Webpack problem with editable ?

### ISSUE THREAD

**Issue by julienpillias** [rcdexta/react-trello#50]
Hi,

Having a problem wich maybe (or not) a problem with webpack.

Using react-trello and the editable props, wich works well on my dev station (using hot reload).
When going to production, i'm using webpack in prod configuration. All works fine, except the "editable" or react-trello. Their is no errors, other props of react-trello works well... (it's like editable is false, but in code it's true...)

Any idea what could be the problem ? 

Thank's for your help.

**Comment by rcdexta** [comment]
There was a problem with `editable` with one of the older versions released. Can you make sure you are packaging the right version with your project. Make sure a stale react-trello version is not present in node_modules folder

**Comment by julienpillias** [comment]
Still looking why this is not working. Did you already had an editable Board with webpack working ? 

All other props are working !

**Comment by rcdexta** [comment]
I maintain a sample create-react-app template project that uses react-trello component

https://github.com/rcdexta/react-trello-example

Please checkout the project and build a production package and try running that. The editable props work fine in the webpack build.

**Comment by julienpillias** [comment]
So, still having the problem.

Tried your project, with my webpack, and no problems ! 
Tried to change sevral things in my webpack conf, without succes...
It may or may not be a problem with my code... But without any erros, don't know where to start !

Is their any API to activate editable mode ?

**Comment by julienpillias** [comment]
up :)

**Comment by julienpillias** [comment]
It is quiet strange, because when inspecting with react tools, i can see the "editable":true
![trello](https://user-images.githubusercontent.com/30586898/34880416-a6684e8e-f7b0-11e7-8881-ead5d4401a15.PNG)

**Comment by rcdexta** [comment]
Ok with today's release, i have made the `editable` prop explicit for Lane and Card components as well. Check that out. Also if you react developer tools, check if the `editable` prop is passed as true for `Lane` and `Card` components on the board.

**Comment by julienpillias** [comment]
Thank's for the update.

Just tried, and still have a problem.
I've checked the props for lane and Cards => the editable props is not present.  (but is present on the Board element.)

Don't understund why...

![trello](https://user-images.githubusercontent.com/30586898/34939030-b7f37ba6-f9ea-11e7-9c35-fe073d583887.PNG)

Editable props is lost here : 
![trello2](https://user-images.githubusercontent.com/30586898/34939201-464b98fc-f9eb-11e7-8fd1-71c6d4f64ecb.PNG)

**Comment by rcdexta** [comment]
Can you inspect 

`<t ref=bound value() id="1" droppable=true title="Implantation">` and check the props. That is the lane component in the webpack build. That should have `editable` set to true!

Also, it's really weird that it's happening only in your webpack production build. If you can share atleast the code that is relevant to this issue, I can help you debug this issue!

**Comment by julienpillias** [comment]
Hi,

the editable props is present on `<t ref=bound value() id="1" droppable=true title="Implantation">`

On my local, I can see that the "span onclick add" is present  : 
![localtrello](https://user-images.githubusercontent.com/30586898/34986017-4cb95078-fab6-11e7-9ace-bc356de387aa.PNG)

but not on prod : 
![prodtrello](https://user-images.githubusercontent.com/30586898/34986023-5434b310-fab6-11e7-99d3-780e0a9cbfcd.PNG)

Strange !

**Comment by julienpillias** [comment]
And here is the webpack conf, if it can help you.

https://gist.github.com/julienpillias/25d38882360c1c7f74966e1a3c338a2f

**Comment by julienpillias** [comment]
After a bit of investigation, i've seen that the Lane componant does not have the same props on my local and in production.

In production, addCardLink, newCardTemplate, onCardAdd, onCardDelete are missing ! 
onCardClick is present in both side (local & production)

**Comment by julienpillias** [comment]
Style working on this.

for information, their is finaly no props editable in production on Lane component.

This one was present because i've done a test adding editable to the lane configuration : 

```
lanes: [
      {
        id: 'lane1',
        title: 'Planned Tasks',
        editable: true,
        cards: [...]
      },
     ...
]
```

But still not working. Diging in...

**Comment by julienpillias** [comment]
Just updated to last version, it works in production ! Don't what it was...

Any way, thank's for your help, we can close this :)

**Comment by rcdexta** [comment]
Glad to know. Thanks
