### ISSUE TITLE
cleanup outdated dependencies

### ISSUE THREAD

**Issue by lowsky** [rcdexta/react-trello#51]
Hi, this is a really great project and I also like to see how it used styled-component!

While running 
`npm outdated` I found tht some dependencies are outdated/old or could even be removed, because they are unused.

E.g. dependencies for testing, like
`
babel-jest
chai
chai-enzyme
enzyme
istanbul
jest
jest-cli
jsdom
mocha
react-addons-test-utils@15.6.0(deprecated in react@16!)
react-test-renderer@15.6.1
sinon
`
(for react-addons-test-utils, see note about migration/deprecation on https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#react-test-utils)

Even while some are difficult to upgrade, but I did not find any unit tests, yet ;-)

So how about reducing the list of dependencies?

As a follow-up, let's add some updated Jest based unit tests *later* in a separate task, when there was some time?

**Comment by rcdexta** [comment]
@lowsky Thanks for taking interest in this project. Yes this started as a small side project and test coverage has been in my laundry list for a long time and only featured get added on top and I should add tests asap.

I have created a milestone to track this: https://github.com/rcdexta/react-trello/milestone/4

As far as the dependencies are concerned, only the following are relevant:

```
    "immutability-helper": "^2.4.0",
    "lodash": "^4.17.4",
    "prop-types": "^15.6.0",
    "react-dnd": "^2.2.4",
    "react-dnd-html5-backend": "^2.2.4",
    "react-dnd-multi-backend": "^2.3.7",
    "react-dnd-touch-backend": "^0.3.11",
    "react-redux": "^5.0.3",
    "redux": "^3.6.0",
    "redux-actions": "^1.2.2",
    "redux-logger": "^3.0.6",
    "styled-components": "^2.1.1",
    "uuid": "^3.1.0"
```

rest of them are for the build or tests. While working on the testing milestone, i will prune them and will keep you posted.

If you would like to bootstrap jest based test framework on top of this component, please do send a PR. Would be happy to merge and contribute on top of that.. 

Thanks again!

**Comment by rcdexta** [comment]
Will keep this issue open to track these items...

**Comment by lowsky** [comment]
cool. I also think we should go with jest+enzyme.  
So, you don't mind if I prepare something?

**Comment by rcdexta** [comment]
@lowsky absolutely all right if you can add some basic component level tests with jest+enzyme. Please shoot a PR. Thanks!
