### ISSUE TITLE
Changing the Lane's and Card's Width has style problems when the lane number is too large

### ISSUE THREAD

**Issue by LeoCai** [rcdexta/react-trello#53]
When i change the **width style of the lane and card**, such as 
`{[
id:...,
style:{ width: 280 }, 
cards:[
cardStyle:{ width: 270 },
],
]}`
It is working properly when the lane number is less than 5, but when **the lane number is too large**, **the lane style return to default width (smaller than 280px)** while the card style's width is right.

**Comment by rcdexta** [comment]
I am not able to replicate this issue and everything renders fine when i try this custom width style. Please try with the latest release if this problem persists. If it doesn, could you please share the code where you face this issue?

**Comment by LeoCai** [comment]
My react-trello version is v1.26.0

when lane number is 4, style works good as below:
![image](https://user-images.githubusercontent.com/7079275/35223749-857c5a3e-ffbd-11e7-8ad3-cbbf9399d7ae.png)

when lane number more than 5, the lane's width return to default, while card's width works good:
![image](https://user-images.githubusercontent.com/7079275/35223810-b2e58e0a-ffbd-11e7-9211-31e4511fef1c.png)

my code is as bellow:
```
const cardStyle = { width: 270, maxWidth: 270, margin: 'auto', marginBottom: 5 };
laneList.push({
        id: key,
        color: laneColors[i] || '#B2B2B2',
        // droppable: isDroppable(dragging, key, groupType, nextStateList, statusStageMap),
        title: `${laneInfo[key]}（${workitemList ? workitemList.length : 0}）`,
        style: isDroppable(dragging, key, groupType, nextStateList, statusStageMap) ?
          laneDroppableStyle : laneUnDroppableStyle,
        cards: workitemList && workitemList.length > 0 ? workitemList.sort((a, b) => a.priority - b.priority).map((item) => {
          return {
            ...item,
            id: item.sign,
            body: item.subject,
            cardStyle: {
              ...cardStyle,
            }
          };
        })
```

```
 <Board
            className={kanbanStyles.kanbanBoard}
            data={{ lanes: laneList }}
            draggable
            customCardLayout
            handleDragEnd={this.handleDragEnd.bind(this)}
            handleDragStart={this.handleDragStart.bind(this)}
            onCardClick={this.onWorkItemClick.bind(this)}
            customLaneHeader={<CustomLaneHeader />}
          >
            <CustomCard stateList={nextStateList} intl={intl} listMap={listMap} dispatch={dispatch} />
</Board>
```

**Comment by rcdexta** [comment]
ok thanks for the example. Will get back on this by tomorrow!

**Comment by rcdexta** [comment]
Should be fixed now.

Tested this usecase in this story: https://rcdexta.github.io/react-trello/?selectedKind=Advanced%20Features&selectedStory=Board%20Styling&full=0&down=0&left=1&panelRight=0
