### ISSUE TITLE
Is it possible to make lane header fixed when scroll?

### ISSUE THREAD

**Issue by LeoCai** [rcdexta/react-trello#54]
It would seem better to make lane header fixed when scroll the cards.
I like this project, and i would like to contribute code to support this feature.

**Comment by Felonius-Gru** [comment]
I have the same problem.
Please let me know if there is a way to fix lane header when scroll the cards

**Comment by LeoCai** [comment]
@Felonius-Gru 
you can try this to change the scroll behavior, this works for me:

.XXX.less
```
.kanbanBoard{
    .jgpevD{
      background-color:white;
      height:100%;
      overflow-y:hidden;
    }
    .jgpevD>div {
      height:100%;
    }
    .bHdfjd{
      max-height:94%;
      height:auto;
      overflow-y: auto;
    }
}
```
XXX.js
```
 <Board
            className={kanbanStyles.kanbanBoard}
....
          >
....
          </Board>
```

**Comment by rcdexta** [comment]
Lane header is fixed by default with latest release. Please check storybook for scroll behaviour.
