### ISSUE TITLE
console.log in default drag handler

### ISSUE THREAD

**Issue by julienpillias** [rcdexta/react-trello#55]
Hi,

You have leave some console.log in source code : 
https://github.com/rcdexta/react-trello/blob/66d233e2d769b74b026722ae210c5a1afc091ade/src/components/BoardContainer.js#L53
https://github.com/rcdexta/react-trello/blob/66d233e2d769b74b026722ae210c5a1afc091ade/src/components/BoardContainer.js#L58
and
https://github.com/rcdexta/react-trello/blob/63bc2fbae6adc69a7d255435749db4fba220a2f3/src/components/Lane.js#L146

regards

**Comment by rcdexta** [comment]
The log statements have been removed!
