### ISSUE TITLE
Customize delete button for editable cards

### ISSUE THREAD

**Issue by rcdexta** [rcdexta/react-trello#62]
Reference: #42 

Hi - Thanks for your work! Just wondering if it is possible to add custom component to the delete button? It fits well with standard setup but my styling is using material-ui components and I would like to change the delete button (or actually remove it - so I could have a popup show info on click)

![image](https://user-images.githubusercontent.com/24975408/35304821-da6b44c0-008e-11e8-9653-a69ae8b9a339.png)

Any idea??

Cheers,

M

**Comment by buddythumbs** [comment]
Sorry for piggybacking on previous issue!

**Comment by rcdexta** [comment]
v1.27.1 should fix this. 

Introduced a new prop called `hideCardDeleteIcon` which will hide the delete icon on cards when the board is `editable`. Refer to story for illustration:

https://rcdexta.github.io/react-trello/?selectedKind=Editable%20Board&selectedStory=Custom%20Buttons&full=0&down=0&left=1&panelRight=0
