### ISSUE TITLE
The item is pushed down by the height of the neighboring element.

### ISSUE THREAD

**Issue by HazemEngMuh** [rcdexta/react-trello#64]
When there is sides for container and we want to drag the item. It is pushed down by the height of container plus sides's height like this problem in another repository
https://drive.google.com/file/d/0B3mwXFEGAguUUkVKakZQOFpIVHc/view

**Comment by rcdexta** [comment]
Can you explain a bit more about what do you mean by sides of the container? Can you share sample code with the container where you use the `Board` component, so that I can understand better..

**Comment by HazemEngMuh** [comment]
`
      <Board
      editable
      onCardAdd={this.handleCardAdd}
      data={this.state.boardData}
      draggable
      onDataChange={this.shouldReceiveNewData}
      eventBusHandle={this.setEventBus}
      handleDragStart={handleDragStart}
      handleDragEnd={handleDragEnd}
  />`
I used basic example as above. In my project I have menu on the left of screen and use plugins, Where plugins start after menu's area is finished. When I move a card, the card's transform as the externel container I mean menu's width is calculating and increasing to card's transform(css).
It is same to this problem https://drive.google.com/file/d/0B3mwXFEGAguUUkVKakZQOFpIVHc/view

**Comment by rcdexta** [comment]
v1.27.0 should address this issue. Can you please check and confirm?

**Comment by rcdexta** [comment]
I used some React 16 specific features. Reverted them for backward compatibility. Check v1.27.2.

**Comment by HazemEngMuh** [comment]
Main bug is not solved

**Comment by orangecoding** [comment]
I experienced kind of the same problem. If I drag a card around, and drop it into an empty lane, the card is first being shown at the top, outside of the lane, then transformed into the lane with a fancy move animation. Might be because I did some heavy styling around the board to match it our container style.. Need to dig deeper though..

**Comment by rcdexta** [comment]
Release v1.28.1 has bug fixes for drag-n-drop and upgraded version of react-beautiful-dnd dependency

**Comment by HazemEngMuh** [comment]
Problem still exist
