### ISSUE TITLE
Multiple Boards With Different Data Is Not Supported

### ISSUE THREAD

**Issue by eshirazp** [rcdexta/react-trello#65]
I can not make multiple boards with different data inside the same component. 

For example, if I can't return a JSX component that contains Board1 and Board2, with different lanes and cards. Board1, being rendered first, will pick up the lanes and cards of Board2, thus being the same exact thing.

**Comment by aditigoel23** [comment]
Is support for this on the roadmap?

**Comment by rcdexta** [comment]
Support added for multiple boards in 1.28.0

Example: http://rcdexta.me/react-trello/?selectedKind=Multiple%20Boards&selectedStory=Two%20Boards&full=0&down=0&left=1&panelRight=0

**Comment by aditigoel23** [comment]
thanks!
