### ISSUE TITLE
Support styling of lanes

### ISSUE THREAD

**Issue by orangecoding** [rcdexta/react-trello#68]
Is it somehow possible to style the lanes? Currently I'm doing it by setting the `className` of the board and in there I set 
```
section {...}
```

Thanks

**Comment by rcdexta** [comment]
It is possible to override the `style`, `titleStyle` and `labelStyle` props passed to lane in the data.json to customise the lane look-and-feel.

Example here: https://github.com/rcdexta/react-trello/blob/master/stories/CustomCardStyling.story.js

You can specify your own template for lane as well like this:

https://github.com/rcdexta/react-trello/blob/master/stories/CustomLaneStyling.story.js

Check out the storybook to see how it renders on the screen!
