### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by edudavid** [rcdexta/react-trello#7]
Hello @rcdexta,

I have two questions about the component:

1) How can I get card index inside lane. For example, if I want to persist the cards position inside a lane, how do I know its position?

2) Is it possible to drop card in a specific position when moving across lanes?

Regards,

Eduardo

**Comment by rcdexta** [comment]
The way `react-trello` was designed to work is that after `data` prop is passed as initial state, any change to the state will be passed out using the `onDataChange` callback function

If you refer this sample code from the story: https://github.com/rcdexta/react-trello/blob/master/stories/DragDrop.story.js

anytime a card is moved from one lane to another or to a different position within the same lane, `onDataChange(newData)` will be called with the updated lane details. 

Inspecting `newData` should answer both your requirements (1) and (2). We could see if having hooks at board level is too generic and can we have much more granular hooks?

Let me know if this works for you..

**Comment by edudavid** [comment]
Hello @rcdexta ,

Thank you for your reply.

Regarding question one, ok, I can easily get cards index with the `onDataChange(newData)`.

Regarding question two, I believe it is more complex. I was expecting to have the same behavior when moving cards between lanes as when moving cards inside lane.

When I am moving a card inside a lane, a can select at what position I want to drop the card. But when I move a card from one lane to another, the dropped card is placed at the end of the lane it was dropped.

This behavior can be seen at the project demo:

https://raw.githubusercontent.com/rcdexta/react-trello/master/react-trello.gif

How can we have this behavior?

Regards,

Eduardo

**Comment by rcdexta** [comment]
Aaah I see. I think the only workaround right now is to move the card across lane and again reorder within lane. I am working on retaining order when dragging card across lanes. Will keep you posted!

**Comment by edudavid** [comment]
Hello @rcdexta ,

I worked on the component this weekend and I believe I am reaching a satisfatory result. The implementation still have some issues, but I am working on them.

Here is the link of the branch I am working.
[https://github.com/edudavid/react-trello/tree/ed-drag-between-lanes](https://github.com/edudavid/react-trello/tree/ed-drag-between-lanes)

The changed files:
- src/components/Lane
- src/helpers/LaneHelper
- src/styles/Base

I was wondering if you could take a look and let me know your opinion about the approach. If it`s ok, I can finish and send a pull request.

Regards,

Eduardo

**Comment by rcdexta** [comment]
Looked at the code and it looks really cool. I had just one comment related to index existence check and everything else looks good. 

Thanks a lot for doing this @edudavid. Please submit a PR and will merge
