### ISSUE TITLE
Multiple card movement

### ISSUE THREAD

**Issue by Felonius-Gru** [rcdexta/react-trello#70]
I just added a checkbox to each card using customcardStyle.

Is there any way to drag and drop multiple selected cards at one time?

**Comment by rcdexta** [comment]
No right now, it is not possible to drag multiple cards. Also, it is not a good UX pattern, to allow moving multiple cards (it makes it even difficult if it is not contiguous) using drag-n-drop.

I would suggest to have a toolbar at the top with a move to button that asks for the target lane to move the cards to. Refer to the `Move Cards` functionality in actual Trello board for inspiration!
