### ISSUE TITLE
Is there a plan to upgrade react-beautiful-dnd to 7.x

### ISSUE THREAD

**Issue by aditigoel23** [rcdexta/react-trello#82]
Seems to have some nice performance improvements - https://github.com/atlassian/react-beautiful-dnd/releases/tag/v7.0.0

**Comment by rcdexta** [comment]
Done!

**Comment by LucasPerso** [comment]
Hi there !

Unfortunately, upgrading to react-beautiful-dnd breaks backward compatibility as v7.x is not compatible with React 15.x

Therefore, any version of react-trello above 1.29.0 won't work with React 15.x as there is no Fragment support

**Comment by rcdexta** [comment]
react-trello v1.30.0 onwards does not use react-beautiful-dnd for drag-n-drop support. So, upgrade to the latest for backward compatibility with React 15.x

**Comment by LucasPerso** [comment]
Thank you for your prompt answer.

It appears `smooth-dnd` does not support server-side rendering which was one of react-beautiful-dnd features. It does break the compatibility with previous versions.

**Comment by rcdexta** [comment]
@LucasPerso The latest version of react-smooth-dnd supports SSR and react-trello should support it too now. Please pull the latest release and should work.

**Comment by LucasPerso** [comment]
Thank you for the information. I will have look !
