### ISSUE TITLE
Can I drag lane to reorder lanes？

### ISSUE THREAD

**Issue by changyu72** [rcdexta/react-trello#83]
Can I drag lane to reorder lanes？

**Comment by rcdexta** [comment]
Currently, drag-n-drop for lanes is not supported.

Tracked here: https://github.com/rcdexta/react-trello/issues/30

Hoping to add it soon!

**Comment by rcdexta** [comment]
Duplicate of https://github.com/rcdexta/react-trello/issues/30

**Comment by changyu72** [comment]
Oh, looking forward to it, thank you！
