### ISSUE TITLE
Export all actions from BoardReducer to event bus?

### ISSUE THREAD

**Issue by cnupm** [rcdexta/react-trello#84]
ATM eventbus exports only 'ADD_CARD', 'REMOVE_CARD', 'REFRESH_BOARD', 'MOVE_CARD', so there is no way to add new lane 'on the fly' without REFRESH_BOARD call, while reducer contains 'UPDATE_LANE' action

**Comment by rcdexta** [comment]
Should be available in the the latest release. Refer README for details.

More specialised actions to add, update or remove lane coming in next major release.
