### ISSUE TITLE
Add/Remove/Update lanes

### ISSUE THREAD

**Issue by aktjerry** [rcdexta/react-trello#89]
It's an awesome library but missing the feature to add or remove or update lanes.

**Comment by panytsch** [comment]
You actually can update 'data' array. I mean you can remove or push new item, and component will rerender. It's not a problem i think

**Comment by rcdexta** [comment]
Yes @panytsch suggested you can modify `data.lanes` prop directly to get the lanes updated or use `UPDATE_LANES` event available in event bus

**Comment by MukeshNegi-brillmark** [comment]
@rcdexta Can you provide a simple example for deleting a lane using event bus or any other method
or provide a link to get help other than the package example
