### ISSUE TITLE
Touch responsive

### ISSUE THREAD

**Issue by manpreetAulakh** [rcdexta/react-trello#9]
Hi,
Great Component.
I was wondering if it works for touch Events also,  for iPads or phones?

It responds to click events on desktop but doesn't responding to touch events.

**Comment by rcdexta** [comment]
@manpreetAulakh Thanks for pointing that out. v1.17.1 should work for touch devices as well. I still have to get the css look-and-feel for touch devices when dragging the card. Will do it when I have time, or if you can do that and send a PR, will be glad to merge it. Thanks!
