### ISSUE TITLE
Lane title/label/id cannot be updated

### ISSUE THREAD

**Issue by LucianBuzzo** [rcdexta/react-trello#92]
The only way to modify the `title` of a lane after its been rendered is to destroy and remount the `Lane` component somehow. This is due to the `shouldComponentUpdate` code here https://github.com/rcdexta/react-trello/blob/master/src/components/Lane.js#L76
Does this need to be here? Can it be removed?

**Comment by rcdexta** [comment]
Details available in the commit. This method is removed now.
