### ISSUE TITLE
Can't resolve 'styled-components' in 1.31.3

### ISSUE THREAD

**Issue by Menogus** [rcdexta/react-trello#94]
./node_modules/react-trello/dist/styles/Base.js
Module not found: Can't resolve 'styled-components' in 'F:\GIT\trello\node_modules\react-trello\dist\styles'

also:
<Provider> does not support changing `store` on the fly. It is most likely that you see this error because you updated to Redux 2.x and React Redux 2.x which no longer hot reload reducers automatically. See https://github.com/reactjs/react-redux/releases/tag/v2.0.0 for the migration instructions.

**Comment by rcdexta** [comment]
Should be addressed in 1.31.4

**Comment by casprian** [comment]
Module not found: Error: Can't resolve 'styled-components' in '*/node_modules/react-trello/dist/styles'

**Comment by sstalder** [comment]
You need to run `npm install styled-components` as it appears the dependency is not in the right place.
