### ISSUE TITLE
Add metadata as argument to handleDragEnd to make it more extensible

### ISSUE THREAD

**Issue by cmccarthy15** [rcdexta/react-trello#97]
In my project, I need to be able to call additional actions at drag end based on some of the card information that is stored in the metadata. Without it, I am unable to determine the correct next actions to take. I imagine others may have come across similar situations and thinking adding metadata as a argument for handleDragEnd adds a lot more control and options for way to integrate react-trello into the app. 

To solve for my use case, I just updated the following within Lane.js: 

```
_this.onDragEnd = function (laneId, result) {
      var handleDragEnd = _this.props.handleDragEnd;
      var addedIndex = result.addedIndex,
          payload = result.payload;

      if (addedIndex != null) {
        _this.props.actions.moveCardAcrossLanes({
          fromLaneId: payload.laneId,
          toLaneId: laneId,
          cardId: payload.id,
          index: addedIndex
        });
        handleDragEnd && handleDragEnd(payload.id, payload.laneId, laneId, addedIndex, payload.metadata);
      }
    },
```

If there are other ways of getting more detailed information about the card that was dropped already built out, please let me know!
Thanks!

**Comment by rcdexta** [comment]
Please pull latest release. `handleDragEnd` callback function should pass `cardData` as the last argument
