### ISSUE TITLE
Make cards draggable without making lanes draggable

### ISSUE THREAD

**Issue by cmccarthy15** [rcdexta/react-trello#98]
I need to disable lane dragging while still allowing for cards to be dragged between lanes. Currently the draggable prop controls both lanes and cards. I suggest two props instead - draggableLanes and draggableCards to give more nuanced control of the board behavior.

**Comment by rcdexta** [comment]
Added `laneDraggable` and `cardDraggable` props to override card or lane dragging behaviour. Updated README to document attributes. Please pull latest release.
